(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Awso_iot1click_devices.Values
val claim_devices_by_claim_code :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ClaimDevicesByClaimCodeRequest.t ->
        (ClaimDevicesByClaimCodeResponse.t,
          ClaimDevicesByClaimCodeResponse.error) Result.t Async.Deferred.t
val describe_device :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeDeviceRequest.t ->
        (DescribeDeviceResponse.t, DescribeDeviceResponse.error) Result.t
          Async.Deferred.t
val finalize_device_claim :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      FinalizeDeviceClaimRequest.t ->
        (FinalizeDeviceClaimResponse.t, FinalizeDeviceClaimResponse.error)
          Result.t Async.Deferred.t
val get_device_methods :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      GetDeviceMethodsRequest.t ->
        (GetDeviceMethodsResponse.t, GetDeviceMethodsResponse.error) Result.t
          Async.Deferred.t
val initiate_device_claim :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      InitiateDeviceClaimRequest.t ->
        (InitiateDeviceClaimResponse.t, InitiateDeviceClaimResponse.error)
          Result.t Async.Deferred.t
val invoke_device_method :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      InvokeDeviceMethodRequest.t ->
        (InvokeDeviceMethodResponse.t, InvokeDeviceMethodResponse.error)
          Result.t Async.Deferred.t
val list_device_events :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListDeviceEventsRequest.t ->
        (ListDeviceEventsResponse.t, ListDeviceEventsResponse.error) Result.t
          Async.Deferred.t
val list_devices :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListDevicesRequest.t ->
        (ListDevicesResponse.t, ListDevicesResponse.error) Result.t
          Async.Deferred.t
val list_tags_for_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListTagsForResourceRequest.t ->
        (ListTagsForResourceResponse.t, ListTagsForResourceResponse.error)
          Result.t Async.Deferred.t
val tag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      TagResourceRequest.t -> (unit, unit) Result.t Async.Deferred.t
val unclaim_device :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UnclaimDeviceRequest.t ->
        (UnclaimDeviceResponse.t, UnclaimDeviceResponse.error) Result.t
          Async.Deferred.t
val untag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UntagResourceRequest.t -> (unit, unit) Result.t Async.Deferred.t
val update_device_state :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UpdateDeviceStateRequest.t ->
        (UpdateDeviceStateResponse.t, UpdateDeviceStateResponse.error)
          Result.t Async.Deferred.t