(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Core
open Async
let json_arg = Command.Arg_type.create Yojson.Safe.from_string
let call ?endpoint_url ?profile ?region f m result_to_json error_to_json =
  let region =
    match region with
    | Some region -> Some (Awso.Region.of_string region)
    | None -> None in
  (Awso_async.Cfg.get_exn ?profile ?region ()) >>=
    (fun cfg ->
       (f ?endpoint_url ?cfg:(Some cfg) m) >>=
         (fun result ->
            match result with
            | Error err ->
                (match error_to_json with
                 | None ->
                     failwithf
                       "endpoint error, but no error values defined in boto"
                       ()
                 | Some to_json ->
                     let s = (err |> to_json) |> Yojson.Safe.to_string in
                     failwithf "AWS error: %s" s ())
            | Ok result ->
                ((match result_to_json with
                  | None -> print_endline "ok response from endpoint"
                  | Some to_json ->
                      ((result |> to_json) |> Yojson.Safe.to_string) |>
                        print_endline);
                 return ())))
let autocomplete =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int)
           ~doc:"INT AutocompleteRequestMaxResultsInteger"
       and biasPosition =
         flag "bias-position" (optional json_arg) ~doc:"JSON Position"
       and filter =
         flag "filter" (optional json_arg) ~doc:"JSON AutocompleteFilter"
       and postalCodeMode =
         flag "postal-code-mode" (optional json_arg)
           ~doc:"JSON PostalCodeMode"
       and additionalFeatures =
         flag "additional-features" (optional json_arg)
           ~doc:"JSON AutocompleteAdditionalFeatureList"
       and language =
         flag "language" (optional string) ~doc:"STRING LanguageTag"
       and politicalView =
         flag "political-view" (optional string) ~doc:"STRING CountryCode"
       and intendedUse =
         flag "intended-use" (optional json_arg)
           ~doc:"JSON AutocompleteIntendedUse"
       and key = flag "key" (optional string) ~doc:"STRING ApiKey"
       and queryText =
         flag "query-text" (required string)
           ~doc:"STRING AutocompleteRequestQueryTextString" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.autocomplete
           (Values.AutocompleteRequest.make ?maxResults
              ?biasPosition:(Option.map ~f:Values.Position.of_json
                               biasPosition)
              ?filter:(Option.map ~f:Values.AutocompleteFilter.of_json filter)
              ?postalCodeMode:(Option.map ~f:Values.PostalCodeMode.of_json
                                 postalCodeMode)
              ?additionalFeatures:(Option.map
                                     ~f:Values.AutocompleteAdditionalFeatureList.of_json
                                     additionalFeatures) ?language
              ?politicalView
              ?intendedUse:(Option.map
                              ~f:Values.AutocompleteIntendedUse.of_json
                              intendedUse) ?key ~queryText ())
           (Some Values.AutocompleteResponse.to_json)
           (Some Values.AutocompleteResponse.error_to_json)])
let geocode =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and queryText =
         flag "query-text" (optional string)
           ~doc:"STRING GeocodeRequestQueryTextString"
       and queryComponents =
         flag "query-components" (optional json_arg)
           ~doc:"JSON GeocodeQueryComponents"
       and maxResults =
         flag "max-results" (optional int)
           ~doc:"INT GeocodeRequestMaxResultsInteger"
       and biasPosition =
         flag "bias-position" (optional json_arg) ~doc:"JSON Position"
       and filter =
         flag "filter" (optional json_arg) ~doc:"JSON GeocodeFilter"
       and additionalFeatures =
         flag "additional-features" (optional json_arg)
           ~doc:"JSON GeocodeAdditionalFeatureList"
       and language =
         flag "language" (optional string) ~doc:"STRING LanguageTag"
       and politicalView =
         flag "political-view" (optional string) ~doc:"STRING CountryCode"
       and intendedUse =
         flag "intended-use" (optional json_arg)
           ~doc:"JSON GeocodeIntendedUse"
       and key = flag "key" (optional string) ~doc:"STRING ApiKey" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.geocode
           (Values.GeocodeRequest.make ?queryText
              ?queryComponents:(Option.map
                                  ~f:Values.GeocodeQueryComponents.of_json
                                  queryComponents) ?maxResults
              ?biasPosition:(Option.map ~f:Values.Position.of_json
                               biasPosition)
              ?filter:(Option.map ~f:Values.GeocodeFilter.of_json filter)
              ?additionalFeatures:(Option.map
                                     ~f:Values.GeocodeAdditionalFeatureList.of_json
                                     additionalFeatures) ?language
              ?politicalView
              ?intendedUse:(Option.map ~f:Values.GeocodeIntendedUse.of_json
                              intendedUse) ?key ())
           (Some Values.GeocodeResponse.to_json)
           (Some Values.GeocodeResponse.error_to_json)])
let get_place =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and additionalFeatures =
         flag "additional-features" (optional json_arg)
           ~doc:"JSON GetPlaceAdditionalFeatureList"
       and language =
         flag "language" (optional string) ~doc:"STRING LanguageTag"
       and politicalView =
         flag "political-view" (optional string) ~doc:"STRING CountryCode"
       and intendedUse =
         flag "intended-use" (optional json_arg)
           ~doc:"JSON GetPlaceIntendedUse"
       and key = flag "key" (optional string) ~doc:"STRING ApiKey"
       and placeId =
         flag "place-id" (required string)
           ~doc:"STRING GetPlaceRequestPlaceIdString" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_place
           (Values.GetPlaceRequest.make
              ?additionalFeatures:(Option.map
                                     ~f:Values.GetPlaceAdditionalFeatureList.of_json
                                     additionalFeatures) ?language
              ?politicalView
              ?intendedUse:(Option.map ~f:Values.GetPlaceIntendedUse.of_json
                              intendedUse) ?key ~placeId ())
           (Some Values.GetPlaceResponse.to_json)
           (Some Values.GetPlaceResponse.error_to_json)])
let reverse_geocode =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and queryRadius =
         flag "query-radius" (optional json_arg)
           ~doc:"JSON ReverseGeocodeRequestQueryRadiusLong"
       and maxResults =
         flag "max-results" (optional int)
           ~doc:"INT ReverseGeocodeRequestMaxResultsInteger"
       and filter =
         flag "filter" (optional json_arg) ~doc:"JSON ReverseGeocodeFilter"
       and additionalFeatures =
         flag "additional-features" (optional json_arg)
           ~doc:"JSON ReverseGeocodeAdditionalFeatureList"
       and language =
         flag "language" (optional string) ~doc:"STRING LanguageTag"
       and politicalView =
         flag "political-view" (optional string) ~doc:"STRING CountryCode"
       and intendedUse =
         flag "intended-use" (optional json_arg)
           ~doc:"JSON ReverseGeocodeIntendedUse"
       and key = flag "key" (optional string) ~doc:"STRING ApiKey"
       and heading = flag "heading" (optional float) ~doc:"FLOAT Heading"
       and queryPosition =
         flag "query-position" (required json_arg) ~doc:"JSON Position" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.reverse_geocode
           (Values.ReverseGeocodeRequest.make
              ?queryRadius:(Option.map
                              ~f:Values.ReverseGeocodeRequestQueryRadiusLong.of_json
                              queryRadius) ?maxResults
              ?filter:(Option.map ~f:Values.ReverseGeocodeFilter.of_json
                         filter)
              ?additionalFeatures:(Option.map
                                     ~f:Values.ReverseGeocodeAdditionalFeatureList.of_json
                                     additionalFeatures) ?language
              ?politicalView
              ?intendedUse:(Option.map
                              ~f:Values.ReverseGeocodeIntendedUse.of_json
                              intendedUse) ?key ?heading
              ~queryPosition:(Values.Position.of_json queryPosition) ())
           (Some Values.ReverseGeocodeResponse.to_json)
           (Some Values.ReverseGeocodeResponse.error_to_json)])
let search_nearby =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and queryRadius =
         flag "query-radius" (optional json_arg)
           ~doc:"JSON SearchNearbyRequestQueryRadiusLong"
       and maxResults =
         flag "max-results" (optional int)
           ~doc:"INT SearchNearbyRequestMaxResultsInteger"
       and filter =
         flag "filter" (optional json_arg) ~doc:"JSON SearchNearbyFilter"
       and additionalFeatures =
         flag "additional-features" (optional json_arg)
           ~doc:"JSON SearchNearbyAdditionalFeatureList"
       and language =
         flag "language" (optional string) ~doc:"STRING LanguageTag"
       and politicalView =
         flag "political-view" (optional string) ~doc:"STRING CountryCode"
       and intendedUse =
         flag "intended-use" (optional json_arg)
           ~doc:"JSON SearchNearbyIntendedUse"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING Token"
       and key = flag "key" (optional string) ~doc:"STRING ApiKey"
       and queryPosition =
         flag "query-position" (required json_arg) ~doc:"JSON Position" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.search_nearby
           (Values.SearchNearbyRequest.make
              ?queryRadius:(Option.map
                              ~f:Values.SearchNearbyRequestQueryRadiusLong.of_json
                              queryRadius) ?maxResults
              ?filter:(Option.map ~f:Values.SearchNearbyFilter.of_json filter)
              ?additionalFeatures:(Option.map
                                     ~f:Values.SearchNearbyAdditionalFeatureList.of_json
                                     additionalFeatures) ?language
              ?politicalView
              ?intendedUse:(Option.map
                              ~f:Values.SearchNearbyIntendedUse.of_json
                              intendedUse) ?nextToken ?key
              ~queryPosition:(Values.Position.of_json queryPosition) ())
           (Some Values.SearchNearbyResponse.to_json)
           (Some Values.SearchNearbyResponse.error_to_json)])
let search_text =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and queryText =
         flag "query-text" (optional string)
           ~doc:"STRING SearchTextRequestQueryTextString"
       and queryId =
         flag "query-id" (optional string)
           ~doc:"STRING SearchTextRequestQueryIdString"
       and maxResults =
         flag "max-results" (optional int)
           ~doc:"INT SearchTextRequestMaxResultsInteger"
       and biasPosition =
         flag "bias-position" (optional json_arg) ~doc:"JSON Position"
       and filter =
         flag "filter" (optional json_arg) ~doc:"JSON SearchTextFilter"
       and additionalFeatures =
         flag "additional-features" (optional json_arg)
           ~doc:"JSON SearchTextAdditionalFeatureList"
       and language =
         flag "language" (optional string) ~doc:"STRING LanguageTag"
       and politicalView =
         flag "political-view" (optional string) ~doc:"STRING CountryCode"
       and intendedUse =
         flag "intended-use" (optional json_arg)
           ~doc:"JSON SearchTextIntendedUse"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING Token"
       and key = flag "key" (optional string) ~doc:"STRING ApiKey" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.search_text
           (Values.SearchTextRequest.make ?queryText ?queryId ?maxResults
              ?biasPosition:(Option.map ~f:Values.Position.of_json
                               biasPosition)
              ?filter:(Option.map ~f:Values.SearchTextFilter.of_json filter)
              ?additionalFeatures:(Option.map
                                     ~f:Values.SearchTextAdditionalFeatureList.of_json
                                     additionalFeatures) ?language
              ?politicalView
              ?intendedUse:(Option.map
                              ~f:Values.SearchTextIntendedUse.of_json
                              intendedUse) ?nextToken ?key ())
           (Some Values.SearchTextResponse.to_json)
           (Some Values.SearchTextResponse.error_to_json)])
let suggest =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int)
           ~doc:"INT SuggestRequestMaxResultsInteger"
       and maxQueryRefinements =
         flag "max-query-refinements" (optional int)
           ~doc:"INT SuggestRequestMaxQueryRefinementsInteger"
       and biasPosition =
         flag "bias-position" (optional json_arg) ~doc:"JSON Position"
       and filter =
         flag "filter" (optional json_arg) ~doc:"JSON SuggestFilter"
       and additionalFeatures =
         flag "additional-features" (optional json_arg)
           ~doc:"JSON SuggestAdditionalFeatureList"
       and language =
         flag "language" (optional string) ~doc:"STRING LanguageTag"
       and politicalView =
         flag "political-view" (optional string) ~doc:"STRING CountryCode"
       and intendedUse =
         flag "intended-use" (optional json_arg)
           ~doc:"JSON SuggestIntendedUse"
       and key = flag "key" (optional string) ~doc:"STRING ApiKey"
       and queryText =
         flag "query-text" (required string)
           ~doc:"STRING SuggestRequestQueryTextString" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.suggest
           (Values.SuggestRequest.make ?maxResults ?maxQueryRefinements
              ?biasPosition:(Option.map ~f:Values.Position.of_json
                               biasPosition)
              ?filter:(Option.map ~f:Values.SuggestFilter.of_json filter)
              ?additionalFeatures:(Option.map
                                     ~f:Values.SuggestAdditionalFeatureList.of_json
                                     additionalFeatures) ?language
              ?politicalView
              ?intendedUse:(Option.map ~f:Values.SuggestIntendedUse.of_json
                              intendedUse) ?key ~queryText ())
           (Some Values.SuggestResponse.to_json)
           (Some Values.SuggestResponse.error_to_json)])
let main =
  Command.group
    ~summary:((Awso.Service.to_string Values.service) ^ " commands")
    [("autocomplete", autocomplete);
    ("geocode", geocode);
    ("get-place", get_place);
    ("reverse-geocode", reverse_geocode);
    ("search-nearby", search_nearby);
    ("search-text", search_text);
    ("suggest", suggest)]