(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Awso_pinpoint_email
open Awso_eio
module Io = Http.Io
let eval ?endpoint_url ?cfg endpoint input =
  Io.bind (Io.resolve_cfg cfg)
    (fun cfg ->
       let meth = Endpoints.method_of_endpoint endpoint in
       let uri = Endpoints.uri_of_endpoint endpoint input in
       Io.map
         (Io.call ?endpoint_url ~cfg ~service:Values.service meth
            (Endpoints.to_request endpoint input) uri)
         (fun resp_result -> Endpoints.of_response endpoint resp_result))
let create_configuration_set ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.CreateConfigurationSet input
let create_configuration_set_event_destination ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.CreateConfigurationSetEventDestination
    input
let create_dedicated_ip_pool ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.CreateDedicatedIpPool input
let create_deliverability_test_report ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.CreateDeliverabilityTestReport input
let create_email_identity ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.CreateEmailIdentity input
let delete_configuration_set ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.DeleteConfigurationSet input
let delete_configuration_set_event_destination ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.DeleteConfigurationSetEventDestination
    input
let delete_dedicated_ip_pool ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.DeleteDedicatedIpPool input
let delete_email_identity ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.DeleteEmailIdentity input
let get_account ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetAccount input
let get_blacklist_reports ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetBlacklistReports input
let get_configuration_set ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetConfigurationSet input
let get_configuration_set_event_destinations ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetConfigurationSetEventDestinations
    input
let get_dedicated_ip ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetDedicatedIp input
let get_dedicated_ips ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetDedicatedIps input
let get_deliverability_dashboard_options ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetDeliverabilityDashboardOptions input
let get_deliverability_test_report ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetDeliverabilityTestReport input
let get_domain_deliverability_campaign ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetDomainDeliverabilityCampaign input
let get_domain_statistics_report ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetDomainStatisticsReport input
let get_email_identity ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.GetEmailIdentity input
let list_configuration_sets ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.ListConfigurationSets input
let list_dedicated_ip_pools ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.ListDedicatedIpPools input
let list_deliverability_test_reports ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.ListDeliverabilityTestReports input
let list_domain_deliverability_campaigns ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.ListDomainDeliverabilityCampaigns input
let list_email_identities ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.ListEmailIdentities input
let list_tags_for_resource ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.ListTagsForResource input
let put_account_dedicated_ip_warmup_attributes ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutAccountDedicatedIpWarmupAttributes
    input
let put_account_sending_attributes ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutAccountSendingAttributes input
let put_configuration_set_delivery_options ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutConfigurationSetDeliveryOptions input
let put_configuration_set_reputation_options ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutConfigurationSetReputationOptions
    input
let put_configuration_set_sending_options ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutConfigurationSetSendingOptions input
let put_configuration_set_tracking_options ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutConfigurationSetTrackingOptions input
let put_dedicated_ip_in_pool ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutDedicatedIpInPool input
let put_dedicated_ip_warmup_attributes ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutDedicatedIpWarmupAttributes input
let put_deliverability_dashboard_option ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutDeliverabilityDashboardOption input
let put_email_identity_dkim_attributes ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutEmailIdentityDkimAttributes input
let put_email_identity_feedback_attributes ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutEmailIdentityFeedbackAttributes input
let put_email_identity_mail_from_attributes ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.PutEmailIdentityMailFromAttributes input
let send_email ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.SendEmail input
let tag_resource ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.TagResource input
let untag_resource ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.UntagResource input
let update_configuration_set_event_destination ?endpoint_url ?cfg input =
  eval ?endpoint_url ?cfg Endpoints.UpdateConfigurationSetEventDestination
    input