(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Awso_forecast.Values
val create_auto_predictor :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateAutoPredictorRequest.t ->
        (CreateAutoPredictorResponse.t,
          [ `AWS of CreateAutoPredictorResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val create_dataset :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateDatasetRequest.t ->
        (CreateDatasetResponse.t,
          [ `AWS of CreateDatasetResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val create_dataset_group :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateDatasetGroupRequest.t ->
        (CreateDatasetGroupResponse.t,
          [ `AWS of CreateDatasetGroupResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val create_dataset_import_job :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateDatasetImportJobRequest.t ->
        (CreateDatasetImportJobResponse.t,
          [ `AWS of CreateDatasetImportJobResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val create_explainability :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateExplainabilityRequest.t ->
        (CreateExplainabilityResponse.t,
          [ `AWS of CreateExplainabilityResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val create_explainability_export :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateExplainabilityExportRequest.t ->
        (CreateExplainabilityExportResponse.t,
          [ `AWS of CreateExplainabilityExportResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val create_forecast :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateForecastRequest.t ->
        (CreateForecastResponse.t,
          [ `AWS of CreateForecastResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val create_forecast_export_job :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateForecastExportJobRequest.t ->
        (CreateForecastExportJobResponse.t,
          [ `AWS of CreateForecastExportJobResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val create_predictor :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreatePredictorRequest.t ->
        (CreatePredictorResponse.t,
          [ `AWS of CreatePredictorResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val create_predictor_backtest_export_job :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreatePredictorBacktestExportJobRequest.t ->
        (CreatePredictorBacktestExportJobResponse.t,
          [ `AWS of CreatePredictorBacktestExportJobResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val delete_dataset :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteDatasetRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val delete_dataset_group :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteDatasetGroupRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val delete_dataset_import_job :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteDatasetImportJobRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val delete_explainability :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteExplainabilityRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val delete_explainability_export :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteExplainabilityExportRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val delete_forecast :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteForecastRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val delete_forecast_export_job :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteForecastExportJobRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val delete_predictor :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeletePredictorRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val delete_predictor_backtest_export_job :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeletePredictorBacktestExportJobRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val delete_resource_tree :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteResourceTreeRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val describe_auto_predictor :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeAutoPredictorRequest.t ->
        (DescribeAutoPredictorResponse.t,
          [ `AWS of DescribeAutoPredictorResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val describe_dataset :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeDatasetRequest.t ->
        (DescribeDatasetResponse.t,
          [ `AWS of DescribeDatasetResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val describe_dataset_group :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeDatasetGroupRequest.t ->
        (DescribeDatasetGroupResponse.t,
          [ `AWS of DescribeDatasetGroupResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val describe_dataset_import_job :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeDatasetImportJobRequest.t ->
        (DescribeDatasetImportJobResponse.t,
          [ `AWS of DescribeDatasetImportJobResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val describe_explainability :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeExplainabilityRequest.t ->
        (DescribeExplainabilityResponse.t,
          [ `AWS of DescribeExplainabilityResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val describe_explainability_export :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeExplainabilityExportRequest.t ->
        (DescribeExplainabilityExportResponse.t,
          [ `AWS of DescribeExplainabilityExportResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val describe_forecast :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeForecastRequest.t ->
        (DescribeForecastResponse.t,
          [ `AWS of DescribeForecastResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val describe_forecast_export_job :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeForecastExportJobRequest.t ->
        (DescribeForecastExportJobResponse.t,
          [ `AWS of DescribeForecastExportJobResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val describe_predictor :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribePredictorRequest.t ->
        (DescribePredictorResponse.t,
          [ `AWS of DescribePredictorResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val describe_predictor_backtest_export_job :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribePredictorBacktestExportJobRequest.t ->
        (DescribePredictorBacktestExportJobResponse.t,
          [ `AWS of DescribePredictorBacktestExportJobResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val get_accuracy_metrics :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      GetAccuracyMetricsRequest.t ->
        (GetAccuracyMetricsResponse.t,
          [ `AWS of GetAccuracyMetricsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val list_dataset_groups :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListDatasetGroupsRequest.t ->
        (ListDatasetGroupsResponse.t,
          [ `AWS of ListDatasetGroupsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val list_dataset_import_jobs :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListDatasetImportJobsRequest.t ->
        (ListDatasetImportJobsResponse.t,
          [ `AWS of ListDatasetImportJobsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val list_datasets :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListDatasetsRequest.t ->
        (ListDatasetsResponse.t,
          [ `AWS of ListDatasetsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val list_explainabilities :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListExplainabilitiesRequest.t ->
        (ListExplainabilitiesResponse.t,
          [ `AWS of ListExplainabilitiesResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val list_explainability_exports :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListExplainabilityExportsRequest.t ->
        (ListExplainabilityExportsResponse.t,
          [ `AWS of ListExplainabilityExportsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val list_forecast_export_jobs :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListForecastExportJobsRequest.t ->
        (ListForecastExportJobsResponse.t,
          [ `AWS of ListForecastExportJobsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val list_forecasts :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListForecastsRequest.t ->
        (ListForecastsResponse.t,
          [ `AWS of ListForecastsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val list_predictor_backtest_export_jobs :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListPredictorBacktestExportJobsRequest.t ->
        (ListPredictorBacktestExportJobsResponse.t,
          [ `AWS of ListPredictorBacktestExportJobsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val list_predictors :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListPredictorsRequest.t ->
        (ListPredictorsResponse.t,
          [ `AWS of ListPredictorsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val list_tags_for_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListTagsForResourceRequest.t ->
        (ListTagsForResourceResponse.t,
          [ `AWS of ListTagsForResourceResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val stop_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      StopResourceRequest.t ->
        (unit, [ `AWS of unit  | `Transport of Awso.Http.Io.Error.call ])
          Result.t Async.Deferred.t
val tag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      TagResourceRequest.t ->
        (TagResourceResponse.t,
          [ `AWS of TagResourceResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val untag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UntagResourceRequest.t ->
        (UntagResourceResponse.t,
          [ `AWS of UntagResourceResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t
val update_dataset_group :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UpdateDatasetGroupRequest.t ->
        (UpdateDatasetGroupResponse.t,
          [ `AWS of UpdateDatasetGroupResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t
          Async.Deferred.t