(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso *)
open! Awso_common.Jane_compat
open Values
type ('i, 'o, 'e) t =
  | AcceptPage: (AcceptPageRequest.t, AcceptPageResult.t,
  AcceptPageResult.error) t 
  | ActivateContactChannel: (ActivateContactChannelRequest.t,
  ActivateContactChannelResult.t, ActivateContactChannelResult.error) t 
  | CreateContact: (CreateContactRequest.t, CreateContactResult.t,
  CreateContactResult.error) t 
  | CreateContactChannel: (CreateContactChannelRequest.t,
  CreateContactChannelResult.t, CreateContactChannelResult.error) t 
  | DeactivateContactChannel: (DeactivateContactChannelRequest.t,
  DeactivateContactChannelResult.t, DeactivateContactChannelResult.error) t 
  | DeleteContact: (DeleteContactRequest.t, DeleteContactResult.t,
  DeleteContactResult.error) t 
  | DeleteContactChannel: (DeleteContactChannelRequest.t,
  DeleteContactChannelResult.t, DeleteContactChannelResult.error) t 
  | DescribeEngagement: (DescribeEngagementRequest.t,
  DescribeEngagementResult.t, DescribeEngagementResult.error) t 
  | DescribePage: (DescribePageRequest.t, DescribePageResult.t,
  DescribePageResult.error) t 
  | GetContact: (GetContactRequest.t, GetContactResult.t,
  GetContactResult.error) t 
  | GetContactChannel: (GetContactChannelRequest.t,
  GetContactChannelResult.t, GetContactChannelResult.error) t 
  | GetContactPolicy: (GetContactPolicyRequest.t, GetContactPolicyResult.t,
  GetContactPolicyResult.error) t 
  | ListContactChannels: (ListContactChannelsRequest.t,
  ListContactChannelsResult.t, ListContactChannelsResult.error) t 
  | ListContacts: (ListContactsRequest.t, ListContactsResult.t,
  ListContactsResult.error) t 
  | ListEngagements: (ListEngagementsRequest.t, ListEngagementsResult.t,
  ListEngagementsResult.error) t 
  | ListPageReceipts: (ListPageReceiptsRequest.t, ListPageReceiptsResult.t,
  ListPageReceiptsResult.error) t 
  | ListPagesByContact: (ListPagesByContactRequest.t,
  ListPagesByContactResult.t, ListPagesByContactResult.error) t 
  | ListPagesByEngagement: (ListPagesByEngagementRequest.t,
  ListPagesByEngagementResult.t, ListPagesByEngagementResult.error) t 
  | ListTagsForResource: (ListTagsForResourceRequest.t,
  ListTagsForResourceResult.t, ListTagsForResourceResult.error) t 
  | PutContactPolicy: (PutContactPolicyRequest.t, PutContactPolicyResult.t,
  PutContactPolicyResult.error) t 
  | SendActivationCode: (SendActivationCodeRequest.t,
  SendActivationCodeResult.t, SendActivationCodeResult.error) t 
  | StartEngagement: (StartEngagementRequest.t, StartEngagementResult.t,
  StartEngagementResult.error) t 
  | StopEngagement: (StopEngagementRequest.t, StopEngagementResult.t,
  StopEngagementResult.error) t 
  | TagResource: (TagResourceRequest.t, TagResourceResult.t,
  TagResourceResult.error) t 
  | UntagResource: (UntagResourceRequest.t, UntagResourceResult.t,
  UntagResourceResult.error) t 
  | UpdateContact: (UpdateContactRequest.t, UpdateContactResult.t,
  UpdateContactResult.error) t 
  | UpdateContactChannel: (UpdateContactChannelRequest.t,
  UpdateContactChannelResult.t, UpdateContactChannelResult.error) t 
let method_of_endpoint : type i o e. (i, o, e) t -> _ =
  function
  | AcceptPage -> `POST
  | ActivateContactChannel -> `POST
  | CreateContact -> `POST
  | CreateContactChannel -> `POST
  | DeactivateContactChannel -> `POST
  | DeleteContact -> `POST
  | DeleteContactChannel -> `POST
  | DescribeEngagement -> `POST
  | DescribePage -> `POST
  | GetContact -> `POST
  | GetContactChannel -> `POST
  | GetContactPolicy -> `POST
  | ListContactChannels -> `POST
  | ListContacts -> `POST
  | ListEngagements -> `POST
  | ListPageReceipts -> `POST
  | ListPagesByContact -> `POST
  | ListPagesByEngagement -> `POST
  | ListTagsForResource -> `POST
  | PutContactPolicy -> `POST
  | SendActivationCode -> `POST
  | StartEngagement -> `POST
  | StopEngagement -> `POST
  | TagResource -> `POST
  | UntagResource -> `POST
  | UpdateContact -> `POST
  | UpdateContactChannel -> `POST
let uri_of_endpoint : type i o e. (i, o, e) t -> i -> Uri.t =
  ((fun endpoint x ->
      match endpoint with
      | AcceptPage -> (Format.kasprintf Uri.of_string) "/"
      | ActivateContactChannel -> (Format.kasprintf Uri.of_string) "/"
      | CreateContact -> (Format.kasprintf Uri.of_string) "/"
      | CreateContactChannel -> (Format.kasprintf Uri.of_string) "/"
      | DeactivateContactChannel -> (Format.kasprintf Uri.of_string) "/"
      | DeleteContact -> (Format.kasprintf Uri.of_string) "/"
      | DeleteContactChannel -> (Format.kasprintf Uri.of_string) "/"
      | DescribeEngagement -> (Format.kasprintf Uri.of_string) "/"
      | DescribePage -> (Format.kasprintf Uri.of_string) "/"
      | GetContact -> (Format.kasprintf Uri.of_string) "/"
      | GetContactChannel -> (Format.kasprintf Uri.of_string) "/"
      | GetContactPolicy -> (Format.kasprintf Uri.of_string) "/"
      | ListContactChannels -> (Format.kasprintf Uri.of_string) "/"
      | ListContacts -> (Format.kasprintf Uri.of_string) "/"
      | ListEngagements -> (Format.kasprintf Uri.of_string) "/"
      | ListPageReceipts -> (Format.kasprintf Uri.of_string) "/"
      | ListPagesByContact -> (Format.kasprintf Uri.of_string) "/"
      | ListPagesByEngagement -> (Format.kasprintf Uri.of_string) "/"
      | ListTagsForResource -> (Format.kasprintf Uri.of_string) "/"
      | PutContactPolicy -> (Format.kasprintf Uri.of_string) "/"
      | SendActivationCode -> (Format.kasprintf Uri.of_string) "/"
      | StartEngagement -> (Format.kasprintf Uri.of_string) "/"
      | StopEngagement -> (Format.kasprintf Uri.of_string) "/"
      | TagResource -> (Format.kasprintf Uri.of_string) "/"
      | UntagResource -> (Format.kasprintf Uri.of_string) "/"
      | UpdateContact -> (Format.kasprintf Uri.of_string) "/"
      | UpdateContactChannel -> (Format.kasprintf Uri.of_string) "/")
  [@ocaml.warning "-27"])
let to_request (type i) (type o) (type e) (endp : (i, o, e) t) (req : i) =
  match endp with
  | AcceptPage ->
      let json = AcceptPageRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.AcceptPage")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ActivateContactChannel ->
      let json = ActivateContactChannelRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.ActivateContactChannel")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreateContact ->
      let json = CreateContactRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.CreateContact")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreateContactChannel ->
      let json = CreateContactChannelRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.CreateContactChannel")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeactivateContactChannel ->
      let json = DeactivateContactChannelRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.DeactivateContactChannel")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteContact ->
      let json = DeleteContactRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.DeleteContact")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteContactChannel ->
      let json = DeleteContactChannelRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.DeleteContactChannel")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DescribeEngagement ->
      let json = DescribeEngagementRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.DescribeEngagement")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DescribePage ->
      let json = DescribePageRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.DescribePage")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetContact ->
      let json = GetContactRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.GetContact")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetContactChannel ->
      let json = GetContactChannelRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.GetContactChannel")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetContactPolicy ->
      let json = GetContactPolicyRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.GetContactPolicy")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListContactChannels ->
      let json = ListContactChannelsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.ListContactChannels")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListContacts ->
      let json = ListContactsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.ListContacts")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListEngagements ->
      let json = ListEngagementsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.ListEngagements")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListPageReceipts ->
      let json = ListPageReceiptsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.ListPageReceipts")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListPagesByContact ->
      let json = ListPagesByContactRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.ListPagesByContact")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListPagesByEngagement ->
      let json = ListPagesByEngagementRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.ListPagesByEngagement")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListTagsForResource ->
      let json = ListTagsForResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.ListTagsForResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | PutContactPolicy ->
      let json = PutContactPolicyRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.PutContactPolicy")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | SendActivationCode ->
      let json = SendActivationCodeRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.SendActivationCode")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | StartEngagement ->
      let json = StartEngagementRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.StartEngagement")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | StopEngagement ->
      let json = StopEngagementRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.StopEngagement")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | TagResource ->
      let json = TagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.TagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UntagResource ->
      let json = UntagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.UntagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateContact ->
      let json = UpdateContactRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.UpdateContact")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateContactChannel ->
      let json = UpdateContactChannelRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "SSMContacts.UpdateContactChannel")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
let of_response (type i) (type o) (type e) (endpoint : (i, o, e) t)
  (resp : (Awso.Http.Response.t, Awso.Http.Io.Error.call) result) :
  (o, [ `AWS of e  | `Transport of Awso.Http.Io.Error.call ]) result=
  let handle_error err error_of_json =
    let generic_error () = Error (`Transport err) in
    match err with
    | `Too_many_redirects -> generic_error ()
    | `Bad_response
        { Awso.Http.Io.Error.code = code; body; x_amzn_error_type = _ } ->
        (match (error_of_json, ((code >= 400) && (code <= 599))) with
         | (Some error_of_json, true) ->
             let json = Yojson.Safe.from_string body in
             (match json |> (Yojson.Safe.Util.member "__type") with
              | `String error_type ->
                  Error (`AWS (error_of_json error_type json))
              | `Null -> generic_error ()
              | _ ->
                  failwith
                    (sprintf "Error '__type' did not have string type: %s"
                       body))
         | (None, _) | (_, false) -> generic_error ()) in
  match endpoint with
  | AcceptPage ->
      (match resp with
       | Error err -> handle_error err (Some AcceptPageResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (AcceptPageResult.of_json json))
  | ActivateContactChannel ->
      (match resp with
       | Error err ->
           handle_error err (Some ActivateContactChannelResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ActivateContactChannelResult.of_json json))
  | CreateContact ->
      (match resp with
       | Error err ->
           handle_error err (Some CreateContactResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (CreateContactResult.of_json json))
  | CreateContactChannel ->
      (match resp with
       | Error err ->
           handle_error err (Some CreateContactChannelResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (CreateContactChannelResult.of_json json))
  | DeactivateContactChannel ->
      (match resp with
       | Error err ->
           handle_error err
             (Some DeactivateContactChannelResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (DeactivateContactChannelResult.of_json json))
  | DeleteContact ->
      (match resp with
       | Error err ->
           handle_error err (Some DeleteContactResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (DeleteContactResult.of_json json))
  | DeleteContactChannel ->
      (match resp with
       | Error err ->
           handle_error err (Some DeleteContactChannelResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (DeleteContactChannelResult.of_json json))
  | DescribeEngagement ->
      (match resp with
       | Error err ->
           handle_error err (Some DescribeEngagementResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (DescribeEngagementResult.of_json json))
  | DescribePage ->
      (match resp with
       | Error err ->
           handle_error err (Some DescribePageResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (DescribePageResult.of_json json))
  | GetContact ->
      (match resp with
       | Error err -> handle_error err (Some GetContactResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (GetContactResult.of_json json))
  | GetContactChannel ->
      (match resp with
       | Error err ->
           handle_error err (Some GetContactChannelResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (GetContactChannelResult.of_json json))
  | GetContactPolicy ->
      (match resp with
       | Error err ->
           handle_error err (Some GetContactPolicyResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (GetContactPolicyResult.of_json json))
  | ListContactChannels ->
      (match resp with
       | Error err ->
           handle_error err (Some ListContactChannelsResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListContactChannelsResult.of_json json))
  | ListContacts ->
      (match resp with
       | Error err ->
           handle_error err (Some ListContactsResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListContactsResult.of_json json))
  | ListEngagements ->
      (match resp with
       | Error err ->
           handle_error err (Some ListEngagementsResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListEngagementsResult.of_json json))
  | ListPageReceipts ->
      (match resp with
       | Error err ->
           handle_error err (Some ListPageReceiptsResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListPageReceiptsResult.of_json json))
  | ListPagesByContact ->
      (match resp with
       | Error err ->
           handle_error err (Some ListPagesByContactResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListPagesByContactResult.of_json json))
  | ListPagesByEngagement ->
      (match resp with
       | Error err ->
           handle_error err (Some ListPagesByEngagementResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListPagesByEngagementResult.of_json json))
  | ListTagsForResource ->
      (match resp with
       | Error err ->
           handle_error err (Some ListTagsForResourceResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListTagsForResourceResult.of_json json))
  | PutContactPolicy ->
      (match resp with
       | Error err ->
           handle_error err (Some PutContactPolicyResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (PutContactPolicyResult.of_json json))
  | SendActivationCode ->
      (match resp with
       | Error err ->
           handle_error err (Some SendActivationCodeResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (SendActivationCodeResult.of_json json))
  | StartEngagement ->
      (match resp with
       | Error err ->
           handle_error err (Some StartEngagementResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (StartEngagementResult.of_json json))
  | StopEngagement ->
      (match resp with
       | Error err ->
           handle_error err (Some StopEngagementResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (StopEngagementResult.of_json json))
  | TagResource ->
      (match resp with
       | Error err -> handle_error err (Some TagResourceResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (TagResourceResult.of_json json))
  | UntagResource ->
      (match resp with
       | Error err ->
           handle_error err (Some UntagResourceResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (UntagResourceResult.of_json json))
  | UpdateContact ->
      (match resp with
       | Error err ->
           handle_error err (Some UpdateContactResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (UpdateContactResult.of_json json))
  | UpdateContactChannel ->
      (match resp with
       | Error err ->
           handle_error err (Some UpdateContactChannelResult.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (UpdateContactChannelResult.of_json json))