(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open! Awso_common.Jane_compat
open Values
type ('i, 'o, 'e) t =
  | AssociateSourceViews: (AssociateSourceViewsRequest.t,
  AssociateSourceViewsResponse.t, AssociateSourceViewsResponse.error) t 
  | CreateBillingView: (CreateBillingViewRequest.t,
  CreateBillingViewResponse.t, CreateBillingViewResponse.error) t 
  | DeleteBillingView: (DeleteBillingViewRequest.t,
  DeleteBillingViewResponse.t, DeleteBillingViewResponse.error) t 
  | DisassociateSourceViews: (DisassociateSourceViewsRequest.t,
  DisassociateSourceViewsResponse.t, DisassociateSourceViewsResponse.error) t
  
  | GetBillingView: (GetBillingViewRequest.t, GetBillingViewResponse.t,
  GetBillingViewResponse.error) t 
  | GetResourcePolicy: (GetResourcePolicyRequest.t,
  GetResourcePolicyResponse.t, GetResourcePolicyResponse.error) t 
  | ListBillingViews: (ListBillingViewsRequest.t, ListBillingViewsResponse.t,
  ListBillingViewsResponse.error) t 
  | ListSourceViewsForBillingView: (ListSourceViewsForBillingViewRequest.t,
  ListSourceViewsForBillingViewResponse.t,
  ListSourceViewsForBillingViewResponse.error) t 
  | ListTagsForResource: (ListTagsForResourceRequest.t,
  ListTagsForResourceResponse.t, ListTagsForResourceResponse.error) t 
  | TagResource: (TagResourceRequest.t, TagResourceResponse.t,
  TagResourceResponse.error) t 
  | UntagResource: (UntagResourceRequest.t, UntagResourceResponse.t,
  UntagResourceResponse.error) t 
  | UpdateBillingView: (UpdateBillingViewRequest.t,
  UpdateBillingViewResponse.t, UpdateBillingViewResponse.error) t 
let method_of_endpoint : type i o e. (i, o, e) t -> _ =
  function
  | AssociateSourceViews -> `POST
  | CreateBillingView -> `POST
  | DeleteBillingView -> `POST
  | DisassociateSourceViews -> `POST
  | GetBillingView -> `POST
  | GetResourcePolicy -> `POST
  | ListBillingViews -> `POST
  | ListSourceViewsForBillingView -> `POST
  | ListTagsForResource -> `POST
  | TagResource -> `POST
  | UntagResource -> `POST
  | UpdateBillingView -> `POST
let uri_of_endpoint : type i o e. (i, o, e) t -> i -> Uri.t =
  ((fun endpoint x ->
      match endpoint with
      | AssociateSourceViews -> (Format.kasprintf Uri.of_string) "/"
      | CreateBillingView -> (Format.kasprintf Uri.of_string) "/"
      | DeleteBillingView -> (Format.kasprintf Uri.of_string) "/"
      | DisassociateSourceViews -> (Format.kasprintf Uri.of_string) "/"
      | GetBillingView -> (Format.kasprintf Uri.of_string) "/"
      | GetResourcePolicy -> (Format.kasprintf Uri.of_string) "/"
      | ListBillingViews -> (Format.kasprintf Uri.of_string) "/"
      | ListSourceViewsForBillingView -> (Format.kasprintf Uri.of_string) "/"
      | ListTagsForResource -> (Format.kasprintf Uri.of_string) "/"
      | TagResource -> (Format.kasprintf Uri.of_string) "/"
      | UntagResource -> (Format.kasprintf Uri.of_string) "/"
      | UpdateBillingView -> (Format.kasprintf Uri.of_string) "/")
  [@ocaml.warning "-27"])
let to_request (type i) (type o) (type e) (endp : (i, o, e) t) (req : i) =
  match endp with
  | AssociateSourceViews ->
      let json = AssociateSourceViewsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.AssociateSourceViews")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreateBillingView ->
      let json = CreateBillingViewRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.CreateBillingView")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteBillingView ->
      let json = DeleteBillingViewRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.DeleteBillingView")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DisassociateSourceViews ->
      let json = DisassociateSourceViewsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.DisassociateSourceViews")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetBillingView ->
      let json = GetBillingViewRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.GetBillingView")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetResourcePolicy ->
      let json = GetResourcePolicyRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.GetResourcePolicy")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListBillingViews ->
      let json = ListBillingViewsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.ListBillingViews")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListSourceViewsForBillingView ->
      let json = ListSourceViewsForBillingViewRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.ListSourceViewsForBillingView")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListTagsForResource ->
      let json = ListTagsForResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.ListTagsForResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | TagResource ->
      let json = TagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.TagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UntagResource ->
      let json = UntagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.UntagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateBillingView ->
      let json = UpdateBillingViewRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "AWSBilling.UpdateBillingView")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
let of_response (type i) (type o) (type e) (endpoint : (i, o, e) t)
  (resp : Awso.Http.Response.t) : (o, e) result=
  let code = Awso.Http.Status.to_code (Awso.Http.Response.status resp) in
  let is_success = (code >= 200) && (code < 300) in
  let parse_aws_error error_of_json =
    let body = Awso.Http.Response.body resp in
    let bail () =
      raise
        (Awso.Http.Io.Error.Bad_response
           { Awso.Http.Io.Error.code = code; body; x_amzn_error_type = None }) in
    match (error_of_json, ((code >= 400) && (code <= 599))) with
    | (Some error_of_json, true) ->
        let json = Yojson.Safe.from_string body in
        (match json |> (Yojson.Safe.Util.member "__type") with
         | `String error_type -> error_of_json error_type json
         | `Null -> bail ()
         | _ ->
             failwith
               (sprintf "Error '__type' did not have string type: %s" body))
    | (None, _) | (_, false) -> bail () in
  let _ = parse_aws_error in
  let _ = resp in
  match endpoint with
  | AssociateSourceViews ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (AssociateSourceViewsResponse.of_json json)
      else
        Error
          (parse_aws_error (Some AssociateSourceViewsResponse.error_of_json))
  | CreateBillingView ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CreateBillingViewResponse.of_json json)
      else
        Error
          (parse_aws_error (Some CreateBillingViewResponse.error_of_json))
  | DeleteBillingView ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (DeleteBillingViewResponse.of_json json)
      else
        Error
          (parse_aws_error (Some DeleteBillingViewResponse.error_of_json))
  | DisassociateSourceViews ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (DisassociateSourceViewsResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some DisassociateSourceViewsResponse.error_of_json))
  | GetBillingView ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetBillingViewResponse.of_json json)
      else
        Error (parse_aws_error (Some GetBillingViewResponse.error_of_json))
  | GetResourcePolicy ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetResourcePolicyResponse.of_json json)
      else
        Error
          (parse_aws_error (Some GetResourcePolicyResponse.error_of_json))
  | ListBillingViews ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListBillingViewsResponse.of_json json)
      else
        Error (parse_aws_error (Some ListBillingViewsResponse.error_of_json))
  | ListSourceViewsForBillingView ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListSourceViewsForBillingViewResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some ListSourceViewsForBillingViewResponse.error_of_json))
  | ListTagsForResource ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListTagsForResourceResponse.of_json json)
      else
        Error
          (parse_aws_error (Some ListTagsForResourceResponse.error_of_json))
  | TagResource ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (TagResourceResponse.of_json json)
      else Error (parse_aws_error (Some TagResourceResponse.error_of_json))
  | UntagResource ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (UntagResourceResponse.of_json json)
      else Error (parse_aws_error (Some UntagResourceResponse.error_of_json))
  | UpdateBillingView ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (UpdateBillingViewResponse.of_json json)
      else
        Error
          (parse_aws_error (Some UpdateBillingViewResponse.error_of_json))