(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open! Awso_common.Jane_compat
open Values
type ('i, 'o, 'e) t =
  | CreateAccess: (CreateAccessRequest.t, CreateAccessResponse.t,
  CreateAccessResponse.error) t 
  | CreateServer: (CreateServerRequest.t, CreateServerResponse.t,
  CreateServerResponse.error) t 
  | CreateUser: (CreateUserRequest.t, CreateUserResponse.t,
  CreateUserResponse.error) t 
  | CreateWorkflow: (CreateWorkflowRequest.t, CreateWorkflowResponse.t,
  CreateWorkflowResponse.error) t 
  | DeleteAccess: (DeleteAccessRequest.t, unit, unit) t 
  | DeleteServer: (DeleteServerRequest.t, unit, unit) t 
  | DeleteSshPublicKey: (DeleteSshPublicKeyRequest.t, unit, unit) t 
  | DeleteUser: (DeleteUserRequest.t, unit, unit) t 
  | DeleteWorkflow: (DeleteWorkflowRequest.t, unit, unit) t 
  | DescribeAccess: (DescribeAccessRequest.t, DescribeAccessResponse.t,
  DescribeAccessResponse.error) t 
  | DescribeExecution: (DescribeExecutionRequest.t,
  DescribeExecutionResponse.t, DescribeExecutionResponse.error) t 
  | DescribeSecurityPolicy: (DescribeSecurityPolicyRequest.t,
  DescribeSecurityPolicyResponse.t, DescribeSecurityPolicyResponse.error) t 
  | DescribeServer: (DescribeServerRequest.t, DescribeServerResponse.t,
  DescribeServerResponse.error) t 
  | DescribeUser: (DescribeUserRequest.t, DescribeUserResponse.t,
  DescribeUserResponse.error) t 
  | DescribeWorkflow: (DescribeWorkflowRequest.t, DescribeWorkflowResponse.t,
  DescribeWorkflowResponse.error) t 
  | ImportSshPublicKey: (ImportSshPublicKeyRequest.t,
  ImportSshPublicKeyResponse.t, ImportSshPublicKeyResponse.error) t 
  | ListAccesses: (ListAccessesRequest.t, ListAccessesResponse.t,
  ListAccessesResponse.error) t 
  | ListExecutions: (ListExecutionsRequest.t, ListExecutionsResponse.t,
  ListExecutionsResponse.error) t 
  | ListSecurityPolicies: (ListSecurityPoliciesRequest.t,
  ListSecurityPoliciesResponse.t, ListSecurityPoliciesResponse.error) t 
  | ListServers: (ListServersRequest.t, ListServersResponse.t,
  ListServersResponse.error) t 
  | ListTagsForResource: (ListTagsForResourceRequest.t,
  ListTagsForResourceResponse.t, ListTagsForResourceResponse.error) t 
  | ListUsers: (ListUsersRequest.t, ListUsersResponse.t,
  ListUsersResponse.error) t 
  | ListWorkflows: (ListWorkflowsRequest.t, ListWorkflowsResponse.t,
  ListWorkflowsResponse.error) t 
  | SendWorkflowStepState: (SendWorkflowStepStateRequest.t,
  SendWorkflowStepStateResponse.t, SendWorkflowStepStateResponse.error) t 
  | StartServer: (StartServerRequest.t, unit, unit) t 
  | StopServer: (StopServerRequest.t, unit, unit) t 
  | TagResource: (TagResourceRequest.t, unit, unit) t 
  | TestIdentityProvider: (TestIdentityProviderRequest.t,
  TestIdentityProviderResponse.t, TestIdentityProviderResponse.error) t 
  | UntagResource: (UntagResourceRequest.t, unit, unit) t 
  | UpdateAccess: (UpdateAccessRequest.t, UpdateAccessResponse.t,
  UpdateAccessResponse.error) t 
  | UpdateServer: (UpdateServerRequest.t, UpdateServerResponse.t,
  UpdateServerResponse.error) t 
  | UpdateUser: (UpdateUserRequest.t, UpdateUserResponse.t,
  UpdateUserResponse.error) t 
let method_of_endpoint : type i o e. (i, o, e) t -> _ =
  function
  | CreateAccess -> `POST
  | CreateServer -> `POST
  | CreateUser -> `POST
  | CreateWorkflow -> `POST
  | DeleteAccess -> `POST
  | DeleteServer -> `POST
  | DeleteSshPublicKey -> `POST
  | DeleteUser -> `POST
  | DeleteWorkflow -> `POST
  | DescribeAccess -> `POST
  | DescribeExecution -> `POST
  | DescribeSecurityPolicy -> `POST
  | DescribeServer -> `POST
  | DescribeUser -> `POST
  | DescribeWorkflow -> `POST
  | ImportSshPublicKey -> `POST
  | ListAccesses -> `POST
  | ListExecutions -> `POST
  | ListSecurityPolicies -> `POST
  | ListServers -> `POST
  | ListTagsForResource -> `POST
  | ListUsers -> `POST
  | ListWorkflows -> `POST
  | SendWorkflowStepState -> `POST
  | StartServer -> `POST
  | StopServer -> `POST
  | TagResource -> `POST
  | TestIdentityProvider -> `POST
  | UntagResource -> `POST
  | UpdateAccess -> `POST
  | UpdateServer -> `POST
  | UpdateUser -> `POST
let uri_of_endpoint : type i o e. (i, o, e) t -> i -> Uri.t =
  ((fun endpoint x ->
      match endpoint with
      | CreateAccess -> (Format.kasprintf Uri.of_string) "/"
      | CreateServer -> (Format.kasprintf Uri.of_string) "/"
      | CreateUser -> (Format.kasprintf Uri.of_string) "/"
      | CreateWorkflow -> (Format.kasprintf Uri.of_string) "/"
      | DeleteAccess -> (Format.kasprintf Uri.of_string) "/"
      | DeleteServer -> (Format.kasprintf Uri.of_string) "/"
      | DeleteSshPublicKey -> (Format.kasprintf Uri.of_string) "/"
      | DeleteUser -> (Format.kasprintf Uri.of_string) "/"
      | DeleteWorkflow -> (Format.kasprintf Uri.of_string) "/"
      | DescribeAccess -> (Format.kasprintf Uri.of_string) "/"
      | DescribeExecution -> (Format.kasprintf Uri.of_string) "/"
      | DescribeSecurityPolicy -> (Format.kasprintf Uri.of_string) "/"
      | DescribeServer -> (Format.kasprintf Uri.of_string) "/"
      | DescribeUser -> (Format.kasprintf Uri.of_string) "/"
      | DescribeWorkflow -> (Format.kasprintf Uri.of_string) "/"
      | ImportSshPublicKey -> (Format.kasprintf Uri.of_string) "/"
      | ListAccesses -> (Format.kasprintf Uri.of_string) "/"
      | ListExecutions -> (Format.kasprintf Uri.of_string) "/"
      | ListSecurityPolicies -> (Format.kasprintf Uri.of_string) "/"
      | ListServers -> (Format.kasprintf Uri.of_string) "/"
      | ListTagsForResource -> (Format.kasprintf Uri.of_string) "/"
      | ListUsers -> (Format.kasprintf Uri.of_string) "/"
      | ListWorkflows -> (Format.kasprintf Uri.of_string) "/"
      | SendWorkflowStepState -> (Format.kasprintf Uri.of_string) "/"
      | StartServer -> (Format.kasprintf Uri.of_string) "/"
      | StopServer -> (Format.kasprintf Uri.of_string) "/"
      | TagResource -> (Format.kasprintf Uri.of_string) "/"
      | TestIdentityProvider -> (Format.kasprintf Uri.of_string) "/"
      | UntagResource -> (Format.kasprintf Uri.of_string) "/"
      | UpdateAccess -> (Format.kasprintf Uri.of_string) "/"
      | UpdateServer -> (Format.kasprintf Uri.of_string) "/"
      | UpdateUser -> (Format.kasprintf Uri.of_string) "/")
  [@ocaml.warning "-27"])
let to_request (type i) (type o) (type e) (endp : (i, o, e) t) (req : i) =
  match endp with
  | CreateAccess ->
      let json = CreateAccessRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.CreateAccess")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreateServer ->
      let json = CreateServerRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.CreateServer")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreateUser ->
      let json = CreateUserRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.CreateUser")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreateWorkflow ->
      let json = CreateWorkflowRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.CreateWorkflow")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteAccess ->
      let json = DeleteAccessRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DeleteAccess")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteServer ->
      let json = DeleteServerRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DeleteServer")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteSshPublicKey ->
      let json = DeleteSshPublicKeyRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DeleteSshPublicKey")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteUser ->
      let json = DeleteUserRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DeleteUser")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteWorkflow ->
      let json = DeleteWorkflowRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DeleteWorkflow")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DescribeAccess ->
      let json = DescribeAccessRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DescribeAccess")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DescribeExecution ->
      let json = DescribeExecutionRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DescribeExecution")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DescribeSecurityPolicy ->
      let json = DescribeSecurityPolicyRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DescribeSecurityPolicy")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DescribeServer ->
      let json = DescribeServerRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DescribeServer")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DescribeUser ->
      let json = DescribeUserRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DescribeUser")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DescribeWorkflow ->
      let json = DescribeWorkflowRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.DescribeWorkflow")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ImportSshPublicKey ->
      let json = ImportSshPublicKeyRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.ImportSshPublicKey")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListAccesses ->
      let json = ListAccessesRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.ListAccesses")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListExecutions ->
      let json = ListExecutionsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.ListExecutions")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListSecurityPolicies ->
      let json = ListSecurityPoliciesRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.ListSecurityPolicies")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListServers ->
      let json = ListServersRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.ListServers")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListTagsForResource ->
      let json = ListTagsForResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.ListTagsForResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListUsers ->
      let json = ListUsersRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.ListUsers")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListWorkflows ->
      let json = ListWorkflowsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.ListWorkflows")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | SendWorkflowStepState ->
      let json = SendWorkflowStepStateRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.SendWorkflowStepState")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | StartServer ->
      let json = StartServerRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.StartServer")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | StopServer ->
      let json = StopServerRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.StopServer")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | TagResource ->
      let json = TagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.TagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | TestIdentityProvider ->
      let json = TestIdentityProviderRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.TestIdentityProvider")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UntagResource ->
      let json = UntagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.UntagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateAccess ->
      let json = UpdateAccessRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.UpdateAccess")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateServer ->
      let json = UpdateServerRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.UpdateServer")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateUser ->
      let json = UpdateUserRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "TransferService.UpdateUser")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
let of_response (type i) (type o) (type e) (endpoint : (i, o, e) t)
  (resp : Awso.Http.Response.t) : (o, e) result=
  let code = Awso.Http.Status.to_code (Awso.Http.Response.status resp) in
  let is_success = (code >= 200) && (code < 300) in
  let parse_aws_error error_of_json =
    let body = Awso.Http.Response.body resp in
    let bail () =
      raise
        (Awso.Http.Io.Error.Bad_response
           { Awso.Http.Io.Error.code = code; body; x_amzn_error_type = None }) in
    match (error_of_json, ((code >= 400) && (code <= 599))) with
    | (Some error_of_json, true) ->
        let json = Yojson.Safe.from_string body in
        (match json |> (Yojson.Safe.Util.member "__type") with
         | `String error_type -> error_of_json error_type json
         | `Null -> bail ()
         | _ ->
             failwith
               (sprintf "Error '__type' did not have string type: %s" body))
    | (None, _) | (_, false) -> bail () in
  let _ = parse_aws_error in
  let _ = resp in
  match endpoint with
  | CreateAccess ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CreateAccessResponse.of_json json)
      else Error (parse_aws_error (Some CreateAccessResponse.error_of_json))
  | CreateServer ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CreateServerResponse.of_json json)
      else Error (parse_aws_error (Some CreateServerResponse.error_of_json))
  | CreateUser ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CreateUserResponse.of_json json)
      else Error (parse_aws_error (Some CreateUserResponse.error_of_json))
  | CreateWorkflow ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CreateWorkflowResponse.of_json json)
      else
        Error (parse_aws_error (Some CreateWorkflowResponse.error_of_json))
  | DeleteAccess ->
      if is_success then Ok () else Error (parse_aws_error None)
  | DeleteServer ->
      if is_success then Ok () else Error (parse_aws_error None)
  | DeleteSshPublicKey ->
      if is_success then Ok () else Error (parse_aws_error None)
  | DeleteUser -> if is_success then Ok () else Error (parse_aws_error None)
  | DeleteWorkflow ->
      if is_success then Ok () else Error (parse_aws_error None)
  | DescribeAccess ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (DescribeAccessResponse.of_json json)
      else
        Error (parse_aws_error (Some DescribeAccessResponse.error_of_json))
  | DescribeExecution ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (DescribeExecutionResponse.of_json json)
      else
        Error
          (parse_aws_error (Some DescribeExecutionResponse.error_of_json))
  | DescribeSecurityPolicy ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (DescribeSecurityPolicyResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some DescribeSecurityPolicyResponse.error_of_json))
  | DescribeServer ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (DescribeServerResponse.of_json json)
      else
        Error (parse_aws_error (Some DescribeServerResponse.error_of_json))
  | DescribeUser ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (DescribeUserResponse.of_json json)
      else Error (parse_aws_error (Some DescribeUserResponse.error_of_json))
  | DescribeWorkflow ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (DescribeWorkflowResponse.of_json json)
      else
        Error (parse_aws_error (Some DescribeWorkflowResponse.error_of_json))
  | ImportSshPublicKey ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ImportSshPublicKeyResponse.of_json json)
      else
        Error
          (parse_aws_error (Some ImportSshPublicKeyResponse.error_of_json))
  | ListAccesses ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListAccessesResponse.of_json json)
      else Error (parse_aws_error (Some ListAccessesResponse.error_of_json))
  | ListExecutions ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListExecutionsResponse.of_json json)
      else
        Error (parse_aws_error (Some ListExecutionsResponse.error_of_json))
  | ListSecurityPolicies ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListSecurityPoliciesResponse.of_json json)
      else
        Error
          (parse_aws_error (Some ListSecurityPoliciesResponse.error_of_json))
  | ListServers ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListServersResponse.of_json json)
      else Error (parse_aws_error (Some ListServersResponse.error_of_json))
  | ListTagsForResource ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListTagsForResourceResponse.of_json json)
      else
        Error
          (parse_aws_error (Some ListTagsForResourceResponse.error_of_json))
  | ListUsers ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListUsersResponse.of_json json)
      else Error (parse_aws_error (Some ListUsersResponse.error_of_json))
  | ListWorkflows ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListWorkflowsResponse.of_json json)
      else Error (parse_aws_error (Some ListWorkflowsResponse.error_of_json))
  | SendWorkflowStepState ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (SendWorkflowStepStateResponse.of_json json)
      else
        Error
          (parse_aws_error (Some SendWorkflowStepStateResponse.error_of_json))
  | StartServer -> if is_success then Ok () else Error (parse_aws_error None)
  | StopServer -> if is_success then Ok () else Error (parse_aws_error None)
  | TagResource -> if is_success then Ok () else Error (parse_aws_error None)
  | TestIdentityProvider ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (TestIdentityProviderResponse.of_json json)
      else
        Error
          (parse_aws_error (Some TestIdentityProviderResponse.error_of_json))
  | UntagResource ->
      if is_success then Ok () else Error (parse_aws_error None)
  | UpdateAccess ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (UpdateAccessResponse.of_json json)
      else Error (parse_aws_error (Some UpdateAccessResponse.error_of_json))
  | UpdateServer ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (UpdateServerResponse.of_json json)
      else Error (parse_aws_error (Some UpdateServerResponse.error_of_json))
  | UpdateUser ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (UpdateUserResponse.of_json json)
      else Error (parse_aws_error (Some UpdateUserResponse.error_of_json))