(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Core
open Async
let json_arg = Command.Arg_type.create Yojson.Safe.from_string
let call ?endpoint_url ?profile ?region f m result_to_json error_to_json =
  let region =
    match region with
    | Some region -> Some (Awso.Region.of_string region)
    | None -> None in
  (Awso_async.Cfg.get_exn ?profile ?region ()) >>=
    (fun cfg ->
       (f ?endpoint_url ?cfg:(Some cfg) m) >>=
         (fun result ->
            match result with
            | Error err ->
                (match error_to_json with
                 | None ->
                     failwithf
                       "endpoint error, but no error values defined in boto"
                       ()
                 | Some to_json ->
                     let s = (err |> to_json) |> Yojson.Safe.to_string in
                     failwithf "AWS error: %s" s ())
            | Ok result ->
                ((match result_to_json with
                  | None -> print_endline "ok response from endpoint"
                  | Some to_json ->
                      ((result |> to_json) |> Yojson.Safe.to_string) |>
                        print_endline);
                 return ())))
let accept_invitation =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and masterId = flag "master-id" (required string) ~doc:"STRING String"
       and invitationId =
         flag "invitation-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.accept_invitation
           (Values.AcceptInvitationRequest.make ~detectorId ~masterId
              ~invitationId ())
           (Some Values.AcceptInvitationResponse.to_json)
           (Some Values.AcceptInvitationResponse.error_to_json)])
let archive_findings =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and findingIds =
         flag "finding-ids" (required json_arg) ~doc:"JSON FindingIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.archive_findings
           (Values.ArchiveFindingsRequest.make ~detectorId
              ~findingIds:(Values.FindingIds.of_json findingIds) ())
           (Some Values.ArchiveFindingsResponse.to_json)
           (Some Values.ArchiveFindingsResponse.error_to_json)])
let create_detector =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and clientToken =
         flag "client-token" (optional string) ~doc:"STRING ClientToken"
       and findingPublishingFrequency =
         flag "finding-publishing-frequency" (optional json_arg)
           ~doc:"JSON FindingPublishingFrequency"
       and dataSources =
         flag "data-sources" (optional json_arg)
           ~doc:"JSON DataSourceConfigurations"
       and tags = flag "tags" (optional json_arg) ~doc:"JSON TagMap"
       and enable = flag "enable" (required bool) ~doc:"BOOL Boolean" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_detector
           (Values.CreateDetectorRequest.make ?clientToken
              ?findingPublishingFrequency:(Option.map
                                             ~f:Values.FindingPublishingFrequency.of_json
                                             findingPublishingFrequency)
              ?dataSources:(Option.map
                              ~f:Values.DataSourceConfigurations.of_json
                              dataSources)
              ?tags:(Option.map ~f:Values.TagMap.of_json tags) ~enable ())
           (Some Values.CreateDetectorResponse.to_json)
           (Some Values.CreateDetectorResponse.error_to_json)])
let create_filter =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and description =
         flag "description" (optional string) ~doc:"STRING FilterDescription"
       and action =
         flag "action" (optional json_arg) ~doc:"JSON FilterAction"
       and rank = flag "rank" (optional int) ~doc:"INT FilterRank"
       and clientToken =
         flag "client-token" (optional string) ~doc:"STRING ClientToken"
       and tags = flag "tags" (optional json_arg) ~doc:"JSON TagMap"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and name = flag "name" (required string) ~doc:"STRING FilterName"
       and findingCriteria =
         flag "finding-criteria" (required json_arg)
           ~doc:"JSON FindingCriteria" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_filter
           (Values.CreateFilterRequest.make ?description
              ?action:(Option.map ~f:Values.FilterAction.of_json action)
              ?rank ?clientToken
              ?tags:(Option.map ~f:Values.TagMap.of_json tags) ~detectorId
              ~name
              ~findingCriteria:(Values.FindingCriteria.of_json
                                  findingCriteria) ())
           (Some Values.CreateFilterResponse.to_json)
           (Some Values.CreateFilterResponse.error_to_json)])
let create_i_p_set =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and clientToken =
         flag "client-token" (optional string) ~doc:"STRING ClientToken"
       and tags = flag "tags" (optional json_arg) ~doc:"JSON TagMap"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and name = flag "name" (required string) ~doc:"STRING Name"
       and format = flag "format" (required json_arg) ~doc:"JSON IpSetFormat"
       and location =
         flag "location" (required string) ~doc:"STRING Location"
       and activate = flag "activate" (required bool) ~doc:"BOOL Boolean" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_i_p_set
           (Values.CreateIPSetRequest.make ?clientToken
              ?tags:(Option.map ~f:Values.TagMap.of_json tags) ~detectorId
              ~name ~format:(Values.IpSetFormat.of_json format) ~location
              ~activate ()) (Some Values.CreateIPSetResponse.to_json)
           (Some Values.CreateIPSetResponse.error_to_json)])
let create_members =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and accountDetails =
         flag "account-details" (required json_arg)
           ~doc:"JSON AccountDetails" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_members
           (Values.CreateMembersRequest.make ~detectorId
              ~accountDetails:(Values.AccountDetails.of_json accountDetails)
              ()) (Some Values.CreateMembersResponse.to_json)
           (Some Values.CreateMembersResponse.error_to_json)])
let create_publishing_destination =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and clientToken =
         flag "client-token" (optional string) ~doc:"STRING ClientToken"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and destinationType =
         flag "destination-type" (required json_arg)
           ~doc:"JSON DestinationType"
       and destinationProperties =
         flag "destination-properties" (required json_arg)
           ~doc:"JSON DestinationProperties" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_publishing_destination
           (Values.CreatePublishingDestinationRequest.make ?clientToken
              ~detectorId
              ~destinationType:(Values.DestinationType.of_json
                                  destinationType)
              ~destinationProperties:(Values.DestinationProperties.of_json
                                        destinationProperties) ())
           (Some Values.CreatePublishingDestinationResponse.to_json)
           (Some Values.CreatePublishingDestinationResponse.error_to_json)])
let create_sample_findings =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and findingTypes =
         flag "finding-types" (optional json_arg) ~doc:"JSON FindingTypes"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_sample_findings
           (Values.CreateSampleFindingsRequest.make
              ?findingTypes:(Option.map ~f:Values.FindingTypes.of_json
                               findingTypes) ~detectorId ())
           (Some Values.CreateSampleFindingsResponse.to_json)
           (Some Values.CreateSampleFindingsResponse.error_to_json)])
let create_threat_intel_set =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and clientToken =
         flag "client-token" (optional string) ~doc:"STRING ClientToken"
       and tags = flag "tags" (optional json_arg) ~doc:"JSON TagMap"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and name = flag "name" (required string) ~doc:"STRING Name"
       and format =
         flag "format" (required json_arg) ~doc:"JSON ThreatIntelSetFormat"
       and location =
         flag "location" (required string) ~doc:"STRING Location"
       and activate = flag "activate" (required bool) ~doc:"BOOL Boolean" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_threat_intel_set
           (Values.CreateThreatIntelSetRequest.make ?clientToken
              ?tags:(Option.map ~f:Values.TagMap.of_json tags) ~detectorId
              ~name ~format:(Values.ThreatIntelSetFormat.of_json format)
              ~location ~activate ())
           (Some Values.CreateThreatIntelSetResponse.to_json)
           (Some Values.CreateThreatIntelSetResponse.error_to_json)])
let decline_invitations =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and accountIds =
         flag "account-ids" (required json_arg) ~doc:"JSON AccountIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.decline_invitations
           (Values.DeclineInvitationsRequest.make
              ~accountIds:(Values.AccountIds.of_json accountIds) ())
           (Some Values.DeclineInvitationsResponse.to_json)
           (Some Values.DeclineInvitationsResponse.error_to_json)])
let delete_detector =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_detector
           (Values.DeleteDetectorRequest.make ~detectorId ())
           (Some Values.DeleteDetectorResponse.to_json)
           (Some Values.DeleteDetectorResponse.error_to_json)])
let delete_filter =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and filterName =
         flag "filter-name" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_filter
           (Values.DeleteFilterRequest.make ~detectorId ~filterName ())
           (Some Values.DeleteFilterResponse.to_json)
           (Some Values.DeleteFilterResponse.error_to_json)])
let delete_i_p_set =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and ipSetId = flag "ip-set-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_i_p_set
           (Values.DeleteIPSetRequest.make ~detectorId ~ipSetId ())
           (Some Values.DeleteIPSetResponse.to_json)
           (Some Values.DeleteIPSetResponse.error_to_json)])
let delete_invitations =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and accountIds =
         flag "account-ids" (required json_arg) ~doc:"JSON AccountIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_invitations
           (Values.DeleteInvitationsRequest.make
              ~accountIds:(Values.AccountIds.of_json accountIds) ())
           (Some Values.DeleteInvitationsResponse.to_json)
           (Some Values.DeleteInvitationsResponse.error_to_json)])
let delete_members =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and accountIds =
         flag "account-ids" (required json_arg) ~doc:"JSON AccountIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_members
           (Values.DeleteMembersRequest.make ~detectorId
              ~accountIds:(Values.AccountIds.of_json accountIds) ())
           (Some Values.DeleteMembersResponse.to_json)
           (Some Values.DeleteMembersResponse.error_to_json)])
let delete_publishing_destination =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and destinationId =
         flag "destination-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_publishing_destination
           (Values.DeletePublishingDestinationRequest.make ~detectorId
              ~destinationId ())
           (Some Values.DeletePublishingDestinationResponse.to_json)
           (Some Values.DeletePublishingDestinationResponse.error_to_json)])
let delete_threat_intel_set =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and threatIntelSetId =
         flag "threat-intel-set-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_threat_intel_set
           (Values.DeleteThreatIntelSetRequest.make ~detectorId
              ~threatIntelSetId ())
           (Some Values.DeleteThreatIntelSetResponse.to_json)
           (Some Values.DeleteThreatIntelSetResponse.error_to_json)])
let describe_organization_configuration =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.describe_organization_configuration
           (Values.DescribeOrganizationConfigurationRequest.make ~detectorId
              ())
           (Some Values.DescribeOrganizationConfigurationResponse.to_json)
           (Some
              Values.DescribeOrganizationConfigurationResponse.error_to_json)])
let describe_publishing_destination =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and destinationId =
         flag "destination-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.describe_publishing_destination
           (Values.DescribePublishingDestinationRequest.make ~detectorId
              ~destinationId ())
           (Some Values.DescribePublishingDestinationResponse.to_json)
           (Some Values.DescribePublishingDestinationResponse.error_to_json)])
let disable_organization_admin_account =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and adminAccountId =
         flag "admin-account-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.disable_organization_admin_account
           (Values.DisableOrganizationAdminAccountRequest.make
              ~adminAccountId ())
           (Some Values.DisableOrganizationAdminAccountResponse.to_json)
           (Some Values.DisableOrganizationAdminAccountResponse.error_to_json)])
let disassociate_from_master_account =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.disassociate_from_master_account
           (Values.DisassociateFromMasterAccountRequest.make ~detectorId ())
           (Some Values.DisassociateFromMasterAccountResponse.to_json)
           (Some Values.DisassociateFromMasterAccountResponse.error_to_json)])
let disassociate_members =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and accountIds =
         flag "account-ids" (required json_arg) ~doc:"JSON AccountIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.disassociate_members
           (Values.DisassociateMembersRequest.make ~detectorId
              ~accountIds:(Values.AccountIds.of_json accountIds) ())
           (Some Values.DisassociateMembersResponse.to_json)
           (Some Values.DisassociateMembersResponse.error_to_json)])
let enable_organization_admin_account =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and adminAccountId =
         flag "admin-account-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.enable_organization_admin_account
           (Values.EnableOrganizationAdminAccountRequest.make ~adminAccountId
              ())
           (Some Values.EnableOrganizationAdminAccountResponse.to_json)
           (Some Values.EnableOrganizationAdminAccountResponse.error_to_json)])
let get_detector =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_detector (Values.GetDetectorRequest.make ~detectorId ())
           (Some Values.GetDetectorResponse.to_json)
           (Some Values.GetDetectorResponse.error_to_json)])
let get_filter =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and filterName =
         flag "filter-name" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_filter
           (Values.GetFilterRequest.make ~detectorId ~filterName ())
           (Some Values.GetFilterResponse.to_json)
           (Some Values.GetFilterResponse.error_to_json)])
let get_findings =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and sortCriteria =
         flag "sort-criteria" (optional json_arg) ~doc:"JSON SortCriteria"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and findingIds =
         flag "finding-ids" (required json_arg) ~doc:"JSON FindingIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_findings
           (Values.GetFindingsRequest.make
              ?sortCriteria:(Option.map ~f:Values.SortCriteria.of_json
                               sortCriteria) ~detectorId
              ~findingIds:(Values.FindingIds.of_json findingIds) ())
           (Some Values.GetFindingsResponse.to_json)
           (Some Values.GetFindingsResponse.error_to_json)])
let get_findings_statistics =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and findingCriteria =
         flag "finding-criteria" (optional json_arg)
           ~doc:"JSON FindingCriteria"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and findingStatisticTypes =
         flag "finding-statistic-types" (required json_arg)
           ~doc:"JSON FindingStatisticTypes" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_findings_statistics
           (Values.GetFindingsStatisticsRequest.make
              ?findingCriteria:(Option.map ~f:Values.FindingCriteria.of_json
                                  findingCriteria) ~detectorId
              ~findingStatisticTypes:(Values.FindingStatisticTypes.of_json
                                        findingStatisticTypes) ())
           (Some Values.GetFindingsStatisticsResponse.to_json)
           (Some Values.GetFindingsStatisticsResponse.error_to_json)])
let get_i_p_set =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and ipSetId = flag "ip-set-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_i_p_set
           (Values.GetIPSetRequest.make ~detectorId ~ipSetId ())
           (Some Values.GetIPSetResponse.to_json)
           (Some Values.GetIPSetResponse.error_to_json)])
let get_invitations_count =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and () = return () in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_invitations_count
           (Values.GetInvitationsCountRequest.make ())
           (Some Values.GetInvitationsCountResponse.to_json)
           (Some Values.GetInvitationsCountResponse.error_to_json)])
let get_master_account =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_master_account
           (Values.GetMasterAccountRequest.make ~detectorId ())
           (Some Values.GetMasterAccountResponse.to_json)
           (Some Values.GetMasterAccountResponse.error_to_json)])
let get_member_detectors =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and accountIds =
         flag "account-ids" (required json_arg) ~doc:"JSON AccountIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_member_detectors
           (Values.GetMemberDetectorsRequest.make ~detectorId
              ~accountIds:(Values.AccountIds.of_json accountIds) ())
           (Some Values.GetMemberDetectorsResponse.to_json)
           (Some Values.GetMemberDetectorsResponse.error_to_json)])
let get_members =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and accountIds =
         flag "account-ids" (required json_arg) ~doc:"JSON AccountIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_members
           (Values.GetMembersRequest.make ~detectorId
              ~accountIds:(Values.AccountIds.of_json accountIds) ())
           (Some Values.GetMembersResponse.to_json)
           (Some Values.GetMembersResponse.error_to_json)])
let get_threat_intel_set =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and threatIntelSetId =
         flag "threat-intel-set-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_threat_intel_set
           (Values.GetThreatIntelSetRequest.make ~detectorId
              ~threatIntelSetId ())
           (Some Values.GetThreatIntelSetResponse.to_json)
           (Some Values.GetThreatIntelSetResponse.error_to_json)])
let get_usage_statistics =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and unit = flag "unit" (optional string) ~doc:"STRING String"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING String"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and usageStatisticType =
         flag "usage-statistic-type" (required json_arg)
           ~doc:"JSON UsageStatisticType"
       and usageCriteria =
         flag "usage-criteria" (required json_arg) ~doc:"JSON UsageCriteria" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_usage_statistics
           (Values.GetUsageStatisticsRequest.make ?unit ?maxResults
              ?nextToken ~detectorId
              ~usageStatisticType:(Values.UsageStatisticType.of_json
                                     usageStatisticType)
              ~usageCriteria:(Values.UsageCriteria.of_json usageCriteria) ())
           (Some Values.GetUsageStatisticsResponse.to_json)
           (Some Values.GetUsageStatisticsResponse.error_to_json)])
let invite_members =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and disableEmailNotification =
         flag "disable-email-notification" (optional bool)
           ~doc:"BOOL Boolean"
       and message = flag "message" (optional string) ~doc:"STRING String"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and accountIds =
         flag "account-ids" (required json_arg) ~doc:"JSON AccountIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.invite_members
           (Values.InviteMembersRequest.make ?disableEmailNotification
              ?message ~detectorId
              ~accountIds:(Values.AccountIds.of_json accountIds) ())
           (Some Values.InviteMembersResponse.to_json)
           (Some Values.InviteMembersResponse.error_to_json)])
let list_detectors =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_detectors
           (Values.ListDetectorsRequest.make ?maxResults ?nextToken ())
           (Some Values.ListDetectorsResponse.to_json)
           (Some Values.ListDetectorsResponse.error_to_json)])
let list_filters =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING String"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_filters
           (Values.ListFiltersRequest.make ?maxResults ?nextToken ~detectorId
              ()) (Some Values.ListFiltersResponse.to_json)
           (Some Values.ListFiltersResponse.error_to_json)])
let list_findings =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and findingCriteria =
         flag "finding-criteria" (optional json_arg)
           ~doc:"JSON FindingCriteria"
       and sortCriteria =
         flag "sort-criteria" (optional json_arg) ~doc:"JSON SortCriteria"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING String"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_findings
           (Values.ListFindingsRequest.make
              ?findingCriteria:(Option.map ~f:Values.FindingCriteria.of_json
                                  findingCriteria)
              ?sortCriteria:(Option.map ~f:Values.SortCriteria.of_json
                               sortCriteria) ?maxResults ?nextToken
              ~detectorId ()) (Some Values.ListFindingsResponse.to_json)
           (Some Values.ListFindingsResponse.error_to_json)])
let list_i_p_sets =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING String"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_i_p_sets
           (Values.ListIPSetsRequest.make ?maxResults ?nextToken ~detectorId
              ()) (Some Values.ListIPSetsResponse.to_json)
           (Some Values.ListIPSetsResponse.error_to_json)])
let list_invitations =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_invitations
           (Values.ListInvitationsRequest.make ?maxResults ?nextToken ())
           (Some Values.ListInvitationsResponse.to_json)
           (Some Values.ListInvitationsResponse.error_to_json)])
let list_members =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING String"
       and onlyAssociated =
         flag "only-associated" (optional string) ~doc:"STRING String"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_members
           (Values.ListMembersRequest.make ?maxResults ?nextToken
              ?onlyAssociated ~detectorId ())
           (Some Values.ListMembersResponse.to_json)
           (Some Values.ListMembersResponse.error_to_json)])
let list_organization_admin_accounts =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_organization_admin_accounts
           (Values.ListOrganizationAdminAccountsRequest.make ?maxResults
              ?nextToken ())
           (Some Values.ListOrganizationAdminAccountsResponse.to_json)
           (Some Values.ListOrganizationAdminAccountsResponse.error_to_json)])
let list_publishing_destinations =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING String"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_publishing_destinations
           (Values.ListPublishingDestinationsRequest.make ?maxResults
              ?nextToken ~detectorId ())
           (Some Values.ListPublishingDestinationsResponse.to_json)
           (Some Values.ListPublishingDestinationsResponse.error_to_json)])
let list_tags_for_resource =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and resourceArn =
         flag "resource-arn" (required string) ~doc:"STRING GuardDutyArn" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_tags_for_resource
           (Values.ListTagsForResourceRequest.make ~resourceArn ())
           (Some Values.ListTagsForResourceResponse.to_json)
           (Some Values.ListTagsForResourceResponse.error_to_json)])
let list_threat_intel_sets =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING String"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_threat_intel_sets
           (Values.ListThreatIntelSetsRequest.make ?maxResults ?nextToken
              ~detectorId ())
           (Some Values.ListThreatIntelSetsResponse.to_json)
           (Some Values.ListThreatIntelSetsResponse.error_to_json)])
let start_monitoring_members =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and accountIds =
         flag "account-ids" (required json_arg) ~doc:"JSON AccountIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.start_monitoring_members
           (Values.StartMonitoringMembersRequest.make ~detectorId
              ~accountIds:(Values.AccountIds.of_json accountIds) ())
           (Some Values.StartMonitoringMembersResponse.to_json)
           (Some Values.StartMonitoringMembersResponse.error_to_json)])
let stop_monitoring_members =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and accountIds =
         flag "account-ids" (required json_arg) ~doc:"JSON AccountIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.stop_monitoring_members
           (Values.StopMonitoringMembersRequest.make ~detectorId
              ~accountIds:(Values.AccountIds.of_json accountIds) ())
           (Some Values.StopMonitoringMembersResponse.to_json)
           (Some Values.StopMonitoringMembersResponse.error_to_json)])
let tag_resource =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and resourceArn =
         flag "resource-arn" (required string) ~doc:"STRING GuardDutyArn"
       and tags = flag "tags" (required json_arg) ~doc:"JSON TagMap" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.tag_resource
           (Values.TagResourceRequest.make ~resourceArn
              ~tags:(Values.TagMap.of_json tags) ())
           (Some Values.TagResourceResponse.to_json)
           (Some Values.TagResourceResponse.error_to_json)])
let unarchive_findings =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and findingIds =
         flag "finding-ids" (required json_arg) ~doc:"JSON FindingIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.unarchive_findings
           (Values.UnarchiveFindingsRequest.make ~detectorId
              ~findingIds:(Values.FindingIds.of_json findingIds) ())
           (Some Values.UnarchiveFindingsResponse.to_json)
           (Some Values.UnarchiveFindingsResponse.error_to_json)])
let untag_resource =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and resourceArn =
         flag "resource-arn" (required string) ~doc:"STRING GuardDutyArn"
       and tagKeys =
         flag "tag-keys" (required json_arg) ~doc:"JSON TagKeyList" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.untag_resource
           (Values.UntagResourceRequest.make ~resourceArn
              ~tagKeys:(Values.TagKeyList.of_json tagKeys) ())
           (Some Values.UntagResourceResponse.to_json)
           (Some Values.UntagResourceResponse.error_to_json)])
let update_detector =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and enable = flag "enable" (optional bool) ~doc:"BOOL Boolean"
       and findingPublishingFrequency =
         flag "finding-publishing-frequency" (optional json_arg)
           ~doc:"JSON FindingPublishingFrequency"
       and dataSources =
         flag "data-sources" (optional json_arg)
           ~doc:"JSON DataSourceConfigurations"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_detector
           (Values.UpdateDetectorRequest.make ?enable
              ?findingPublishingFrequency:(Option.map
                                             ~f:Values.FindingPublishingFrequency.of_json
                                             findingPublishingFrequency)
              ?dataSources:(Option.map
                              ~f:Values.DataSourceConfigurations.of_json
                              dataSources) ~detectorId ())
           (Some Values.UpdateDetectorResponse.to_json)
           (Some Values.UpdateDetectorResponse.error_to_json)])
let update_filter =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and description =
         flag "description" (optional string) ~doc:"STRING FilterDescription"
       and action =
         flag "action" (optional json_arg) ~doc:"JSON FilterAction"
       and rank = flag "rank" (optional int) ~doc:"INT FilterRank"
       and findingCriteria =
         flag "finding-criteria" (optional json_arg)
           ~doc:"JSON FindingCriteria"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and filterName =
         flag "filter-name" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_filter
           (Values.UpdateFilterRequest.make ?description
              ?action:(Option.map ~f:Values.FilterAction.of_json action)
              ?rank
              ?findingCriteria:(Option.map ~f:Values.FindingCriteria.of_json
                                  findingCriteria) ~detectorId ~filterName ())
           (Some Values.UpdateFilterResponse.to_json)
           (Some Values.UpdateFilterResponse.error_to_json)])
let update_findings_feedback =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and comments = flag "comments" (optional string) ~doc:"STRING String"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and findingIds =
         flag "finding-ids" (required json_arg) ~doc:"JSON FindingIds"
       and feedback =
         flag "feedback" (required json_arg) ~doc:"JSON Feedback" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_findings_feedback
           (Values.UpdateFindingsFeedbackRequest.make ?comments ~detectorId
              ~findingIds:(Values.FindingIds.of_json findingIds)
              ~feedback:(Values.Feedback.of_json feedback) ())
           (Some Values.UpdateFindingsFeedbackResponse.to_json)
           (Some Values.UpdateFindingsFeedbackResponse.error_to_json)])
let update_i_p_set =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and name = flag "name" (optional string) ~doc:"STRING Name"
       and location =
         flag "location" (optional string) ~doc:"STRING Location"
       and activate = flag "activate" (optional bool) ~doc:"BOOL Boolean"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and ipSetId = flag "ip-set-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_i_p_set
           (Values.UpdateIPSetRequest.make ?name ?location ?activate
              ~detectorId ~ipSetId ())
           (Some Values.UpdateIPSetResponse.to_json)
           (Some Values.UpdateIPSetResponse.error_to_json)])
let update_member_detectors =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and dataSources =
         flag "data-sources" (optional json_arg)
           ~doc:"JSON DataSourceConfigurations"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and accountIds =
         flag "account-ids" (required json_arg) ~doc:"JSON AccountIds" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_member_detectors
           (Values.UpdateMemberDetectorsRequest.make
              ?dataSources:(Option.map
                              ~f:Values.DataSourceConfigurations.of_json
                              dataSources) ~detectorId
              ~accountIds:(Values.AccountIds.of_json accountIds) ())
           (Some Values.UpdateMemberDetectorsResponse.to_json)
           (Some Values.UpdateMemberDetectorsResponse.error_to_json)])
let update_organization_configuration =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and dataSources =
         flag "data-sources" (optional json_arg)
           ~doc:"JSON OrganizationDataSourceConfigurations"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and autoEnable =
         flag "auto-enable" (required bool) ~doc:"BOOL Boolean" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_organization_configuration
           (Values.UpdateOrganizationConfigurationRequest.make
              ?dataSources:(Option.map
                              ~f:Values.OrganizationDataSourceConfigurations.of_json
                              dataSources) ~detectorId ~autoEnable ())
           (Some Values.UpdateOrganizationConfigurationResponse.to_json)
           (Some Values.UpdateOrganizationConfigurationResponse.error_to_json)])
let update_publishing_destination =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and destinationProperties =
         flag "destination-properties" (optional json_arg)
           ~doc:"JSON DestinationProperties"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and destinationId =
         flag "destination-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_publishing_destination
           (Values.UpdatePublishingDestinationRequest.make
              ?destinationProperties:(Option.map
                                        ~f:Values.DestinationProperties.of_json
                                        destinationProperties) ~detectorId
              ~destinationId ())
           (Some Values.UpdatePublishingDestinationResponse.to_json)
           (Some Values.UpdatePublishingDestinationResponse.error_to_json)])
let update_threat_intel_set =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and name = flag "name" (optional string) ~doc:"STRING Name"
       and location =
         flag "location" (optional string) ~doc:"STRING Location"
       and activate = flag "activate" (optional bool) ~doc:"BOOL Boolean"
       and detectorId =
         flag "detector-id" (required string) ~doc:"STRING DetectorId"
       and threatIntelSetId =
         flag "threat-intel-set-id" (required string) ~doc:"STRING String" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_threat_intel_set
           (Values.UpdateThreatIntelSetRequest.make ?name ?location ?activate
              ~detectorId ~threatIntelSetId ())
           (Some Values.UpdateThreatIntelSetResponse.to_json)
           (Some Values.UpdateThreatIntelSetResponse.error_to_json)])
let main =
  Command.group
    ~summary:((Awso_codegen.Service.to_string Values.service) ^ " commands")
    [("accept-invitation", accept_invitation);
    ("archive-findings", archive_findings);
    ("create-detector", create_detector);
    ("create-filter", create_filter);
    ("create-i-p-set", create_i_p_set);
    ("create-members", create_members);
    ("create-publishing-destination", create_publishing_destination);
    ("create-sample-findings", create_sample_findings);
    ("create-threat-intel-set", create_threat_intel_set);
    ("decline-invitations", decline_invitations);
    ("delete-detector", delete_detector);
    ("delete-filter", delete_filter);
    ("delete-i-p-set", delete_i_p_set);
    ("delete-invitations", delete_invitations);
    ("delete-members", delete_members);
    ("delete-publishing-destination", delete_publishing_destination);
    ("delete-threat-intel-set", delete_threat_intel_set);
    ("describe-organization-configuration",
      describe_organization_configuration);
    ("describe-publishing-destination", describe_publishing_destination);
    ("disable-organization-admin-account",
      disable_organization_admin_account);
    ("disassociate-from-master-account", disassociate_from_master_account);
    ("disassociate-members", disassociate_members);
    ("enable-organization-admin-account", enable_organization_admin_account);
    ("get-detector", get_detector);
    ("get-filter", get_filter);
    ("get-findings", get_findings);
    ("get-findings-statistics", get_findings_statistics);
    ("get-i-p-set", get_i_p_set);
    ("get-invitations-count", get_invitations_count);
    ("get-master-account", get_master_account);
    ("get-member-detectors", get_member_detectors);
    ("get-members", get_members);
    ("get-threat-intel-set", get_threat_intel_set);
    ("get-usage-statistics", get_usage_statistics);
    ("invite-members", invite_members);
    ("list-detectors", list_detectors);
    ("list-filters", list_filters);
    ("list-findings", list_findings);
    ("list-i-p-sets", list_i_p_sets);
    ("list-invitations", list_invitations);
    ("list-members", list_members);
    ("list-organization-admin-accounts", list_organization_admin_accounts);
    ("list-publishing-destinations", list_publishing_destinations);
    ("list-tags-for-resource", list_tags_for_resource);
    ("list-threat-intel-sets", list_threat_intel_sets);
    ("start-monitoring-members", start_monitoring_members);
    ("stop-monitoring-members", stop_monitoring_members);
    ("tag-resource", tag_resource);
    ("unarchive-findings", unarchive_findings);
    ("untag-resource", untag_resource);
    ("update-detector", update_detector);
    ("update-filter", update_filter);
    ("update-findings-feedback", update_findings_feedback);
    ("update-i-p-set", update_i_p_set);
    ("update-member-detectors", update_member_detectors);
    ("update-organization-configuration", update_organization_configuration);
    ("update-publishing-destination", update_publishing_destination);
    ("update-threat-intel-set", update_threat_intel_set)]