(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Awso_security_ir.Values
val batch_get_member_account_details :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      BatchGetMemberAccountDetailsRequest.t ->
        (BatchGetMemberAccountDetailsResponse.t,
          BatchGetMemberAccountDetailsResponse.error) Result.t
          Async.Deferred.t
val cancel_membership :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CancelMembershipRequest.t ->
        (CancelMembershipResponse.t, CancelMembershipResponse.error) Result.t
          Async.Deferred.t
val close_case :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CloseCaseRequest.t ->
        (CloseCaseResponse.t, CloseCaseResponse.error) Result.t
          Async.Deferred.t
val create_case :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateCaseRequest.t ->
        (CreateCaseResponse.t, CreateCaseResponse.error) Result.t
          Async.Deferred.t
val create_case_comment :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateCaseCommentRequest.t ->
        (CreateCaseCommentResponse.t, CreateCaseCommentResponse.error)
          Result.t Async.Deferred.t
val create_membership :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateMembershipRequest.t ->
        (CreateMembershipResponse.t, CreateMembershipResponse.error) Result.t
          Async.Deferred.t
val get_case :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      GetCaseRequest.t ->
        (GetCaseResponse.t, GetCaseResponse.error) Result.t Async.Deferred.t
val get_case_attachment_download_url :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      GetCaseAttachmentDownloadUrlRequest.t ->
        (GetCaseAttachmentDownloadUrlResponse.t,
          GetCaseAttachmentDownloadUrlResponse.error) Result.t
          Async.Deferred.t
val get_case_attachment_upload_url :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      GetCaseAttachmentUploadUrlRequest.t ->
        (GetCaseAttachmentUploadUrlResponse.t,
          GetCaseAttachmentUploadUrlResponse.error) Result.t Async.Deferred.t
val get_membership :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      GetMembershipRequest.t ->
        (GetMembershipResponse.t, GetMembershipResponse.error) Result.t
          Async.Deferred.t
val list_case_edits :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListCaseEditsRequest.t ->
        (ListCaseEditsResponse.t, ListCaseEditsResponse.error) Result.t
          Async.Deferred.t
val list_cases :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListCasesRequest.t ->
        (ListCasesResponse.t, ListCasesResponse.error) Result.t
          Async.Deferred.t
val list_comments :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListCommentsRequest.t ->
        (ListCommentsResponse.t, ListCommentsResponse.error) Result.t
          Async.Deferred.t
val list_investigations :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListInvestigationsRequest.t ->
        (ListInvestigationsResponse.t, ListInvestigationsResponse.error)
          Result.t Async.Deferred.t
val list_memberships :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListMembershipsRequest.t ->
        (ListMembershipsResponse.t, ListMembershipsResponse.error) Result.t
          Async.Deferred.t
val list_tags_for_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListTagsForResourceInput.t ->
        (ListTagsForResourceOutput.t, ListTagsForResourceOutput.error)
          Result.t Async.Deferred.t
val send_feedback :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      SendFeedbackRequest.t ->
        (SendFeedbackResponse.t, SendFeedbackResponse.error) Result.t
          Async.Deferred.t
val tag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      TagResourceInput.t ->
        (TagResourceOutput.t, TagResourceOutput.error) Result.t
          Async.Deferred.t
val untag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UntagResourceInput.t ->
        (UntagResourceOutput.t, UntagResourceOutput.error) Result.t
          Async.Deferred.t
val update_case :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UpdateCaseRequest.t ->
        (UpdateCaseResponse.t, UpdateCaseResponse.error) Result.t
          Async.Deferred.t
val update_case_comment :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UpdateCaseCommentRequest.t ->
        (UpdateCaseCommentResponse.t, UpdateCaseCommentResponse.error)
          Result.t Async.Deferred.t
val update_case_status :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UpdateCaseStatusRequest.t ->
        (UpdateCaseStatusResponse.t, UpdateCaseStatusResponse.error) Result.t
          Async.Deferred.t
val update_membership :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UpdateMembershipRequest.t ->
        (UpdateMembershipResponse.t, UpdateMembershipResponse.error) Result.t
          Async.Deferred.t
val update_resolver_type :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UpdateResolverTypeRequest.t ->
        (UpdateResolverTypeResponse.t, UpdateResolverTypeResponse.error)
          Result.t Async.Deferred.t