(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Awso_cloudhsmv2.Values
val copy_backup_to_region :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      CopyBackupToRegionRequest.t ->
        (CopyBackupToRegionResponse.t, CopyBackupToRegionResponse.error)
          Result.t
val create_cluster :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      CreateClusterRequest.t ->
        (CreateClusterResponse.t, CreateClusterResponse.error) Result.t
val create_hsm :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      CreateHsmRequest.t ->
        (CreateHsmResponse.t, CreateHsmResponse.error) Result.t
val delete_backup :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      DeleteBackupRequest.t ->
        (DeleteBackupResponse.t, DeleteBackupResponse.error) Result.t
val delete_cluster :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      DeleteClusterRequest.t ->
        (DeleteClusterResponse.t, DeleteClusterResponse.error) Result.t
val delete_hsm :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      DeleteHsmRequest.t ->
        (DeleteHsmResponse.t, DeleteHsmResponse.error) Result.t
val delete_resource_policy :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      DeleteResourcePolicyRequest.t ->
        (DeleteResourcePolicyResponse.t, DeleteResourcePolicyResponse.error)
          Result.t
val describe_backups :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      DescribeBackupsRequest.t ->
        (DescribeBackupsResponse.t, DescribeBackupsResponse.error) Result.t
val describe_clusters :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      DescribeClustersRequest.t ->
        (DescribeClustersResponse.t, DescribeClustersResponse.error) Result.t
val get_resource_policy :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      GetResourcePolicyRequest.t ->
        (GetResourcePolicyResponse.t, GetResourcePolicyResponse.error)
          Result.t
val initialize_cluster :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      InitializeClusterRequest.t ->
        (InitializeClusterResponse.t, InitializeClusterResponse.error)
          Result.t
val list_tags :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      ListTagsRequest.t ->
        (ListTagsResponse.t, ListTagsResponse.error) Result.t
val modify_backup_attributes :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      ModifyBackupAttributesRequest.t ->
        (ModifyBackupAttributesResponse.t,
          ModifyBackupAttributesResponse.error) Result.t
val modify_cluster :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      ModifyClusterRequest.t ->
        (ModifyClusterResponse.t, ModifyClusterResponse.error) Result.t
val put_resource_policy :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      PutResourcePolicyRequest.t ->
        (PutResourcePolicyResponse.t, PutResourcePolicyResponse.error)
          Result.t
val restore_backup :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      RestoreBackupRequest.t ->
        (RestoreBackupResponse.t, RestoreBackupResponse.error) Result.t
val tag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      TagResourceRequest.t ->
        (TagResourceResponse.t, TagResourceResponse.error) Result.t
val untag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso_eio.Cfg.t ->
      UntagResourceRequest.t ->
        (UntagResourceResponse.t, UntagResourceResponse.error) Result.t