(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Core
open Async
let json_arg = Command.Arg_type.create Yojson.Safe.from_string
let call ?endpoint_url ?profile ?region f m result_to_json error_to_json =
  let region =
    match region with
    | Some region -> Some (Awso.Region.of_string region)
    | None -> None in
  (Awso_async.Cfg.get_exn ?profile ?region ()) >>=
    (fun cfg ->
       (f ?endpoint_url ?cfg:(Some cfg) m) >>=
         (fun result ->
            match result with
            | Error err ->
                (match error_to_json with
                 | None ->
                     failwithf
                       "endpoint error, but no error values defined in boto"
                       ()
                 | Some to_json ->
                     let s = (err |> to_json) |> Yojson.Safe.to_string in
                     failwithf "AWS error: %s" s ())
            | Ok result ->
                ((match result_to_json with
                  | None -> print_endline "ok response from endpoint"
                  | Some to_json ->
                      ((result |> to_json) |> Yojson.Safe.to_string) |>
                        print_endline);
                 return ())))
let create_act =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and toolSpecs =
         flag "tool-specs" (optional json_arg) ~doc:"JSON ToolSpecs"
       and clientToken =
         flag "client-token" (optional string) ~doc:"STRING ClientToken"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName"
       and workflowRunId =
         flag "workflow-run-id" (required string) ~doc:"STRING UuidString"
       and sessionId =
         flag "session-id" (required string) ~doc:"STRING UuidString"
       and task = flag "task" (required string) ~doc:"STRING Task" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_act
           (Values.CreateActRequest.make
              ?toolSpecs:(Option.map ~f:Values.ToolSpecs.of_json toolSpecs)
              ?clientToken ~workflowDefinitionName ~workflowRunId ~sessionId
              ~task ()) (Some Values.CreateActResponse.to_json)
           (Some Values.CreateActResponse.error_to_json)])
let create_session =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and clientToken =
         flag "client-token" (optional string) ~doc:"STRING ClientToken"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName"
       and workflowRunId =
         flag "workflow-run-id" (required string) ~doc:"STRING UuidString" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_session
           (Values.CreateSessionRequest.make ?clientToken
              ~workflowDefinitionName ~workflowRunId ())
           (Some Values.CreateSessionResponse.to_json)
           (Some Values.CreateSessionResponse.error_to_json)])
let create_workflow_definition =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and description =
         flag "description" (optional string)
           ~doc:"STRING WorkflowDescription"
       and exportConfig =
         flag "export-config" (optional json_arg)
           ~doc:"JSON WorkflowExportConfig"
       and clientToken =
         flag "client-token" (optional string) ~doc:"STRING ClientToken"
       and name =
         flag "name" (required string) ~doc:"STRING WorkflowDefinitionName" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_workflow_definition
           (Values.CreateWorkflowDefinitionRequest.make ?description
              ?exportConfig:(Option.map
                               ~f:Values.WorkflowExportConfig.of_json
                               exportConfig) ?clientToken ~name ())
           (Some Values.CreateWorkflowDefinitionResponse.to_json)
           (Some Values.CreateWorkflowDefinitionResponse.error_to_json)])
let create_workflow_run =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and clientToken =
         flag "client-token" (optional string) ~doc:"STRING ClientToken"
       and logGroupName =
         flag "log-group-name" (optional string)
           ~doc:"STRING CloudWatchLogGroupName"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName"
       and modelId = flag "model-id" (required string) ~doc:"STRING ModelId"
       and clientInfo =
         flag "client-info" (required json_arg) ~doc:"JSON ClientInfo" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_workflow_run
           (Values.CreateWorkflowRunRequest.make ?clientToken ?logGroupName
              ~workflowDefinitionName ~modelId
              ~clientInfo:(Values.ClientInfo.of_json clientInfo) ())
           (Some Values.CreateWorkflowRunResponse.to_json)
           (Some Values.CreateWorkflowRunResponse.error_to_json)])
let delete_workflow_definition =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_workflow_definition
           (Values.DeleteWorkflowDefinitionRequest.make
              ~workflowDefinitionName ())
           (Some Values.DeleteWorkflowDefinitionResponse.to_json)
           (Some Values.DeleteWorkflowDefinitionResponse.error_to_json)])
let delete_workflow_run =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName"
       and workflowRunId =
         flag "workflow-run-id" (required string) ~doc:"STRING UuidString" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_workflow_run
           (Values.DeleteWorkflowRunRequest.make ~workflowDefinitionName
              ~workflowRunId ())
           (Some Values.DeleteWorkflowRunResponse.to_json)
           (Some Values.DeleteWorkflowRunResponse.error_to_json)])
let get_workflow_definition =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_workflow_definition
           (Values.GetWorkflowDefinitionRequest.make ~workflowDefinitionName
              ()) (Some Values.GetWorkflowDefinitionResponse.to_json)
           (Some Values.GetWorkflowDefinitionResponse.error_to_json)])
let get_workflow_run =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName"
       and workflowRunId =
         flag "workflow-run-id" (required string) ~doc:"STRING UuidString" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_workflow_run
           (Values.GetWorkflowRunRequest.make ~workflowDefinitionName
              ~workflowRunId ()) (Some Values.GetWorkflowRunResponse.to_json)
           (Some Values.GetWorkflowRunResponse.error_to_json)])
let invoke_act_step =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and previousStepId =
         flag "previous-step-id" (optional string) ~doc:"STRING UuidString"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName"
       and workflowRunId =
         flag "workflow-run-id" (required string) ~doc:"STRING UuidString"
       and sessionId =
         flag "session-id" (required string) ~doc:"STRING UuidString"
       and actId = flag "act-id" (required string) ~doc:"STRING UuidString"
       and callResults =
         flag "call-results" (required json_arg) ~doc:"JSON CallResults" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.invoke_act_step
           (Values.InvokeActStepRequest.make ?previousStepId
              ~workflowDefinitionName ~workflowRunId ~sessionId ~actId
              ~callResults:(Values.CallResults.of_json callResults) ())
           (Some Values.InvokeActStepResponse.to_json)
           (Some Values.InvokeActStepResponse.error_to_json)])
let list_acts =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and workflowRunId =
         flag "workflow-run-id" (optional string) ~doc:"STRING UuidString"
       and sessionId =
         flag "session-id" (optional string) ~doc:"STRING UuidString"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING NextToken"
       and sortOrder =
         flag "sort-order" (optional json_arg) ~doc:"JSON SortOrder"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_acts
           (Values.ListActsRequest.make ?workflowRunId ?sessionId ?maxResults
              ?nextToken
              ?sortOrder:(Option.map ~f:Values.SortOrder.of_json sortOrder)
              ~workflowDefinitionName ())
           (Some Values.ListActsResponse.to_json)
           (Some Values.ListActsResponse.error_to_json)])
let list_models =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and clientCompatibilityVersion =
         flag "client-compatibility-version" (required int)
           ~doc:"INT Integer" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_models
           (Values.ListModelsRequest.make ~clientCompatibilityVersion ())
           (Some Values.ListModelsResponse.to_json)
           (Some Values.ListModelsResponse.error_to_json)])
let list_sessions =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING NextToken"
       and sortOrder =
         flag "sort-order" (optional json_arg) ~doc:"JSON SortOrder"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName"
       and workflowRunId =
         flag "workflow-run-id" (required string) ~doc:"STRING UuidString" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_sessions
           (Values.ListSessionsRequest.make ?maxResults ?nextToken
              ?sortOrder:(Option.map ~f:Values.SortOrder.of_json sortOrder)
              ~workflowDefinitionName ~workflowRunId ())
           (Some Values.ListSessionsResponse.to_json)
           (Some Values.ListSessionsResponse.error_to_json)])
let list_workflow_definitions =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING NextToken"
       and sortOrder =
         flag "sort-order" (optional json_arg) ~doc:"JSON SortOrder" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_workflow_definitions
           (Values.ListWorkflowDefinitionsRequest.make ?maxResults ?nextToken
              ?sortOrder:(Option.map ~f:Values.SortOrder.of_json sortOrder)
              ()) (Some Values.ListWorkflowDefinitionsResponse.to_json)
           (Some Values.ListWorkflowDefinitionsResponse.error_to_json)])
let list_workflow_runs =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING NextToken"
       and sortOrder =
         flag "sort-order" (optional json_arg) ~doc:"JSON SortOrder"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_workflow_runs
           (Values.ListWorkflowRunsRequest.make ?maxResults ?nextToken
              ?sortOrder:(Option.map ~f:Values.SortOrder.of_json sortOrder)
              ~workflowDefinitionName ())
           (Some Values.ListWorkflowRunsResponse.to_json)
           (Some Values.ListWorkflowRunsResponse.error_to_json)])
let update_act =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and error = flag "error" (optional json_arg) ~doc:"JSON ActError"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName"
       and workflowRunId =
         flag "workflow-run-id" (required string) ~doc:"STRING UuidString"
       and sessionId =
         flag "session-id" (required string) ~doc:"STRING UuidString"
       and actId = flag "act-id" (required string) ~doc:"STRING UuidString"
       and status = flag "status" (required json_arg) ~doc:"JSON ActStatus" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_act
           (Values.UpdateActRequest.make
              ?error:(Option.map ~f:Values.ActError.of_json error)
              ~workflowDefinitionName ~workflowRunId ~sessionId ~actId
              ~status:(Values.ActStatus.of_json status) ())
           (Some Values.UpdateActResponse.to_json)
           (Some Values.UpdateActResponse.error_to_json)])
let update_workflow_run =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and workflowDefinitionName =
         flag "workflow-definition-name" (required string)
           ~doc:"STRING WorkflowDefinitionName"
       and workflowRunId =
         flag "workflow-run-id" (required string) ~doc:"STRING UuidString"
       and status =
         flag "status" (required json_arg) ~doc:"JSON WorkflowRunStatus" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_workflow_run
           (Values.UpdateWorkflowRunRequest.make ~workflowDefinitionName
              ~workflowRunId
              ~status:(Values.WorkflowRunStatus.of_json status) ())
           (Some Values.UpdateWorkflowRunResponse.to_json)
           (Some Values.UpdateWorkflowRunResponse.error_to_json)])
let main =
  Command.group
    ~summary:((Awso.Service.to_string Values.service) ^ " commands")
    [("create-act", create_act);
    ("create-session", create_session);
    ("create-workflow-definition", create_workflow_definition);
    ("create-workflow-run", create_workflow_run);
    ("delete-workflow-definition", delete_workflow_definition);
    ("delete-workflow-run", delete_workflow_run);
    ("get-workflow-definition", get_workflow_definition);
    ("get-workflow-run", get_workflow_run);
    ("invoke-act-step", invoke_act_step);
    ("list-acts", list_acts);
    ("list-models", list_models);
    ("list-sessions", list_sessions);
    ("list-workflow-definitions", list_workflow_definitions);
    ("list-workflow-runs", list_workflow_runs);
    ("update-act", update_act);
    ("update-workflow-run", update_workflow_run)]