(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Awso_synthetics.Values
val associate_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      AssociateResourceRequest.t ->
        (AssociateResourceResponse.t, AssociateResourceResponse.error)
          Result.t Lwt.t
val create_canary :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateCanaryRequest.t ->
        (CreateCanaryResponse.t, CreateCanaryResponse.error) Result.t Lwt.t
val create_group :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateGroupRequest.t ->
        (CreateGroupResponse.t, CreateGroupResponse.error) Result.t Lwt.t
val delete_canary :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteCanaryRequest.t ->
        (DeleteCanaryResponse.t, DeleteCanaryResponse.error) Result.t Lwt.t
val delete_group :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteGroupRequest.t ->
        (DeleteGroupResponse.t, DeleteGroupResponse.error) Result.t Lwt.t
val describe_canaries :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeCanariesRequest.t ->
        (DescribeCanariesResponse.t, DescribeCanariesResponse.error) Result.t
          Lwt.t
val describe_canaries_last_run :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeCanariesLastRunRequest.t ->
        (DescribeCanariesLastRunResponse.t,
          DescribeCanariesLastRunResponse.error) Result.t Lwt.t
val describe_runtime_versions :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeRuntimeVersionsRequest.t ->
        (DescribeRuntimeVersionsResponse.t,
          DescribeRuntimeVersionsResponse.error) Result.t Lwt.t
val disassociate_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DisassociateResourceRequest.t ->
        (DisassociateResourceResponse.t, DisassociateResourceResponse.error)
          Result.t Lwt.t
val get_canary :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      GetCanaryRequest.t ->
        (GetCanaryResponse.t, GetCanaryResponse.error) Result.t Lwt.t
val get_canary_runs :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      GetCanaryRunsRequest.t ->
        (GetCanaryRunsResponse.t, GetCanaryRunsResponse.error) Result.t Lwt.t
val get_group :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      GetGroupRequest.t ->
        (GetGroupResponse.t, GetGroupResponse.error) Result.t Lwt.t
val list_associated_groups :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListAssociatedGroupsRequest.t ->
        (ListAssociatedGroupsResponse.t, ListAssociatedGroupsResponse.error)
          Result.t Lwt.t
val list_group_resources :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListGroupResourcesRequest.t ->
        (ListGroupResourcesResponse.t, ListGroupResourcesResponse.error)
          Result.t Lwt.t
val list_groups :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListGroupsRequest.t ->
        (ListGroupsResponse.t, ListGroupsResponse.error) Result.t Lwt.t
val list_tags_for_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListTagsForResourceRequest.t ->
        (ListTagsForResourceResponse.t, ListTagsForResourceResponse.error)
          Result.t Lwt.t
val start_canary :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      StartCanaryRequest.t ->
        (StartCanaryResponse.t, StartCanaryResponse.error) Result.t Lwt.t
val start_canary_dry_run :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      StartCanaryDryRunRequest.t ->
        (StartCanaryDryRunResponse.t, StartCanaryDryRunResponse.error)
          Result.t Lwt.t
val stop_canary :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      StopCanaryRequest.t ->
        (StopCanaryResponse.t, StopCanaryResponse.error) Result.t Lwt.t
val tag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      TagResourceRequest.t ->
        (TagResourceResponse.t, TagResourceResponse.error) Result.t Lwt.t
val untag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UntagResourceRequest.t ->
        (UntagResourceResponse.t, UntagResourceResponse.error) Result.t Lwt.t
val update_canary :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UpdateCanaryRequest.t ->
        (UpdateCanaryResponse.t, UpdateCanaryResponse.error) Result.t Lwt.t