(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open! Awso_common.Jane_compat
open Values
type ('i, 'o, 'e) t =
  | AcceptConnectionInvitation: (AcceptConnectionInvitationRequest.t,
  AcceptConnectionInvitationResponse.t,
  AcceptConnectionInvitationResponse.error) t 
  | AssociateAwsTrainingCertificationEmailDomain:
  (AssociateAwsTrainingCertificationEmailDomainRequest.t,
  AssociateAwsTrainingCertificationEmailDomainResponse.t,
  AssociateAwsTrainingCertificationEmailDomainResponse.error) t 
  | CancelConnection: (CancelConnectionRequest.t, CancelConnectionResponse.t,
  CancelConnectionResponse.error) t 
  | CancelConnectionInvitation: (CancelConnectionInvitationRequest.t,
  CancelConnectionInvitationResponse.t,
  CancelConnectionInvitationResponse.error) t 
  | CancelProfileUpdateTask: (CancelProfileUpdateTaskRequest.t,
  CancelProfileUpdateTaskResponse.t, CancelProfileUpdateTaskResponse.error) t
  
  | CreateConnectionInvitation: (CreateConnectionInvitationRequest.t,
  CreateConnectionInvitationResponse.t,
  CreateConnectionInvitationResponse.error) t 
  | CreatePartner: (CreatePartnerRequest.t, CreatePartnerResponse.t,
  CreatePartnerResponse.error) t 
  | DisassociateAwsTrainingCertificationEmailDomain:
  (DisassociateAwsTrainingCertificationEmailDomainRequest.t,
  DisassociateAwsTrainingCertificationEmailDomainResponse.t,
  DisassociateAwsTrainingCertificationEmailDomainResponse.error) t 
  | GetAllianceLeadContact: (GetAllianceLeadContactRequest.t,
  GetAllianceLeadContactResponse.t, GetAllianceLeadContactResponse.error) t 
  | GetConnection: (GetConnectionRequest.t, GetConnectionResponse.t,
  GetConnectionResponse.error) t 
  | GetConnectionInvitation: (GetConnectionInvitationRequest.t,
  GetConnectionInvitationResponse.t, GetConnectionInvitationResponse.error) t
  
  | GetConnectionPreferences: (GetConnectionPreferencesRequest.t,
  GetConnectionPreferencesResponse.t, GetConnectionPreferencesResponse.error)
  t 
  | GetPartner: (GetPartnerRequest.t, GetPartnerResponse.t,
  GetPartnerResponse.error) t 
  | GetProfileUpdateTask: (GetProfileUpdateTaskRequest.t,
  GetProfileUpdateTaskResponse.t, GetProfileUpdateTaskResponse.error) t 
  | GetProfileVisibility: (GetProfileVisibilityRequest.t,
  GetProfileVisibilityResponse.t, GetProfileVisibilityResponse.error) t 
  | GetVerification: (GetVerificationRequest.t, GetVerificationResponse.t,
  GetVerificationResponse.error) t 
  | ListConnectionInvitations: (ListConnectionInvitationsRequest.t,
  ListConnectionInvitationsResponse.t,
  ListConnectionInvitationsResponse.error) t 
  | ListConnections: (ListConnectionsRequest.t, ListConnectionsResponse.t,
  ListConnectionsResponse.error) t 
  | ListPartners: (ListPartnersRequest.t, ListPartnersResponse.t,
  ListPartnersResponse.error) t 
  | ListTagsForResource: (ListTagsForResourceRequest.t,
  ListTagsForResourceResponse.t, ListTagsForResourceResponse.error) t 
  | PutAllianceLeadContact: (PutAllianceLeadContactRequest.t,
  PutAllianceLeadContactResponse.t, PutAllianceLeadContactResponse.error) t 
  | PutProfileVisibility: (PutProfileVisibilityRequest.t,
  PutProfileVisibilityResponse.t, PutProfileVisibilityResponse.error) t 
  | RejectConnectionInvitation: (RejectConnectionInvitationRequest.t,
  RejectConnectionInvitationResponse.t,
  RejectConnectionInvitationResponse.error) t 
  | SendEmailVerificationCode: (SendEmailVerificationCodeRequest.t,
  SendEmailVerificationCodeResponse.t,
  SendEmailVerificationCodeResponse.error) t 
  | StartProfileUpdateTask: (StartProfileUpdateTaskRequest.t,
  StartProfileUpdateTaskResponse.t, StartProfileUpdateTaskResponse.error) t 
  | StartVerification: (StartVerificationRequest.t,
  StartVerificationResponse.t, StartVerificationResponse.error) t 
  | TagResource: (TagResourceRequest.t, TagResourceResponse.t,
  TagResourceResponse.error) t 
  | UntagResource: (UntagResourceRequest.t, UntagResourceResponse.t,
  UntagResourceResponse.error) t 
  | UpdateConnectionPreferences: (UpdateConnectionPreferencesRequest.t,
  UpdateConnectionPreferencesResponse.t,
  UpdateConnectionPreferencesResponse.error) t 
let method_of_endpoint : type i o e. (i, o, e) t -> _ =
  function
  | AcceptConnectionInvitation -> `POST
  | AssociateAwsTrainingCertificationEmailDomain -> `POST
  | CancelConnection -> `POST
  | CancelConnectionInvitation -> `POST
  | CancelProfileUpdateTask -> `POST
  | CreateConnectionInvitation -> `POST
  | CreatePartner -> `POST
  | DisassociateAwsTrainingCertificationEmailDomain -> `POST
  | GetAllianceLeadContact -> `POST
  | GetConnection -> `POST
  | GetConnectionInvitation -> `POST
  | GetConnectionPreferences -> `POST
  | GetPartner -> `POST
  | GetProfileUpdateTask -> `POST
  | GetProfileVisibility -> `POST
  | GetVerification -> `POST
  | ListConnectionInvitations -> `POST
  | ListConnections -> `POST
  | ListPartners -> `POST
  | ListTagsForResource -> `POST
  | PutAllianceLeadContact -> `POST
  | PutProfileVisibility -> `POST
  | RejectConnectionInvitation -> `POST
  | SendEmailVerificationCode -> `POST
  | StartProfileUpdateTask -> `POST
  | StartVerification -> `POST
  | TagResource -> `POST
  | UntagResource -> `POST
  | UpdateConnectionPreferences -> `POST
let uri_of_endpoint : type i o e. (i, o, e) t -> i -> Uri.t =
  ((fun endpoint x ->
      match endpoint with
      | AcceptConnectionInvitation -> (Format.kasprintf Uri.of_string) "/"
      | AssociateAwsTrainingCertificationEmailDomain ->
          (Format.kasprintf Uri.of_string) "/"
      | CancelConnection -> (Format.kasprintf Uri.of_string) "/"
      | CancelConnectionInvitation -> (Format.kasprintf Uri.of_string) "/"
      | CancelProfileUpdateTask -> (Format.kasprintf Uri.of_string) "/"
      | CreateConnectionInvitation -> (Format.kasprintf Uri.of_string) "/"
      | CreatePartner -> (Format.kasprintf Uri.of_string) "/"
      | DisassociateAwsTrainingCertificationEmailDomain ->
          (Format.kasprintf Uri.of_string) "/"
      | GetAllianceLeadContact -> (Format.kasprintf Uri.of_string) "/"
      | GetConnection -> (Format.kasprintf Uri.of_string) "/"
      | GetConnectionInvitation -> (Format.kasprintf Uri.of_string) "/"
      | GetConnectionPreferences -> (Format.kasprintf Uri.of_string) "/"
      | GetPartner -> (Format.kasprintf Uri.of_string) "/"
      | GetProfileUpdateTask -> (Format.kasprintf Uri.of_string) "/"
      | GetProfileVisibility -> (Format.kasprintf Uri.of_string) "/"
      | GetVerification -> (Format.kasprintf Uri.of_string) "/"
      | ListConnectionInvitations -> (Format.kasprintf Uri.of_string) "/"
      | ListConnections -> (Format.kasprintf Uri.of_string) "/"
      | ListPartners -> (Format.kasprintf Uri.of_string) "/"
      | ListTagsForResource -> (Format.kasprintf Uri.of_string) "/"
      | PutAllianceLeadContact -> (Format.kasprintf Uri.of_string) "/"
      | PutProfileVisibility -> (Format.kasprintf Uri.of_string) "/"
      | RejectConnectionInvitation -> (Format.kasprintf Uri.of_string) "/"
      | SendEmailVerificationCode -> (Format.kasprintf Uri.of_string) "/"
      | StartProfileUpdateTask -> (Format.kasprintf Uri.of_string) "/"
      | StartVerification -> (Format.kasprintf Uri.of_string) "/"
      | TagResource -> (Format.kasprintf Uri.of_string) "/"
      | UntagResource -> (Format.kasprintf Uri.of_string) "/"
      | UpdateConnectionPreferences -> (Format.kasprintf Uri.of_string) "/")
  [@ocaml.warning "-27"])
let to_request (type i) (type o) (type e) (endp : (i, o, e) t) (req : i) =
  match endp with
  | AcceptConnectionInvitation ->
      let json = AcceptConnectionInvitationRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target",
            "PartnerCentralAccount.AcceptConnectionInvitation")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | AssociateAwsTrainingCertificationEmailDomain ->
      let json =
        AssociateAwsTrainingCertificationEmailDomainRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target",
            "PartnerCentralAccount.AssociateAwsTrainingCertificationEmailDomain")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CancelConnection ->
      let json = CancelConnectionRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.CancelConnection")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CancelConnectionInvitation ->
      let json = CancelConnectionInvitationRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target",
            "PartnerCentralAccount.CancelConnectionInvitation")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CancelProfileUpdateTask ->
      let json = CancelProfileUpdateTaskRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.CancelProfileUpdateTask")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreateConnectionInvitation ->
      let json = CreateConnectionInvitationRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target",
            "PartnerCentralAccount.CreateConnectionInvitation")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreatePartner ->
      let json = CreatePartnerRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.CreatePartner")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DisassociateAwsTrainingCertificationEmailDomain ->
      let json =
        DisassociateAwsTrainingCertificationEmailDomainRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target",
            "PartnerCentralAccount.DisassociateAwsTrainingCertificationEmailDomain")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetAllianceLeadContact ->
      let json = GetAllianceLeadContactRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.GetAllianceLeadContact")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetConnection ->
      let json = GetConnectionRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.GetConnection")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetConnectionInvitation ->
      let json = GetConnectionInvitationRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.GetConnectionInvitation")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetConnectionPreferences ->
      let json = GetConnectionPreferencesRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.GetConnectionPreferences")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetPartner ->
      let json = GetPartnerRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.GetPartner")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetProfileUpdateTask ->
      let json = GetProfileUpdateTaskRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.GetProfileUpdateTask")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetProfileVisibility ->
      let json = GetProfileVisibilityRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.GetProfileVisibility")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetVerification ->
      let json = GetVerificationRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.GetVerification")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListConnectionInvitations ->
      let json = ListConnectionInvitationsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.ListConnectionInvitations")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListConnections ->
      let json = ListConnectionsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.ListConnections")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListPartners ->
      let json = ListPartnersRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.ListPartners")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListTagsForResource ->
      let json = ListTagsForResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.ListTagsForResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | PutAllianceLeadContact ->
      let json = PutAllianceLeadContactRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.PutAllianceLeadContact")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | PutProfileVisibility ->
      let json = PutProfileVisibilityRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.PutProfileVisibility")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | RejectConnectionInvitation ->
      let json = RejectConnectionInvitationRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target",
            "PartnerCentralAccount.RejectConnectionInvitation")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | SendEmailVerificationCode ->
      let json = SendEmailVerificationCodeRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.SendEmailVerificationCode")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | StartProfileUpdateTask ->
      let json = StartProfileUpdateTaskRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.StartProfileUpdateTask")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | StartVerification ->
      let json = StartVerificationRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.StartVerification")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | TagResource ->
      let json = TagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.TagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UntagResource ->
      let json = UntagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "PartnerCentralAccount.UntagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateConnectionPreferences ->
      let json = UpdateConnectionPreferencesRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target",
            "PartnerCentralAccount.UpdateConnectionPreferences")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
let of_response (type i) (type o) (type e) (endpoint : (i, o, e) t)
  (resp : Awso.Http.Response.t) : (o, e) result=
  let code = Awso.Http.Status.to_code (Awso.Http.Response.status resp) in
  let is_success = (code >= 200) && (code < 300) in
  let parse_aws_error error_of_json =
    let body = Awso.Http.Response.body resp in
    let bail () =
      raise
        (Awso.Http.Io.Error.Bad_response
           { Awso.Http.Io.Error.code = code; body; x_amzn_error_type = None }) in
    match (error_of_json, ((code >= 400) && (code <= 599))) with
    | (Some error_of_json, true) ->
        let json = Yojson.Safe.from_string body in
        (match json |> (Yojson.Safe.Util.member "__type") with
         | `String error_type -> error_of_json error_type json
         | `Null -> bail ()
         | _ ->
             failwith
               (sprintf "Error '__type' did not have string type: %s" body))
    | (None, _) | (_, false) -> bail () in
  let _ = parse_aws_error in
  let _ = resp in
  match endpoint with
  | AcceptConnectionInvitation ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (AcceptConnectionInvitationResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some AcceptConnectionInvitationResponse.error_of_json))
  | AssociateAwsTrainingCertificationEmailDomain ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok
          (AssociateAwsTrainingCertificationEmailDomainResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some
                AssociateAwsTrainingCertificationEmailDomainResponse.error_of_json))
  | CancelConnection ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CancelConnectionResponse.of_json json)
      else
        Error (parse_aws_error (Some CancelConnectionResponse.error_of_json))
  | CancelConnectionInvitation ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CancelConnectionInvitationResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some CancelConnectionInvitationResponse.error_of_json))
  | CancelProfileUpdateTask ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CancelProfileUpdateTaskResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some CancelProfileUpdateTaskResponse.error_of_json))
  | CreateConnectionInvitation ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CreateConnectionInvitationResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some CreateConnectionInvitationResponse.error_of_json))
  | CreatePartner ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CreatePartnerResponse.of_json json)
      else Error (parse_aws_error (Some CreatePartnerResponse.error_of_json))
  | DisassociateAwsTrainingCertificationEmailDomain ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok
          (DisassociateAwsTrainingCertificationEmailDomainResponse.of_json
             json)
      else
        Error
          (parse_aws_error
             (Some
                DisassociateAwsTrainingCertificationEmailDomainResponse.error_of_json))
  | GetAllianceLeadContact ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetAllianceLeadContactResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some GetAllianceLeadContactResponse.error_of_json))
  | GetConnection ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetConnectionResponse.of_json json)
      else Error (parse_aws_error (Some GetConnectionResponse.error_of_json))
  | GetConnectionInvitation ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetConnectionInvitationResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some GetConnectionInvitationResponse.error_of_json))
  | GetConnectionPreferences ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetConnectionPreferencesResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some GetConnectionPreferencesResponse.error_of_json))
  | GetPartner ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetPartnerResponse.of_json json)
      else Error (parse_aws_error (Some GetPartnerResponse.error_of_json))
  | GetProfileUpdateTask ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetProfileUpdateTaskResponse.of_json json)
      else
        Error
          (parse_aws_error (Some GetProfileUpdateTaskResponse.error_of_json))
  | GetProfileVisibility ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetProfileVisibilityResponse.of_json json)
      else
        Error
          (parse_aws_error (Some GetProfileVisibilityResponse.error_of_json))
  | GetVerification ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetVerificationResponse.of_json json)
      else
        Error (parse_aws_error (Some GetVerificationResponse.error_of_json))
  | ListConnectionInvitations ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListConnectionInvitationsResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some ListConnectionInvitationsResponse.error_of_json))
  | ListConnections ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListConnectionsResponse.of_json json)
      else
        Error (parse_aws_error (Some ListConnectionsResponse.error_of_json))
  | ListPartners ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListPartnersResponse.of_json json)
      else Error (parse_aws_error (Some ListPartnersResponse.error_of_json))
  | ListTagsForResource ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListTagsForResourceResponse.of_json json)
      else
        Error
          (parse_aws_error (Some ListTagsForResourceResponse.error_of_json))
  | PutAllianceLeadContact ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (PutAllianceLeadContactResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some PutAllianceLeadContactResponse.error_of_json))
  | PutProfileVisibility ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (PutProfileVisibilityResponse.of_json json)
      else
        Error
          (parse_aws_error (Some PutProfileVisibilityResponse.error_of_json))
  | RejectConnectionInvitation ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (RejectConnectionInvitationResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some RejectConnectionInvitationResponse.error_of_json))
  | SendEmailVerificationCode ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (SendEmailVerificationCodeResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some SendEmailVerificationCodeResponse.error_of_json))
  | StartProfileUpdateTask ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (StartProfileUpdateTaskResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some StartProfileUpdateTaskResponse.error_of_json))
  | StartVerification ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (StartVerificationResponse.of_json json)
      else
        Error
          (parse_aws_error (Some StartVerificationResponse.error_of_json))
  | TagResource ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (TagResourceResponse.of_json json)
      else Error (parse_aws_error (Some TagResourceResponse.error_of_json))
  | UntagResource ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (UntagResourceResponse.of_json json)
      else Error (parse_aws_error (Some UntagResourceResponse.error_of_json))
  | UpdateConnectionPreferences ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (UpdateConnectionPreferencesResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some UpdateConnectionPreferencesResponse.error_of_json))