(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso *)
open Awso_cloudhsmv2.Values
val copy_backup_to_region :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CopyBackupToRegionRequest.t ->
        (CopyBackupToRegionResponse.t,
          [ `AWS of CopyBackupToRegionResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val create_cluster :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateClusterRequest.t ->
        (CreateClusterResponse.t,
          [ `AWS of CreateClusterResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val create_hsm :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      CreateHsmRequest.t ->
        (CreateHsmResponse.t,
          [ `AWS of CreateHsmResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val delete_backup :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteBackupRequest.t ->
        (DeleteBackupResponse.t,
          [ `AWS of DeleteBackupResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val delete_cluster :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteClusterRequest.t ->
        (DeleteClusterResponse.t,
          [ `AWS of DeleteClusterResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val delete_hsm :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DeleteHsmRequest.t ->
        (DeleteHsmResponse.t,
          [ `AWS of DeleteHsmResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val describe_backups :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeBackupsRequest.t ->
        (DescribeBackupsResponse.t,
          [ `AWS of DescribeBackupsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val describe_clusters :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      DescribeClustersRequest.t ->
        (DescribeClustersResponse.t,
          [ `AWS of DescribeClustersResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val initialize_cluster :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      InitializeClusterRequest.t ->
        (InitializeClusterResponse.t,
          [ `AWS of InitializeClusterResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val list_tags :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ListTagsRequest.t ->
        (ListTagsResponse.t,
          [ `AWS of ListTagsResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val modify_backup_attributes :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ModifyBackupAttributesRequest.t ->
        (ModifyBackupAttributesResponse.t,
          [ `AWS of ModifyBackupAttributesResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val modify_cluster :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      ModifyClusterRequest.t ->
        (ModifyClusterResponse.t,
          [ `AWS of ModifyClusterResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val restore_backup :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      RestoreBackupRequest.t ->
        (RestoreBackupResponse.t,
          [ `AWS of RestoreBackupResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val tag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      TagResourceRequest.t ->
        (TagResourceResponse.t,
          [ `AWS of TagResourceResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t
val untag_resource :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      UntagResourceRequest.t ->
        (UntagResourceResponse.t,
          [ `AWS of UntagResourceResponse.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t