(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Awso_kinesis_video_media.Values
val get_media :
  ?endpoint_url:string ->
    ?cfg:Awso.Cfg.t ->
      GetMediaInput.t ->
        (GetMediaOutput.t,
          [ `AWS of GetMediaOutput.error 
          | `Transport of Awso.Http.Io.Error.call ]) Result.t Lwt.t