(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open! Awso_common.Jane_compat
open Values
type ('i, 'o, 'e) t =
  | AbortMultipartUpload: (AbortMultipartUploadInput.t, unit, unit) t 
  | AbortVaultLock: (AbortVaultLockInput.t, unit, unit) t 
  | AddTagsToVault: (AddTagsToVaultInput.t, unit, unit) t 
  | CompleteMultipartUpload: (CompleteMultipartUploadInput.t,
  ArchiveCreationOutput.t, ArchiveCreationOutput.error) t 
  | CompleteVaultLock: (CompleteVaultLockInput.t, unit, unit) t 
  | CreateVault: (CreateVaultInput.t, CreateVaultOutput.t,
  CreateVaultOutput.error) t 
  | DeleteArchive: (DeleteArchiveInput.t, unit, unit) t 
  | DeleteVault: (DeleteVaultInput.t, unit, unit) t 
  | DeleteVaultAccessPolicy: (DeleteVaultAccessPolicyInput.t, unit, unit) t 
  | DeleteVaultNotifications: (DeleteVaultNotificationsInput.t, unit, 
  unit) t 
  | DescribeJob: (DescribeJobInput.t, GlacierJobDescription.t,
  GlacierJobDescription.error) t 
  | DescribeVault: (DescribeVaultInput.t, DescribeVaultOutput.t,
  DescribeVaultOutput.error) t 
  | GetDataRetrievalPolicy: (GetDataRetrievalPolicyInput.t,
  GetDataRetrievalPolicyOutput.t, GetDataRetrievalPolicyOutput.error) t 
  | GetJobOutput: (GetJobOutputInput.t, GetJobOutputOutput.t,
  GetJobOutputOutput.error) t 
  | GetVaultAccessPolicy: (GetVaultAccessPolicyInput.t,
  GetVaultAccessPolicyOutput.t, GetVaultAccessPolicyOutput.error) t 
  | GetVaultLock: (GetVaultLockInput.t, GetVaultLockOutput.t,
  GetVaultLockOutput.error) t 
  | GetVaultNotifications: (GetVaultNotificationsInput.t,
  GetVaultNotificationsOutput.t, GetVaultNotificationsOutput.error) t 
  | InitiateJob: (InitiateJobInput.t, InitiateJobOutput.t,
  InitiateJobOutput.error) t 
  | InitiateMultipartUpload: (InitiateMultipartUploadInput.t,
  InitiateMultipartUploadOutput.t, InitiateMultipartUploadOutput.error) t 
  | InitiateVaultLock: (InitiateVaultLockInput.t, InitiateVaultLockOutput.t,
  InitiateVaultLockOutput.error) t 
  | ListJobs: (ListJobsInput.t, ListJobsOutput.t, ListJobsOutput.error) t 
  | ListMultipartUploads: (ListMultipartUploadsInput.t,
  ListMultipartUploadsOutput.t, ListMultipartUploadsOutput.error) t 
  | ListParts: (ListPartsInput.t, ListPartsOutput.t, ListPartsOutput.error) t
  
  | ListProvisionedCapacity: (ListProvisionedCapacityInput.t,
  ListProvisionedCapacityOutput.t, ListProvisionedCapacityOutput.error) t 
  | ListTagsForVault: (ListTagsForVaultInput.t, ListTagsForVaultOutput.t,
  ListTagsForVaultOutput.error) t 
  | ListVaults: (ListVaultsInput.t, ListVaultsOutput.t,
  ListVaultsOutput.error) t 
  | PurchaseProvisionedCapacity: (PurchaseProvisionedCapacityInput.t,
  PurchaseProvisionedCapacityOutput.t,
  PurchaseProvisionedCapacityOutput.error) t 
  | RemoveTagsFromVault: (RemoveTagsFromVaultInput.t, unit, unit) t 
  | SetDataRetrievalPolicy: (SetDataRetrievalPolicyInput.t, unit, unit) t 
  | SetVaultAccessPolicy: (SetVaultAccessPolicyInput.t, unit, unit) t 
  | SetVaultNotifications: (SetVaultNotificationsInput.t, unit, unit) t 
  | UploadArchive: (UploadArchiveInput.t, ArchiveCreationOutput.t,
  ArchiveCreationOutput.error) t 
  | UploadMultipartPart: (UploadMultipartPartInput.t,
  UploadMultipartPartOutput.t, UploadMultipartPartOutput.error) t 
let method_of_endpoint : type i o e. (i, o, e) t -> _ =
  function
  | AbortMultipartUpload -> `DELETE
  | AbortVaultLock -> `DELETE
  | AddTagsToVault -> `POST
  | CompleteMultipartUpload -> `POST
  | CompleteVaultLock -> `POST
  | CreateVault -> `PUT
  | DeleteArchive -> `DELETE
  | DeleteVault -> `DELETE
  | DeleteVaultAccessPolicy -> `DELETE
  | DeleteVaultNotifications -> `DELETE
  | DescribeJob -> `GET
  | DescribeVault -> `GET
  | GetDataRetrievalPolicy -> `GET
  | GetJobOutput -> `GET
  | GetVaultAccessPolicy -> `GET
  | GetVaultLock -> `GET
  | GetVaultNotifications -> `GET
  | InitiateJob -> `POST
  | InitiateMultipartUpload -> `POST
  | InitiateVaultLock -> `POST
  | ListJobs -> `GET
  | ListMultipartUploads -> `GET
  | ListParts -> `GET
  | ListProvisionedCapacity -> `GET
  | ListTagsForVault -> `GET
  | ListVaults -> `GET
  | PurchaseProvisionedCapacity -> `POST
  | RemoveTagsFromVault -> `POST
  | SetDataRetrievalPolicy -> `PUT
  | SetVaultAccessPolicy -> `PUT
  | SetVaultNotifications -> `PUT
  | UploadArchive -> `POST
  | UploadMultipartPart -> `PUT
let uri_of_endpoint : type i o e. (i, o, e) t -> i -> Uri.t =
  ((fun endpoint x ->
      match endpoint with
      | AbortMultipartUpload ->
          (Format.kasprintf Uri.of_string)
            "/%s/vaults/%s/multipart-uploads/%s"
            (String_.to_header x.AbortMultipartUploadInput.accountId)
            (String_.to_header x.AbortMultipartUploadInput.vaultName)
            (String_.to_header x.AbortMultipartUploadInput.uploadId)
      | AbortVaultLock ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/lock-policy"
            (String_.to_header x.AbortVaultLockInput.accountId)
            (String_.to_header x.AbortVaultLockInput.vaultName)
      | AddTagsToVault ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/tags?operation=add"
            (String_.to_header x.AddTagsToVaultInput.accountId)
            (String_.to_header x.AddTagsToVaultInput.vaultName)
      | CompleteMultipartUpload ->
          (Format.kasprintf Uri.of_string)
            "/%s/vaults/%s/multipart-uploads/%s"
            (String_.to_header x.CompleteMultipartUploadInput.accountId)
            (String_.to_header x.CompleteMultipartUploadInput.vaultName)
            (String_.to_header x.CompleteMultipartUploadInput.uploadId)
      | CompleteVaultLock ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/lock-policy/%s"
            (String_.to_header x.CompleteVaultLockInput.accountId)
            (String_.to_header x.CompleteVaultLockInput.vaultName)
            (String_.to_header x.CompleteVaultLockInput.lockId)
      | CreateVault ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s"
            (String_.to_header x.CreateVaultInput.accountId)
            (String_.to_header x.CreateVaultInput.vaultName)
      | DeleteArchive ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/archives/%s"
            (String_.to_header x.DeleteArchiveInput.accountId)
            (String_.to_header x.DeleteArchiveInput.vaultName)
            (String_.to_header x.DeleteArchiveInput.archiveId)
      | DeleteVault ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s"
            (String_.to_header x.DeleteVaultInput.accountId)
            (String_.to_header x.DeleteVaultInput.vaultName)
      | DeleteVaultAccessPolicy ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/access-policy"
            (String_.to_header x.DeleteVaultAccessPolicyInput.accountId)
            (String_.to_header x.DeleteVaultAccessPolicyInput.vaultName)
      | DeleteVaultNotifications ->
          (Format.kasprintf Uri.of_string)
            "/%s/vaults/%s/notification-configuration"
            (String_.to_header x.DeleteVaultNotificationsInput.accountId)
            (String_.to_header x.DeleteVaultNotificationsInput.vaultName)
      | DescribeJob ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/jobs/%s"
            (String_.to_header x.DescribeJobInput.accountId)
            (String_.to_header x.DescribeJobInput.vaultName)
            (String_.to_header x.DescribeJobInput.jobId)
      | DescribeVault ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s"
            (String_.to_header x.DescribeVaultInput.accountId)
            (String_.to_header x.DescribeVaultInput.vaultName)
      | GetDataRetrievalPolicy ->
          (Format.kasprintf Uri.of_string) "/%s/policies/data-retrieval"
            (String_.to_header x.GetDataRetrievalPolicyInput.accountId)
      | GetJobOutput ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/jobs/%s/output"
            (String_.to_header x.GetJobOutputInput.accountId)
            (String_.to_header x.GetJobOutputInput.vaultName)
            (String_.to_header x.GetJobOutputInput.jobId)
      | GetVaultAccessPolicy ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/access-policy"
            (String_.to_header x.GetVaultAccessPolicyInput.accountId)
            (String_.to_header x.GetVaultAccessPolicyInput.vaultName)
      | GetVaultLock ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/lock-policy"
            (String_.to_header x.GetVaultLockInput.accountId)
            (String_.to_header x.GetVaultLockInput.vaultName)
      | GetVaultNotifications ->
          (Format.kasprintf Uri.of_string)
            "/%s/vaults/%s/notification-configuration"
            (String_.to_header x.GetVaultNotificationsInput.accountId)
            (String_.to_header x.GetVaultNotificationsInput.vaultName)
      | InitiateJob ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/jobs"
            (String_.to_header x.InitiateJobInput.accountId)
            (String_.to_header x.InitiateJobInput.vaultName)
      | InitiateMultipartUpload ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/multipart-uploads"
            (String_.to_header x.InitiateMultipartUploadInput.accountId)
            (String_.to_header x.InitiateMultipartUploadInput.vaultName)
      | InitiateVaultLock ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/lock-policy"
            (String_.to_header x.InitiateVaultLockInput.accountId)
            (String_.to_header x.InitiateVaultLockInput.vaultName)
      | ListJobs ->
          Uri.add_query_params'
            ((Format.kasprintf Uri.of_string) "/%s/vaults/%s/jobs"
               (String_.to_header x.ListJobsInput.accountId)
               (String_.to_header x.ListJobsInput.vaultName))
            (List.filter_opt
               [Option.map ~f:(fun v -> ("limit", (String_.to_header v)))
                  x.limit;
               Option.map ~f:(fun v -> ("marker", (String_.to_header v)))
                 x.marker;
               Option.map ~f:(fun v -> ("statuscode", (String_.to_header v)))
                 x.statuscode;
               Option.map ~f:(fun v -> ("completed", (String_.to_header v)))
                 x.completed])
      | ListMultipartUploads ->
          Uri.add_query_params'
            ((Format.kasprintf Uri.of_string)
               "/%s/vaults/%s/multipart-uploads"
               (String_.to_header x.ListMultipartUploadsInput.accountId)
               (String_.to_header x.ListMultipartUploadsInput.vaultName))
            (List.filter_opt
               [Option.map ~f:(fun v -> ("marker", (String_.to_header v)))
                  x.marker;
               Option.map ~f:(fun v -> ("limit", (String_.to_header v)))
                 x.limit])
      | ListParts ->
          Uri.add_query_params'
            ((Format.kasprintf Uri.of_string)
               "/%s/vaults/%s/multipart-uploads/%s"
               (String_.to_header x.ListPartsInput.accountId)
               (String_.to_header x.ListPartsInput.vaultName)
               (String_.to_header x.ListPartsInput.uploadId))
            (List.filter_opt
               [Option.map ~f:(fun v -> ("marker", (String_.to_header v)))
                  x.marker;
               Option.map ~f:(fun v -> ("limit", (String_.to_header v)))
                 x.limit])
      | ListProvisionedCapacity ->
          (Format.kasprintf Uri.of_string) "/%s/provisioned-capacity"
            (String_.to_header x.ListProvisionedCapacityInput.accountId)
      | ListTagsForVault ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/tags"
            (String_.to_header x.ListTagsForVaultInput.accountId)
            (String_.to_header x.ListTagsForVaultInput.vaultName)
      | ListVaults ->
          Uri.add_query_params'
            ((Format.kasprintf Uri.of_string) "/%s/vaults"
               (String_.to_header x.ListVaultsInput.accountId))
            (List.filter_opt
               [Option.map ~f:(fun v -> ("marker", (String_.to_header v)))
                  x.marker;
               Option.map ~f:(fun v -> ("limit", (String_.to_header v)))
                 x.limit])
      | PurchaseProvisionedCapacity ->
          (Format.kasprintf Uri.of_string) "/%s/provisioned-capacity"
            (String_.to_header x.PurchaseProvisionedCapacityInput.accountId)
      | RemoveTagsFromVault ->
          (Format.kasprintf Uri.of_string)
            "/%s/vaults/%s/tags?operation=remove"
            (String_.to_header x.RemoveTagsFromVaultInput.accountId)
            (String_.to_header x.RemoveTagsFromVaultInput.vaultName)
      | SetDataRetrievalPolicy ->
          (Format.kasprintf Uri.of_string) "/%s/policies/data-retrieval"
            (String_.to_header x.SetDataRetrievalPolicyInput.accountId)
      | SetVaultAccessPolicy ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/access-policy"
            (String_.to_header x.SetVaultAccessPolicyInput.accountId)
            (String_.to_header x.SetVaultAccessPolicyInput.vaultName)
      | SetVaultNotifications ->
          (Format.kasprintf Uri.of_string)
            "/%s/vaults/%s/notification-configuration"
            (String_.to_header x.SetVaultNotificationsInput.accountId)
            (String_.to_header x.SetVaultNotificationsInput.vaultName)
      | UploadArchive ->
          (Format.kasprintf Uri.of_string) "/%s/vaults/%s/archives"
            (String_.to_header x.UploadArchiveInput.accountId)
            (String_.to_header x.UploadArchiveInput.vaultName)
      | UploadMultipartPart ->
          (Format.kasprintf Uri.of_string)
            "/%s/vaults/%s/multipart-uploads/%s"
            (String_.to_header x.UploadMultipartPartInput.accountId)
            (String_.to_header x.UploadMultipartPartInput.vaultName)
            (String_.to_header x.UploadMultipartPartInput.uploadId))
  [@ocaml.warning "-27"])
let to_request (type i) (type o) (type e) (endp : (i, o, e) t) (req : i) =
  let _req = req in
  match endp with
  | AbortMultipartUpload -> Awso.Http.Request.make (method_of_endpoint endp)
  | AbortVaultLock -> Awso.Http.Request.make (method_of_endpoint endp)
  | AddTagsToVault ->
      let (headers, body) =
        let headers =
          Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map
                   (List.filter_opt
                      [Option.map req.AddTagsToVaultInput.tags
                         ~f:(fun x -> ("Tags", (TagMap.to_value x)))])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | CompleteMultipartUpload ->
      let (headers, body) =
        let headers =
          Some
            ((List.filter_opt
                [Option.map req.CompleteMultipartUploadInput.archiveSize
                   ~f:(fun x -> ("x-amz-archive-size", (String_.to_header x)));
                Option.map req.CompleteMultipartUploadInput.checksum
                  ~f:(fun x ->
                        ("x-amz-sha256-tree-hash", (String_.to_header x)))])
               |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map (List.filter_opt [])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | CompleteVaultLock ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | CreateVault -> Awso.Http.Request.make (method_of_endpoint endp)
  | DeleteArchive -> Awso.Http.Request.make (method_of_endpoint endp)
  | DeleteVault -> Awso.Http.Request.make (method_of_endpoint endp)
  | DeleteVaultAccessPolicy ->
      Awso.Http.Request.make (method_of_endpoint endp)
  | DeleteVaultNotifications ->
      Awso.Http.Request.make (method_of_endpoint endp)
  | DescribeJob ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | DescribeVault ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | GetDataRetrievalPolicy ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | GetJobOutput ->
      let (headers, body) =
        let headers =
          Some
            ((List.filter_opt
                [Option.map req.GetJobOutputInput.range
                   ~f:(fun x -> ("Range", (String_.to_header x)))])
               |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map (List.filter_opt [])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | GetVaultAccessPolicy ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | GetVaultLock ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | GetVaultNotifications ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | InitiateJob ->
      let headers = Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
      let body =
        Option.map req.jobParameters
          ~f:(fun param ->
                ((param |> JobParameters.to_value) |>
                   Awso.Botodata.Json.value_to_json)
                  |> Yojson.Safe.to_string) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | InitiateMultipartUpload ->
      let (headers, body) =
        let headers =
          Some
            ((List.filter_opt
                [Option.map
                   req.InitiateMultipartUploadInput.archiveDescription
                   ~f:(fun x ->
                         ("x-amz-archive-description", (String_.to_header x)));
                Option.map req.InitiateMultipartUploadInput.partSize
                  ~f:(fun x -> ("x-amz-part-size", (String_.to_header x)))])
               |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map (List.filter_opt [])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | InitiateVaultLock ->
      let headers = Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
      let body =
        Option.map req.policy
          ~f:(fun param ->
                ((param |> VaultLockPolicy.to_value) |>
                   Awso.Botodata.Json.value_to_json)
                  |> Yojson.Safe.to_string) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListJobs ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListMultipartUploads ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListParts ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListProvisionedCapacity ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListTagsForVault ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListVaults ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | PurchaseProvisionedCapacity ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | RemoveTagsFromVault ->
      let (headers, body) =
        let headers =
          Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map
                   (List.filter_opt
                      [Option.map req.RemoveTagsFromVaultInput.tagKeys
                         ~f:(fun x -> ("TagKeys", (TagKeyList.to_value x)))])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | SetDataRetrievalPolicy ->
      Awso.Http.Request.make (method_of_endpoint endp)
  | SetVaultAccessPolicy ->
      let headers = Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
      let body =
        Option.map req.policy
          ~f:(fun param ->
                ((param |> VaultAccessPolicy.to_value) |>
                   Awso.Botodata.Json.value_to_json)
                  |> Yojson.Safe.to_string) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | SetVaultNotifications ->
      let headers = Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
      let body =
        Option.map req.vaultNotificationConfig
          ~f:(fun param ->
                ((param |> VaultNotificationConfig.to_value) |>
                   Awso.Botodata.Json.value_to_json)
                  |> Yojson.Safe.to_string) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | UploadArchive ->
      let headers =
        Some
          ((List.filter_opt
              [Option.map req.UploadArchiveInput.archiveDescription
                 ~f:(fun x ->
                       ("x-amz-archive-description", (String_.to_header x)));
              Option.map req.UploadArchiveInput.checksum
                ~f:(fun x ->
                      ("x-amz-sha256-tree-hash", (String_.to_header x)))])
             |> Awso.Http.Headers.of_list) in
      let body = Option.map req.body ~f:Stream.to_header in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | UploadMultipartPart ->
      let headers =
        Some
          ((List.filter_opt
              [Option.map req.UploadMultipartPartInput.checksum
                 ~f:(fun x ->
                       ("x-amz-sha256-tree-hash", (String_.to_header x)));
              Option.map req.UploadMultipartPartInput.range
                ~f:(fun x -> ("Content-Range", (String_.to_header x)))])
             |> Awso.Http.Headers.of_list) in
      let body = Option.map req.body ~f:Stream.to_header in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
let of_response (type i) (type o) (type e) (endpoint : (i, o, e) t)
  (resp : Awso.Http.Response.t) : (o, e) result=
  let code = Awso.Http.Status.to_code (Awso.Http.Response.status resp) in
  let is_success = (code >= 200) && (code < 300) in
  let x_amzn_error_type =
    let headers = Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
    match List.Assoc.find ~equal:String.Caseless.equal headers
            "x-amzn-ErrorType"
    with
    | None -> None
    | Some value ->
        (match String.lsplit2 value ~on:':' with
         | None -> Some value
         | Some (v, _) -> Some v) in
  let parse_aws_error error_of_json =
    let body = Awso.Http.Response.body resp in
    let bail () =
      raise
        (Awso.Http.Io.Error.Bad_response
           { Awso.Http.Io.Error.code = code; body; x_amzn_error_type }) in
    match (x_amzn_error_type, error_of_json,
            ((code >= 400) && (code <= 599)))
    with
    | (Some error_type, Some error_of_json, true) ->
        let json = Yojson.Safe.from_string body in
        error_of_json error_type json
    | (None, Some error_of_json, true) ->
        (try
           let json = Yojson.Safe.from_string body in
           match json |> (Yojson.Safe.Util.member "__type") with
           | `String error_type ->
               let error_type =
                 match String.lsplit2 error_type ~on:'#' with
                 | Some (_, s) -> s
                 | None -> error_type in
               error_of_json error_type json
           | `Null -> bail ()
           | _ ->
               failwithf "Error '__type' did not have string type: %s" body
                 ()
         with | _ -> bail ())
    | (None, _, _) | (_, None, _) | (_, _, false) -> bail () in
  let response_to_json resp =
    Yojson.Safe.from_string (Awso.Http.Response.body resp) in
  let _ = parse_aws_error in
  let _ = response_to_json in
  let _ = resp in
  match endpoint with
  | AbortMultipartUpload ->
      if is_success then Ok () else Error (parse_aws_error None)
  | AbortVaultLock ->
      if is_success then Ok () else Error (parse_aws_error None)
  | AddTagsToVault ->
      if is_success then Ok () else Error (parse_aws_error None)
  | CompleteMultipartUpload ->
      if is_success
      then
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (ArchiveCreationOutput.of_header_and_body (headers, ()))
      else Error (parse_aws_error (Some ArchiveCreationOutput.error_of_json))
  | CompleteVaultLock ->
      if is_success then Ok () else Error (parse_aws_error None)
  | CreateVault ->
      if is_success
      then
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (CreateVaultOutput.of_header_and_body (headers, ()))
      else Error (parse_aws_error (Some CreateVaultOutput.error_of_json))
  | DeleteArchive ->
      if is_success then Ok () else Error (parse_aws_error None)
  | DeleteVault -> if is_success then Ok () else Error (parse_aws_error None)
  | DeleteVaultAccessPolicy ->
      if is_success then Ok () else Error (parse_aws_error None)
  | DeleteVaultNotifications ->
      if is_success then Ok () else Error (parse_aws_error None)
  | DescribeJob ->
      if is_success
      then Ok (GlacierJobDescription.of_json (response_to_json resp))
      else Error (parse_aws_error (Some GlacierJobDescription.error_of_json))
  | DescribeVault ->
      if is_success
      then Ok (DescribeVaultOutput.of_json (response_to_json resp))
      else Error (parse_aws_error (Some DescribeVaultOutput.error_of_json))
  | GetDataRetrievalPolicy ->
      if is_success
      then Ok (GetDataRetrievalPolicyOutput.of_json (response_to_json resp))
      else
        Error
          (parse_aws_error (Some GetDataRetrievalPolicyOutput.error_of_json))
  | GetJobOutput ->
      if is_success
      then
        let body = Stream.of_string (Awso.Http.Response.body resp) in
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (GetJobOutputOutput.of_header_and_body (headers, body))
      else Error (parse_aws_error (Some GetJobOutputOutput.error_of_json))
  | GetVaultAccessPolicy ->
      if is_success
      then
        let body = VaultAccessPolicy.of_string (Awso.Http.Response.body resp) in
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (GetVaultAccessPolicyOutput.of_header_and_body (headers, body))
      else
        Error
          (parse_aws_error (Some GetVaultAccessPolicyOutput.error_of_json))
  | GetVaultLock ->
      if is_success
      then Ok (GetVaultLockOutput.of_json (response_to_json resp))
      else Error (parse_aws_error (Some GetVaultLockOutput.error_of_json))
  | GetVaultNotifications ->
      if is_success
      then
        let body =
          VaultNotificationConfig.of_string (Awso.Http.Response.body resp) in
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (GetVaultNotificationsOutput.of_header_and_body (headers, body))
      else
        Error
          (parse_aws_error (Some GetVaultNotificationsOutput.error_of_json))
  | InitiateJob ->
      if is_success
      then
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (InitiateJobOutput.of_header_and_body (headers, ()))
      else Error (parse_aws_error (Some InitiateJobOutput.error_of_json))
  | InitiateMultipartUpload ->
      if is_success
      then
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (InitiateMultipartUploadOutput.of_header_and_body (headers, ()))
      else
        Error
          (parse_aws_error (Some InitiateMultipartUploadOutput.error_of_json))
  | InitiateVaultLock ->
      if is_success
      then
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (InitiateVaultLockOutput.of_header_and_body (headers, ()))
      else
        Error (parse_aws_error (Some InitiateVaultLockOutput.error_of_json))
  | ListJobs ->
      if is_success
      then Ok (ListJobsOutput.of_json (response_to_json resp))
      else Error (parse_aws_error (Some ListJobsOutput.error_of_json))
  | ListMultipartUploads ->
      if is_success
      then Ok (ListMultipartUploadsOutput.of_json (response_to_json resp))
      else
        Error
          (parse_aws_error (Some ListMultipartUploadsOutput.error_of_json))
  | ListParts ->
      if is_success
      then Ok (ListPartsOutput.of_json (response_to_json resp))
      else Error (parse_aws_error (Some ListPartsOutput.error_of_json))
  | ListProvisionedCapacity ->
      if is_success
      then Ok (ListProvisionedCapacityOutput.of_json (response_to_json resp))
      else
        Error
          (parse_aws_error (Some ListProvisionedCapacityOutput.error_of_json))
  | ListTagsForVault ->
      if is_success
      then Ok (ListTagsForVaultOutput.of_json (response_to_json resp))
      else
        Error (parse_aws_error (Some ListTagsForVaultOutput.error_of_json))
  | ListVaults ->
      if is_success
      then Ok (ListVaultsOutput.of_json (response_to_json resp))
      else Error (parse_aws_error (Some ListVaultsOutput.error_of_json))
  | PurchaseProvisionedCapacity ->
      if is_success
      then
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok
          (PurchaseProvisionedCapacityOutput.of_header_and_body (headers, ()))
      else
        Error
          (parse_aws_error
             (Some PurchaseProvisionedCapacityOutput.error_of_json))
  | RemoveTagsFromVault ->
      if is_success then Ok () else Error (parse_aws_error None)
  | SetDataRetrievalPolicy ->
      if is_success then Ok () else Error (parse_aws_error None)
  | SetVaultAccessPolicy ->
      if is_success then Ok () else Error (parse_aws_error None)
  | SetVaultNotifications ->
      if is_success then Ok () else Error (parse_aws_error None)
  | UploadArchive ->
      if is_success
      then
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (ArchiveCreationOutput.of_header_and_body (headers, ()))
      else Error (parse_aws_error (Some ArchiveCreationOutput.error_of_json))
  | UploadMultipartPart ->
      if is_success
      then
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (UploadMultipartPartOutput.of_header_and_body (headers, ()))
      else
        Error
          (parse_aws_error (Some UploadMultipartPartOutput.error_of_json))