(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso *)
open Core
open Async
let json_arg = Command.Arg_type.create Yojson.Safe.from_string
let call ?endpoint_url ?profile ?region f m result_to_json error_to_json =
  let region =
    match region with
    | Some region -> Some (Awso.Region.of_string region)
    | None -> None in
  (Awso_async.Cfg.get_exn ?profile ?region ()) >>=
    (fun cfg ->
       (f ?endpoint_url ?cfg:(Some cfg) m) >>=
         (fun result ->
            match result with
            | Error err ->
                (match err with
                 | `Transport err ->
                     let msg =
                       match err with
                       | `Bad_response (r : Awso.Http.Io.Error.bad_response)
                           ->
                           sprintf "Bad response: code=%d body=%s" r.code
                             r.body
                       | `Too_many_redirects -> "Too many redirects" in
                     failwithf "Transport error: %s" msg ()
                 | `AWS err ->
                     (match error_to_json with
                      | None ->
                          failwithf
                            "endpoint error, but no error values defined in boto"
                            ()
                      | Some to_json ->
                          let s = (err |> to_json) |> Yojson.Safe.to_string in
                          failwithf "AWS error: %s" s ()))
            | Ok result ->
                ((match result_to_json with
                  | None -> print_endline "ok response from endpoint"
                  | Some to_json ->
                      ((result |> to_json) |> Yojson.Safe.to_string) |>
                        print_endline);
                 return ())))
let batch_get_record =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and identifiers =
         flag "identifiers" (required json_arg)
           ~doc:"JSON BatchGetRecordIdentifiers" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.batch_get_record
           (Values.BatchGetRecordRequest.make
              ~identifiers:(Values.BatchGetRecordIdentifiers.of_json
                              identifiers) ())
           (Some Values.BatchGetRecordResponse.to_json)
           (Some Values.BatchGetRecordResponse.error_to_json)])
let delete_record =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and featureGroupName =
         flag "feature-group-name" (required string)
           ~doc:"STRING FeatureGroupName"
       and recordIdentifierValueAsString =
         flag "record-identifier-value-as-string" (required string)
           ~doc:"STRING ValueAsString"
       and eventTime =
         flag "event-time" (required string) ~doc:"STRING ValueAsString" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_record
           (Values.DeleteRecordRequest.make ~featureGroupName
              ~recordIdentifierValueAsString ~eventTime ()) None None])
let get_record =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and featureNames =
         flag "feature-names" (optional json_arg) ~doc:"JSON FeatureNames"
       and featureGroupName =
         flag "feature-group-name" (required string)
           ~doc:"STRING FeatureGroupName"
       and recordIdentifierValueAsString =
         flag "record-identifier-value-as-string" (required string)
           ~doc:"STRING ValueAsString" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_record
           (Values.GetRecordRequest.make
              ?featureNames:(Option.map ~f:Values.FeatureNames.of_json
                               featureNames) ~featureGroupName
              ~recordIdentifierValueAsString ())
           (Some Values.GetRecordResponse.to_json)
           (Some Values.GetRecordResponse.error_to_json)])
let put_record =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and featureGroupName =
         flag "feature-group-name" (required string)
           ~doc:"STRING FeatureGroupName"
       and record = flag "record" (required json_arg) ~doc:"JSON Record" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.put_record
           (Values.PutRecordRequest.make ~featureGroupName
              ~record:(Values.Record.of_json record) ()) None None])
let main =
  Command.group
    ~summary:((Awso_codegen.Service.to_string Values.service) ^ " commands")
    [("batch-get-record", batch_get_record);
    ("delete-record", delete_record);
    ("get-record", get_record);
    ("put-record", put_record)]