(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso *)
open! Awso_common.Jane_compat
open Values
type ('i, 'o, 'e) t =
  | CreateHttpNamespace: (CreateHttpNamespaceRequest.t,
  CreateHttpNamespaceResponse.t, CreateHttpNamespaceResponse.error) t 
  | CreatePrivateDnsNamespace: (CreatePrivateDnsNamespaceRequest.t,
  CreatePrivateDnsNamespaceResponse.t,
  CreatePrivateDnsNamespaceResponse.error) t 
  | CreatePublicDnsNamespace: (CreatePublicDnsNamespaceRequest.t,
  CreatePublicDnsNamespaceResponse.t, CreatePublicDnsNamespaceResponse.error)
  t 
  | CreateService: (CreateServiceRequest.t, CreateServiceResponse.t,
  CreateServiceResponse.error) t 
  | DeleteNamespace: (DeleteNamespaceRequest.t, DeleteNamespaceResponse.t,
  DeleteNamespaceResponse.error) t 
  | DeleteService: (DeleteServiceRequest.t, DeleteServiceResponse.t,
  DeleteServiceResponse.error) t 
  | DeregisterInstance: (DeregisterInstanceRequest.t,
  DeregisterInstanceResponse.t, DeregisterInstanceResponse.error) t 
  | DiscoverInstances: (DiscoverInstancesRequest.t,
  DiscoverInstancesResponse.t, DiscoverInstancesResponse.error) t 
  | GetInstance: (GetInstanceRequest.t, GetInstanceResponse.t,
  GetInstanceResponse.error) t 
  | GetInstancesHealthStatus: (GetInstancesHealthStatusRequest.t,
  GetInstancesHealthStatusResponse.t, GetInstancesHealthStatusResponse.error)
  t 
  | GetNamespace: (GetNamespaceRequest.t, GetNamespaceResponse.t,
  GetNamespaceResponse.error) t 
  | GetOperation: (GetOperationRequest.t, GetOperationResponse.t,
  GetOperationResponse.error) t 
  | GetService: (GetServiceRequest.t, GetServiceResponse.t,
  GetServiceResponse.error) t 
  | ListInstances: (ListInstancesRequest.t, ListInstancesResponse.t,
  ListInstancesResponse.error) t 
  | ListNamespaces: (ListNamespacesRequest.t, ListNamespacesResponse.t,
  ListNamespacesResponse.error) t 
  | ListOperations: (ListOperationsRequest.t, ListOperationsResponse.t,
  ListOperationsResponse.error) t 
  | ListServices: (ListServicesRequest.t, ListServicesResponse.t,
  ListServicesResponse.error) t 
  | ListTagsForResource: (ListTagsForResourceRequest.t,
  ListTagsForResourceResponse.t, ListTagsForResourceResponse.error) t 
  | RegisterInstance: (RegisterInstanceRequest.t, RegisterInstanceResponse.t,
  RegisterInstanceResponse.error) t 
  | TagResource: (TagResourceRequest.t, TagResourceResponse.t,
  TagResourceResponse.error) t 
  | UntagResource: (UntagResourceRequest.t, UntagResourceResponse.t,
  UntagResourceResponse.error) t 
  | UpdateHttpNamespace: (UpdateHttpNamespaceRequest.t,
  UpdateHttpNamespaceResponse.t, UpdateHttpNamespaceResponse.error) t 
  | UpdateInstanceCustomHealthStatus:
  (UpdateInstanceCustomHealthStatusRequest.t, unit, unit) t 
  | UpdatePrivateDnsNamespace: (UpdatePrivateDnsNamespaceRequest.t,
  UpdatePrivateDnsNamespaceResponse.t,
  UpdatePrivateDnsNamespaceResponse.error) t 
  | UpdatePublicDnsNamespace: (UpdatePublicDnsNamespaceRequest.t,
  UpdatePublicDnsNamespaceResponse.t, UpdatePublicDnsNamespaceResponse.error)
  t 
  | UpdateService: (UpdateServiceRequest.t, UpdateServiceResponse.t,
  UpdateServiceResponse.error) t 
let method_of_endpoint : type i o e. (i, o, e) t -> _ =
  function
  | CreateHttpNamespace -> `POST
  | CreatePrivateDnsNamespace -> `POST
  | CreatePublicDnsNamespace -> `POST
  | CreateService -> `POST
  | DeleteNamespace -> `POST
  | DeleteService -> `POST
  | DeregisterInstance -> `POST
  | DiscoverInstances -> `POST
  | GetInstance -> `POST
  | GetInstancesHealthStatus -> `POST
  | GetNamespace -> `POST
  | GetOperation -> `POST
  | GetService -> `POST
  | ListInstances -> `POST
  | ListNamespaces -> `POST
  | ListOperations -> `POST
  | ListServices -> `POST
  | ListTagsForResource -> `POST
  | RegisterInstance -> `POST
  | TagResource -> `POST
  | UntagResource -> `POST
  | UpdateHttpNamespace -> `POST
  | UpdateInstanceCustomHealthStatus -> `POST
  | UpdatePrivateDnsNamespace -> `POST
  | UpdatePublicDnsNamespace -> `POST
  | UpdateService -> `POST
let uri_of_endpoint : type i o e. (i, o, e) t -> i -> Uri.t =
  ((fun endpoint x ->
      match endpoint with
      | CreateHttpNamespace -> (Format.kasprintf Uri.of_string) "/"
      | CreatePrivateDnsNamespace -> (Format.kasprintf Uri.of_string) "/"
      | CreatePublicDnsNamespace -> (Format.kasprintf Uri.of_string) "/"
      | CreateService -> (Format.kasprintf Uri.of_string) "/"
      | DeleteNamespace -> (Format.kasprintf Uri.of_string) "/"
      | DeleteService -> (Format.kasprintf Uri.of_string) "/"
      | DeregisterInstance -> (Format.kasprintf Uri.of_string) "/"
      | DiscoverInstances -> (Format.kasprintf Uri.of_string) "/"
      | GetInstance -> (Format.kasprintf Uri.of_string) "/"
      | GetInstancesHealthStatus -> (Format.kasprintf Uri.of_string) "/"
      | GetNamespace -> (Format.kasprintf Uri.of_string) "/"
      | GetOperation -> (Format.kasprintf Uri.of_string) "/"
      | GetService -> (Format.kasprintf Uri.of_string) "/"
      | ListInstances -> (Format.kasprintf Uri.of_string) "/"
      | ListNamespaces -> (Format.kasprintf Uri.of_string) "/"
      | ListOperations -> (Format.kasprintf Uri.of_string) "/"
      | ListServices -> (Format.kasprintf Uri.of_string) "/"
      | ListTagsForResource -> (Format.kasprintf Uri.of_string) "/"
      | RegisterInstance -> (Format.kasprintf Uri.of_string) "/"
      | TagResource -> (Format.kasprintf Uri.of_string) "/"
      | UntagResource -> (Format.kasprintf Uri.of_string) "/"
      | UpdateHttpNamespace -> (Format.kasprintf Uri.of_string) "/"
      | UpdateInstanceCustomHealthStatus ->
          (Format.kasprintf Uri.of_string) "/"
      | UpdatePrivateDnsNamespace -> (Format.kasprintf Uri.of_string) "/"
      | UpdatePublicDnsNamespace -> (Format.kasprintf Uri.of_string) "/"
      | UpdateService -> (Format.kasprintf Uri.of_string) "/")
  [@ocaml.warning "-27"])
let to_request (type i) (type o) (type e) (endp : (i, o, e) t) (req : i) =
  match endp with
  | CreateHttpNamespace ->
      let json = CreateHttpNamespaceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.CreateHttpNamespace")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreatePrivateDnsNamespace ->
      let json = CreatePrivateDnsNamespaceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target",
            "Route53AutoNaming_v20170314.CreatePrivateDnsNamespace")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreatePublicDnsNamespace ->
      let json = CreatePublicDnsNamespaceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target",
            "Route53AutoNaming_v20170314.CreatePublicDnsNamespace")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreateService ->
      let json = CreateServiceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.CreateService")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteNamespace ->
      let json = DeleteNamespaceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.DeleteNamespace")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteService ->
      let json = DeleteServiceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.DeleteService")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeregisterInstance ->
      let json = DeregisterInstanceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.DeregisterInstance")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DiscoverInstances ->
      let json = DiscoverInstancesRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.DiscoverInstances")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetInstance ->
      let json = GetInstanceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.GetInstance")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetInstancesHealthStatus ->
      let json = GetInstancesHealthStatusRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target",
            "Route53AutoNaming_v20170314.GetInstancesHealthStatus")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetNamespace ->
      let json = GetNamespaceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.GetNamespace")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetOperation ->
      let json = GetOperationRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.GetOperation")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetService ->
      let json = GetServiceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.GetService")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListInstances ->
      let json = ListInstancesRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.ListInstances")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListNamespaces ->
      let json = ListNamespacesRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.ListNamespaces")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListOperations ->
      let json = ListOperationsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.ListOperations")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListServices ->
      let json = ListServicesRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.ListServices")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListTagsForResource ->
      let json = ListTagsForResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.ListTagsForResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | RegisterInstance ->
      let json = RegisterInstanceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.RegisterInstance")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | TagResource ->
      let json = TagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.TagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UntagResource ->
      let json = UntagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.UntagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateHttpNamespace ->
      let json = UpdateHttpNamespaceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.UpdateHttpNamespace")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateInstanceCustomHealthStatus ->
      let json = UpdateInstanceCustomHealthStatusRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target",
            "Route53AutoNaming_v20170314.UpdateInstanceCustomHealthStatus")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdatePrivateDnsNamespace ->
      let json = UpdatePrivateDnsNamespaceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target",
            "Route53AutoNaming_v20170314.UpdatePrivateDnsNamespace")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdatePublicDnsNamespace ->
      let json = UpdatePublicDnsNamespaceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target",
            "Route53AutoNaming_v20170314.UpdatePublicDnsNamespace")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateService ->
      let json = UpdateServiceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.1");
          ("X-Amz-Target", "Route53AutoNaming_v20170314.UpdateService")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
let of_response (type i) (type o) (type e) (endpoint : (i, o, e) t)
  (resp : (Awso.Http.Response.t, Awso.Http.Io.Error.call) result) :
  (o, [ `AWS of e  | `Transport of Awso.Http.Io.Error.call ]) result=
  let handle_error err error_of_json =
    let generic_error () = Error (`Transport err) in
    match err with
    | `Too_many_redirects -> generic_error ()
    | `Bad_response
        { Awso.Http.Io.Error.code = code; body; x_amzn_error_type = _ } ->
        (match (error_of_json, ((code >= 400) && (code <= 599))) with
         | (Some error_of_json, true) ->
             let json = Yojson.Safe.from_string body in
             (match json |> (Yojson.Safe.Util.member "__type") with
              | `String error_type ->
                  Error (`AWS (error_of_json error_type json))
              | `Null -> generic_error ()
              | _ ->
                  failwith
                    (sprintf "Error '__type' did not have string type: %s"
                       body))
         | (None, _) | (_, false) -> generic_error ()) in
  match endpoint with
  | CreateHttpNamespace ->
      (match resp with
       | Error err ->
           handle_error err (Some CreateHttpNamespaceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (CreateHttpNamespaceResponse.of_json json))
  | CreatePrivateDnsNamespace ->
      (match resp with
       | Error err ->
           handle_error err
             (Some CreatePrivateDnsNamespaceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (CreatePrivateDnsNamespaceResponse.of_json json))
  | CreatePublicDnsNamespace ->
      (match resp with
       | Error err ->
           handle_error err
             (Some CreatePublicDnsNamespaceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (CreatePublicDnsNamespaceResponse.of_json json))
  | CreateService ->
      (match resp with
       | Error err ->
           handle_error err (Some CreateServiceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (CreateServiceResponse.of_json json))
  | DeleteNamespace ->
      (match resp with
       | Error err ->
           handle_error err (Some DeleteNamespaceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (DeleteNamespaceResponse.of_json json))
  | DeleteService ->
      (match resp with
       | Error err ->
           handle_error err (Some DeleteServiceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (DeleteServiceResponse.of_json json))
  | DeregisterInstance ->
      (match resp with
       | Error err ->
           handle_error err (Some DeregisterInstanceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (DeregisterInstanceResponse.of_json json))
  | DiscoverInstances ->
      (match resp with
       | Error err ->
           handle_error err (Some DiscoverInstancesResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (DiscoverInstancesResponse.of_json json))
  | GetInstance ->
      (match resp with
       | Error err ->
           handle_error err (Some GetInstanceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (GetInstanceResponse.of_json json))
  | GetInstancesHealthStatus ->
      (match resp with
       | Error err ->
           handle_error err
             (Some GetInstancesHealthStatusResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (GetInstancesHealthStatusResponse.of_json json))
  | GetNamespace ->
      (match resp with
       | Error err ->
           handle_error err (Some GetNamespaceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (GetNamespaceResponse.of_json json))
  | GetOperation ->
      (match resp with
       | Error err ->
           handle_error err (Some GetOperationResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (GetOperationResponse.of_json json))
  | GetService ->
      (match resp with
       | Error err ->
           handle_error err (Some GetServiceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (GetServiceResponse.of_json json))
  | ListInstances ->
      (match resp with
       | Error err ->
           handle_error err (Some ListInstancesResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListInstancesResponse.of_json json))
  | ListNamespaces ->
      (match resp with
       | Error err ->
           handle_error err (Some ListNamespacesResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListNamespacesResponse.of_json json))
  | ListOperations ->
      (match resp with
       | Error err ->
           handle_error err (Some ListOperationsResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListOperationsResponse.of_json json))
  | ListServices ->
      (match resp with
       | Error err ->
           handle_error err (Some ListServicesResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListServicesResponse.of_json json))
  | ListTagsForResource ->
      (match resp with
       | Error err ->
           handle_error err (Some ListTagsForResourceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (ListTagsForResourceResponse.of_json json))
  | RegisterInstance ->
      (match resp with
       | Error err ->
           handle_error err (Some RegisterInstanceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (RegisterInstanceResponse.of_json json))
  | TagResource ->
      (match resp with
       | Error err ->
           handle_error err (Some TagResourceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (TagResourceResponse.of_json json))
  | UntagResource ->
      (match resp with
       | Error err ->
           handle_error err (Some UntagResourceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (UntagResourceResponse.of_json json))
  | UpdateHttpNamespace ->
      (match resp with
       | Error err ->
           handle_error err (Some UpdateHttpNamespaceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (UpdateHttpNamespaceResponse.of_json json))
  | UpdateInstanceCustomHealthStatus -> Ok ()
  | UpdatePrivateDnsNamespace ->
      (match resp with
       | Error err ->
           handle_error err
             (Some UpdatePrivateDnsNamespaceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (UpdatePrivateDnsNamespaceResponse.of_json json))
  | UpdatePublicDnsNamespace ->
      (match resp with
       | Error err ->
           handle_error err
             (Some UpdatePublicDnsNamespaceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (UpdatePublicDnsNamespaceResponse.of_json json))
  | UpdateService ->
      (match resp with
       | Error err ->
           handle_error err (Some UpdateServiceResponse.error_of_json)
       | Ok resp ->
           let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
           Ok (UpdateServiceResponse.of_json json))