(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open! Awso_common.Jane_compat
open Values
type ('i, 'o, 'e) t =
  | CreateAct: (CreateActRequest.t, CreateActResponse.t,
  CreateActResponse.error) t 
  | CreateSession: (CreateSessionRequest.t, CreateSessionResponse.t,
  CreateSessionResponse.error) t 
  | CreateWorkflowDefinition: (CreateWorkflowDefinitionRequest.t,
  CreateWorkflowDefinitionResponse.t, CreateWorkflowDefinitionResponse.error)
  t 
  | CreateWorkflowRun: (CreateWorkflowRunRequest.t,
  CreateWorkflowRunResponse.t, CreateWorkflowRunResponse.error) t 
  | DeleteWorkflowDefinition: (DeleteWorkflowDefinitionRequest.t,
  DeleteWorkflowDefinitionResponse.t, DeleteWorkflowDefinitionResponse.error)
  t 
  | DeleteWorkflowRun: (DeleteWorkflowRunRequest.t,
  DeleteWorkflowRunResponse.t, DeleteWorkflowRunResponse.error) t 
  | GetWorkflowDefinition: (GetWorkflowDefinitionRequest.t,
  GetWorkflowDefinitionResponse.t, GetWorkflowDefinitionResponse.error) t 
  | GetWorkflowRun: (GetWorkflowRunRequest.t, GetWorkflowRunResponse.t,
  GetWorkflowRunResponse.error) t 
  | InvokeActStep: (InvokeActStepRequest.t, InvokeActStepResponse.t,
  InvokeActStepResponse.error) t 
  | ListActs: (ListActsRequest.t, ListActsResponse.t, ListActsResponse.error)
  t 
  | ListModels: (ListModelsRequest.t, ListModelsResponse.t,
  ListModelsResponse.error) t 
  | ListSessions: (ListSessionsRequest.t, ListSessionsResponse.t,
  ListSessionsResponse.error) t 
  | ListWorkflowDefinitions: (ListWorkflowDefinitionsRequest.t,
  ListWorkflowDefinitionsResponse.t, ListWorkflowDefinitionsResponse.error) t
  
  | ListWorkflowRuns: (ListWorkflowRunsRequest.t, ListWorkflowRunsResponse.t,
  ListWorkflowRunsResponse.error) t 
  | UpdateAct: (UpdateActRequest.t, UpdateActResponse.t,
  UpdateActResponse.error) t 
  | UpdateWorkflowRun: (UpdateWorkflowRunRequest.t,
  UpdateWorkflowRunResponse.t, UpdateWorkflowRunResponse.error) t 
let method_of_endpoint : type i o e. (i, o, e) t -> _ =
  function
  | CreateAct -> `PUT
  | CreateSession -> `PUT
  | CreateWorkflowDefinition -> `PUT
  | CreateWorkflowRun -> `PUT
  | DeleteWorkflowDefinition -> `DELETE
  | DeleteWorkflowRun -> `DELETE
  | GetWorkflowDefinition -> `GET
  | GetWorkflowRun -> `GET
  | InvokeActStep -> `PUT
  | ListActs -> `POST
  | ListModels -> `POST
  | ListSessions -> `POST
  | ListWorkflowDefinitions -> `POST
  | ListWorkflowRuns -> `POST
  | UpdateAct -> `PUT
  | UpdateWorkflowRun -> `PUT
let uri_of_endpoint : type i o e. (i, o, e) t -> i -> Uri.t =
  ((fun endpoint x ->
      match endpoint with
      | CreateAct ->
          (Format.kasprintf Uri.of_string)
            "/workflow-definitions/%s/workflow-runs/%s/sessions/%s/acts"
            (WorkflowDefinitionName.to_header
               x.CreateActRequest.workflowDefinitionName)
            (UuidString.to_header x.CreateActRequest.workflowRunId)
            (UuidString.to_header x.CreateActRequest.sessionId)
      | CreateSession ->
          (Format.kasprintf Uri.of_string)
            "/workflow-definitions/%s/workflow-runs/%s/sessions"
            (WorkflowDefinitionName.to_header
               x.CreateSessionRequest.workflowDefinitionName)
            (UuidString.to_header x.CreateSessionRequest.workflowRunId)
      | CreateWorkflowDefinition ->
          (Format.kasprintf Uri.of_string) "/workflow-definitions"
      | CreateWorkflowRun ->
          (Format.kasprintf Uri.of_string)
            "/workflow-definitions/%s/workflow-runs"
            (WorkflowDefinitionName.to_header
               x.CreateWorkflowRunRequest.workflowDefinitionName)
      | DeleteWorkflowDefinition ->
          (Format.kasprintf Uri.of_string) "/workflow-definitions/%s"
            (WorkflowDefinitionName.to_header
               x.DeleteWorkflowDefinitionRequest.workflowDefinitionName)
      | DeleteWorkflowRun ->
          (Format.kasprintf Uri.of_string)
            "/workflow-definitions/%s/workflow-runs/%s"
            (WorkflowDefinitionName.to_header
               x.DeleteWorkflowRunRequest.workflowDefinitionName)
            (UuidString.to_header x.DeleteWorkflowRunRequest.workflowRunId)
      | GetWorkflowDefinition ->
          (Format.kasprintf Uri.of_string) "/workflow-definitions/%s"
            (WorkflowDefinitionName.to_header
               x.GetWorkflowDefinitionRequest.workflowDefinitionName)
      | GetWorkflowRun ->
          (Format.kasprintf Uri.of_string)
            "/workflow-definitions/%s/workflow-runs/%s"
            (WorkflowDefinitionName.to_header
               x.GetWorkflowRunRequest.workflowDefinitionName)
            (UuidString.to_header x.GetWorkflowRunRequest.workflowRunId)
      | InvokeActStep ->
          (Format.kasprintf Uri.of_string)
            "/workflow-definitions/%s/workflow-runs/%s/sessions/%s/acts/%s/invoke-step/"
            (WorkflowDefinitionName.to_header
               x.InvokeActStepRequest.workflowDefinitionName)
            (UuidString.to_header x.InvokeActStepRequest.workflowRunId)
            (UuidString.to_header x.InvokeActStepRequest.sessionId)
            (UuidString.to_header x.InvokeActStepRequest.actId)
      | ListActs ->
          Uri.add_query_params'
            ((Format.kasprintf Uri.of_string) "/workflow-definitions/%s/acts"
               (WorkflowDefinitionName.to_header
                  x.ListActsRequest.workflowDefinitionName))
            (List.filter_opt
               [Option.map
                  ~f:(fun v -> ("workflowRunId", (UuidString.to_header v)))
                  x.workflowRunId;
               Option.map
                 ~f:(fun v -> ("sessionId", (UuidString.to_header v)))
                 x.sessionId;
               Option.map
                 ~f:(fun v -> ("maxResults", (MaxResults.to_header v)))
                 x.maxResults;
               Option.map
                 ~f:(fun v -> ("nextToken", (NextToken.to_header v)))
                 x.nextToken])
      | ListModels ->
          Uri.add_query_params' ((Format.kasprintf Uri.of_string) "/models")
            (List.filter_opt
               [Some
                  ("clientCompatibilityVersion",
                    (Integer.to_header x.clientCompatibilityVersion))])
      | ListSessions ->
          Uri.add_query_params'
            ((Format.kasprintf Uri.of_string)
               "/workflow-definitions/%s/workflow-runs/%s"
               (WorkflowDefinitionName.to_header
                  x.ListSessionsRequest.workflowDefinitionName)
               (UuidString.to_header x.ListSessionsRequest.workflowRunId))
            (List.filter_opt
               [Option.map
                  ~f:(fun v -> ("maxResults", (MaxResults.to_header v)))
                  x.maxResults;
               Option.map
                 ~f:(fun v -> ("nextToken", (NextToken.to_header v)))
                 x.nextToken])
      | ListWorkflowDefinitions ->
          Uri.add_query_params'
            ((Format.kasprintf Uri.of_string) "/workflow-definitions")
            (List.filter_opt
               [Option.map
                  ~f:(fun v -> ("maxResults", (MaxResults.to_header v)))
                  x.maxResults;
               Option.map
                 ~f:(fun v -> ("nextToken", (NextToken.to_header v)))
                 x.nextToken])
      | ListWorkflowRuns ->
          Uri.add_query_params'
            ((Format.kasprintf Uri.of_string)
               "/workflow-definitions/%s/workflow-runs"
               (WorkflowDefinitionName.to_header
                  x.ListWorkflowRunsRequest.workflowDefinitionName))
            (List.filter_opt
               [Option.map
                  ~f:(fun v -> ("maxResults", (MaxResults.to_header v)))
                  x.maxResults;
               Option.map
                 ~f:(fun v -> ("nextToken", (NextToken.to_header v)))
                 x.nextToken])
      | UpdateAct ->
          (Format.kasprintf Uri.of_string)
            "/workflow-definitions/%s/workflow-runs/%s/sessions/%s/acts/%s"
            (WorkflowDefinitionName.to_header
               x.UpdateActRequest.workflowDefinitionName)
            (UuidString.to_header x.UpdateActRequest.workflowRunId)
            (UuidString.to_header x.UpdateActRequest.sessionId)
            (UuidString.to_header x.UpdateActRequest.actId)
      | UpdateWorkflowRun ->
          (Format.kasprintf Uri.of_string)
            "/workflow-definitions/%s/workflow-runs/%s"
            (WorkflowDefinitionName.to_header
               x.UpdateWorkflowRunRequest.workflowDefinitionName)
            (UuidString.to_header x.UpdateWorkflowRunRequest.workflowRunId))
  [@ocaml.warning "-27"])
let to_request (type i) (type o) (type e) (endp : (i, o, e) t) (req : i) =
  let _req = req in
  match endp with
  | CreateAct -> Awso.Http.Request.make (method_of_endpoint endp)
  | CreateSession -> Awso.Http.Request.make (method_of_endpoint endp)
  | CreateWorkflowDefinition ->
      Awso.Http.Request.make (method_of_endpoint endp)
  | CreateWorkflowRun -> Awso.Http.Request.make (method_of_endpoint endp)
  | DeleteWorkflowDefinition ->
      Awso.Http.Request.make (method_of_endpoint endp)
  | DeleteWorkflowRun -> Awso.Http.Request.make (method_of_endpoint endp)
  | GetWorkflowDefinition ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | GetWorkflowRun ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | InvokeActStep -> Awso.Http.Request.make (method_of_endpoint endp)
  | ListActs ->
      let (headers, body) =
        let headers =
          Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map
                   (List.filter_opt
                      [Option.map req.ListActsRequest.sortOrder
                         ~f:(fun x -> ("sortOrder", (SortOrder.to_value x)))])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListModels ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListSessions ->
      let (headers, body) =
        let headers =
          Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map
                   (List.filter_opt
                      [Option.map req.ListSessionsRequest.sortOrder
                         ~f:(fun x -> ("sortOrder", (SortOrder.to_value x)))])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListWorkflowDefinitions ->
      let (headers, body) =
        let headers =
          Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map
                   (List.filter_opt
                      [Option.map
                         req.ListWorkflowDefinitionsRequest.sortOrder
                         ~f:(fun x -> ("sortOrder", (SortOrder.to_value x)))])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListWorkflowRuns ->
      let (headers, body) =
        let headers =
          Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map
                   (List.filter_opt
                      [Option.map req.ListWorkflowRunsRequest.sortOrder
                         ~f:(fun x -> ("sortOrder", (SortOrder.to_value x)))])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | UpdateAct -> Awso.Http.Request.make (method_of_endpoint endp)
  | UpdateWorkflowRun -> Awso.Http.Request.make (method_of_endpoint endp)
let of_response (type i) (type o) (type e) (endpoint : (i, o, e) t)
  (resp : Awso.Http.Response.t) : (o, e) result=
  let code = Awso.Http.Status.to_code (Awso.Http.Response.status resp) in
  let is_success = (code >= 200) && (code < 300) in
  let x_amzn_error_type =
    let headers = Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
    match List.Assoc.find ~equal:String.Caseless.equal headers
            "x-amzn-ErrorType"
    with
    | None -> None
    | Some value ->
        (match String.lsplit2 value ~on:':' with
         | None -> Some value
         | Some (v, _) -> Some v) in
  let parse_aws_error error_of_json =
    let body = Awso.Http.Response.body resp in
    let bail () =
      raise
        (Awso.Http.Io.Error.Bad_response
           { Awso.Http.Io.Error.code = code; body; x_amzn_error_type }) in
    match (x_amzn_error_type, error_of_json,
            ((code >= 400) && (code <= 599)))
    with
    | (Some error_type, Some error_of_json, true) ->
        let json = Yojson.Safe.from_string body in
        error_of_json error_type json
    | (None, Some error_of_json, true) ->
        (try
           let json = Yojson.Safe.from_string body in
           match json |> (Yojson.Safe.Util.member "__type") with
           | `String error_type ->
               let error_type =
                 match String.lsplit2 error_type ~on:'#' with
                 | Some (_, s) -> s
                 | None -> error_type in
               error_of_json error_type json
           | `Null -> bail ()
           | _ ->
               failwithf "Error '__type' did not have string type: %s" body
                 ()
         with | _ -> bail ())
    | (None, _, _) | (_, None, _) | (_, _, false) -> bail () in
  let response_to_json resp =
    Yojson.Safe.from_string (Awso.Http.Response.body resp) in
  let _ = parse_aws_error in
  let _ = response_to_json in
  let _ = resp in
  match endpoint with
  | CreateAct ->
      if is_success
      then Ok (CreateActResponse.of_json (response_to_json resp))
      else Error (parse_aws_error (Some CreateActResponse.error_of_json))
  | CreateSession ->
      if is_success
      then Ok (CreateSessionResponse.of_json (response_to_json resp))
      else Error (parse_aws_error (Some CreateSessionResponse.error_of_json))
  | CreateWorkflowDefinition ->
      if is_success
      then
        Ok (CreateWorkflowDefinitionResponse.of_json (response_to_json resp))
      else
        Error
          (parse_aws_error
             (Some CreateWorkflowDefinitionResponse.error_of_json))
  | CreateWorkflowRun ->
      if is_success
      then Ok (CreateWorkflowRunResponse.of_json (response_to_json resp))
      else
        Error
          (parse_aws_error (Some CreateWorkflowRunResponse.error_of_json))
  | DeleteWorkflowDefinition ->
      if is_success
      then
        Ok (DeleteWorkflowDefinitionResponse.of_json (response_to_json resp))
      else
        Error
          (parse_aws_error
             (Some DeleteWorkflowDefinitionResponse.error_of_json))
  | DeleteWorkflowRun ->
      if is_success
      then Ok (DeleteWorkflowRunResponse.of_json (response_to_json resp))
      else
        Error
          (parse_aws_error (Some DeleteWorkflowRunResponse.error_of_json))
  | GetWorkflowDefinition ->
      if is_success
      then Ok (GetWorkflowDefinitionResponse.of_json (response_to_json resp))
      else
        Error
          (parse_aws_error (Some GetWorkflowDefinitionResponse.error_of_json))
  | GetWorkflowRun ->
      if is_success
      then Ok (GetWorkflowRunResponse.of_json (response_to_json resp))
      else
        Error (parse_aws_error (Some GetWorkflowRunResponse.error_of_json))
  | InvokeActStep ->
      if is_success
      then Ok (InvokeActStepResponse.of_json (response_to_json resp))
      else Error (parse_aws_error (Some InvokeActStepResponse.error_of_json))
  | ListActs ->
      if is_success
      then Ok (ListActsResponse.of_json (response_to_json resp))
      else Error (parse_aws_error (Some ListActsResponse.error_of_json))
  | ListModels ->
      if is_success
      then Ok (ListModelsResponse.of_json (response_to_json resp))
      else Error (parse_aws_error (Some ListModelsResponse.error_of_json))
  | ListSessions ->
      if is_success
      then Ok (ListSessionsResponse.of_json (response_to_json resp))
      else Error (parse_aws_error (Some ListSessionsResponse.error_of_json))
  | ListWorkflowDefinitions ->
      if is_success
      then
        Ok (ListWorkflowDefinitionsResponse.of_json (response_to_json resp))
      else
        Error
          (parse_aws_error
             (Some ListWorkflowDefinitionsResponse.error_of_json))
  | ListWorkflowRuns ->
      if is_success
      then Ok (ListWorkflowRunsResponse.of_json (response_to_json resp))
      else
        Error (parse_aws_error (Some ListWorkflowRunsResponse.error_of_json))
  | UpdateAct ->
      if is_success
      then
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (UpdateActResponse.of_header_and_body (headers, ()))
      else Error (parse_aws_error (Some UpdateActResponse.error_of_json))
  | UpdateWorkflowRun ->
      if is_success
      then
        let headers =
          Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
        Ok (UpdateWorkflowRunResponse.of_header_and_body (headers, ()))
      else
        Error
          (parse_aws_error (Some UpdateWorkflowRunResponse.error_of_json))