(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open Core
open Async
let json_arg = Command.Arg_type.create Yojson.Safe.from_string
let call ?endpoint_url ?profile ?region f m result_to_json error_to_json =
  let region =
    match region with
    | Some region -> Some (Awso.Region.of_string region)
    | None -> None in
  (Awso_async.Cfg.get_exn ?profile ?region ()) >>=
    (fun cfg ->
       (f ?endpoint_url ?cfg:(Some cfg) m) >>=
         (fun result ->
            match result with
            | Error err ->
                (match error_to_json with
                 | None ->
                     failwithf
                       "endpoint error, but no error values defined in boto"
                       ()
                 | Some to_json ->
                     let s = (err |> to_json) |> Yojson.Safe.to_string in
                     failwithf "AWS error: %s" s ())
            | Ok result ->
                ((match result_to_json with
                  | None -> print_endline "ok response from endpoint"
                  | Some to_json ->
                      ((result |> to_json) |> Yojson.Safe.to_string) |>
                        print_endline);
                 return ())))
let create_rule =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and description =
         flag "description" (optional string) ~doc:"STRING Description"
       and tags = flag "tags" (optional json_arg) ~doc:"JSON TagList"
       and resourceTags =
         flag "resource-tags" (optional json_arg) ~doc:"JSON ResourceTags"
       and retentionPeriod =
         flag "retention-period" (required json_arg)
           ~doc:"JSON RetentionPeriod"
       and resourceType =
         flag "resource-type" (required json_arg) ~doc:"JSON ResourceType" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.create_rule
           (Values.CreateRuleRequest.make ?description
              ?tags:(Option.map ~f:Values.TagList.of_json tags)
              ?resourceTags:(Option.map ~f:Values.ResourceTags.of_json
                               resourceTags)
              ~retentionPeriod:(Values.RetentionPeriod.of_json
                                  retentionPeriod)
              ~resourceType:(Values.ResourceType.of_json resourceType) ())
           (Some Values.CreateRuleResponse.to_json)
           (Some Values.CreateRuleResponse.error_to_json)])
let delete_rule =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and identifier =
         flag "identifier" (required string) ~doc:"STRING RuleIdentifier" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.delete_rule (Values.DeleteRuleRequest.make ~identifier ())
           (Some Values.DeleteRuleResponse.to_json)
           (Some Values.DeleteRuleResponse.error_to_json)])
let get_rule =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and identifier =
         flag "identifier" (required string) ~doc:"STRING RuleIdentifier" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.get_rule (Values.GetRuleRequest.make ~identifier ())
           (Some Values.GetRuleResponse.to_json)
           (Some Values.GetRuleResponse.error_to_json)])
let list_rules =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and maxResults =
         flag "max-results" (optional int) ~doc:"INT MaxResults"
       and nextToken =
         flag "next-token" (optional string) ~doc:"STRING NextToken"
       and resourceTags =
         flag "resource-tags" (optional json_arg) ~doc:"JSON ResourceTags"
       and resourceType =
         flag "resource-type" (required json_arg) ~doc:"JSON ResourceType" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_rules
           (Values.ListRulesRequest.make ?maxResults ?nextToken
              ?resourceTags:(Option.map ~f:Values.ResourceTags.of_json
                               resourceTags)
              ~resourceType:(Values.ResourceType.of_json resourceType) ())
           (Some Values.ListRulesResponse.to_json)
           (Some Values.ListRulesResponse.error_to_json)])
let list_tags_for_resource =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and resourceArn =
         flag "resource-arn" (required string) ~doc:"STRING RuleArn" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.list_tags_for_resource
           (Values.ListTagsForResourceRequest.make ~resourceArn ())
           (Some Values.ListTagsForResourceResponse.to_json)
           (Some Values.ListTagsForResourceResponse.error_to_json)])
let tag_resource =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and resourceArn =
         flag "resource-arn" (required string) ~doc:"STRING RuleArn"
       and tags = flag "tags" (required json_arg) ~doc:"JSON TagList" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.tag_resource
           (Values.TagResourceRequest.make ~resourceArn
              ~tags:(Values.TagList.of_json tags) ())
           (Some Values.TagResourceResponse.to_json)
           (Some Values.TagResourceResponse.error_to_json)])
let untag_resource =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and resourceArn =
         flag "resource-arn" (required string) ~doc:"STRING RuleArn"
       and tagKeys =
         flag "tag-keys" (required json_arg) ~doc:"JSON TagKeyList" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.untag_resource
           (Values.UntagResourceRequest.make ~resourceArn
              ~tagKeys:(Values.TagKeyList.of_json tagKeys) ())
           (Some Values.UntagResourceResponse.to_json)
           (Some Values.UntagResourceResponse.error_to_json)])
let update_rule =
  Command.async ~summary:""
    ([%map_open.Command
       let cli_profile =
         flag "-cli-profile" (optional string) ~doc:"NAME aws profile to use"
       and cli_region =
         flag "-cli-region" (optional string) ~doc:"REGION override region"
       and endpoint_url =
         flag "-endpoint-url" (optional string)
           ~doc:"URL override endpoint url"
       and retentionPeriod =
         flag "retention-period" (optional json_arg)
           ~doc:"JSON RetentionPeriod"
       and description =
         flag "description" (optional string) ~doc:"STRING Description"
       and resourceType =
         flag "resource-type" (optional json_arg) ~doc:"JSON ResourceType"
       and resourceTags =
         flag "resource-tags" (optional json_arg) ~doc:"JSON ResourceTags"
       and identifier =
         flag "identifier" (required string) ~doc:"STRING RuleIdentifier" in
       fun () ->
         call ?endpoint_url ?profile:cli_profile ?region:cli_region
           Io.update_rule
           (Values.UpdateRuleRequest.make
              ?retentionPeriod:(Option.map ~f:Values.RetentionPeriod.of_json
                                  retentionPeriod) ?description
              ?resourceType:(Option.map ~f:Values.ResourceType.of_json
                               resourceType)
              ?resourceTags:(Option.map ~f:Values.ResourceTags.of_json
                               resourceTags) ~identifier ())
           (Some Values.UpdateRuleResponse.to_json)
           (Some Values.UpdateRuleResponse.error_to_json)])
let main =
  Command.group
    ~summary:((Awso_codegen.Service.to_string Values.service) ^ " commands")
    [("create-rule", create_rule);
    ("delete-rule", delete_rule);
    ("get-rule", get_rule);
    ("list-rules", list_rules);
    ("list-tags-for-resource", list_tags_for_resource);
    ("tag-resource", tag_resource);
    ("untag-resource", untag_resource);
    ("update-rule", update_rule)]