(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open! Awso_common.Jane_compat
open Values
type ('i, 'o, 'e) t =
  | DeleteAlarms: (DeleteAlarmsInput.t, unit, unit) t 
  | DeleteAnomalyDetector: (DeleteAnomalyDetectorInput.t,
  DeleteAnomalyDetectorOutput.t, DeleteAnomalyDetectorOutput.error) t 
  | DeleteDashboards: (DeleteDashboardsInput.t, DeleteDashboardsOutput.t,
  DeleteDashboardsOutput.error) t 
  | DeleteInsightRules: (DeleteInsightRulesInput.t,
  DeleteInsightRulesOutput.t, DeleteInsightRulesOutput.error) t 
  | DeleteMetricStream: (DeleteMetricStreamInput.t,
  DeleteMetricStreamOutput.t, DeleteMetricStreamOutput.error) t 
  | DescribeAlarmHistory: (DescribeAlarmHistoryInput.t,
  DescribeAlarmHistoryOutput.t, DescribeAlarmHistoryOutput.error) t 
  | DescribeAlarms: (DescribeAlarmsInput.t, DescribeAlarmsOutput.t,
  DescribeAlarmsOutput.error) t 
  | DescribeAlarmsForMetric: (DescribeAlarmsForMetricInput.t,
  DescribeAlarmsForMetricOutput.t, DescribeAlarmsForMetricOutput.error) t 
  | DescribeAnomalyDetectors: (DescribeAnomalyDetectorsInput.t,
  DescribeAnomalyDetectorsOutput.t, DescribeAnomalyDetectorsOutput.error) t 
  | DescribeInsightRules: (DescribeInsightRulesInput.t,
  DescribeInsightRulesOutput.t, DescribeInsightRulesOutput.error) t 
  | DisableAlarmActions: (DisableAlarmActionsInput.t, unit, unit) t 
  | DisableInsightRules: (DisableInsightRulesInput.t,
  DisableInsightRulesOutput.t, DisableInsightRulesOutput.error) t 
  | EnableAlarmActions: (EnableAlarmActionsInput.t, unit, unit) t 
  | EnableInsightRules: (EnableInsightRulesInput.t,
  EnableInsightRulesOutput.t, EnableInsightRulesOutput.error) t 
  | GetDashboard: (GetDashboardInput.t, GetDashboardOutput.t,
  GetDashboardOutput.error) t 
  | GetInsightRuleReport: (GetInsightRuleReportInput.t,
  GetInsightRuleReportOutput.t, GetInsightRuleReportOutput.error) t 
  | GetMetricData: (GetMetricDataInput.t, GetMetricDataOutput.t,
  GetMetricDataOutput.error) t 
  | GetMetricStatistics: (GetMetricStatisticsInput.t,
  GetMetricStatisticsOutput.t, GetMetricStatisticsOutput.error) t 
  | GetMetricStream: (GetMetricStreamInput.t, GetMetricStreamOutput.t,
  GetMetricStreamOutput.error) t 
  | GetMetricWidgetImage: (GetMetricWidgetImageInput.t,
  GetMetricWidgetImageOutput.t, GetMetricWidgetImageOutput.error) t 
  | ListDashboards: (ListDashboardsInput.t, ListDashboardsOutput.t,
  ListDashboardsOutput.error) t 
  | ListMetricStreams: (ListMetricStreamsInput.t, ListMetricStreamsOutput.t,
  ListMetricStreamsOutput.error) t 
  | ListMetrics: (ListMetricsInput.t, ListMetricsOutput.t,
  ListMetricsOutput.error) t 
  | ListTagsForResource: (ListTagsForResourceInput.t,
  ListTagsForResourceOutput.t, ListTagsForResourceOutput.error) t 
  | PutAnomalyDetector: (PutAnomalyDetectorInput.t,
  PutAnomalyDetectorOutput.t, PutAnomalyDetectorOutput.error) t 
  | PutCompositeAlarm: (PutCompositeAlarmInput.t, unit, unit) t 
  | PutDashboard: (PutDashboardInput.t, PutDashboardOutput.t,
  PutDashboardOutput.error) t 
  | PutInsightRule: (PutInsightRuleInput.t, PutInsightRuleOutput.t,
  PutInsightRuleOutput.error) t 
  | PutMetricAlarm: (PutMetricAlarmInput.t, unit, unit) t 
  | PutMetricData: (PutMetricDataInput.t, unit, unit) t 
  | PutMetricStream: (PutMetricStreamInput.t, PutMetricStreamOutput.t,
  PutMetricStreamOutput.error) t 
  | SetAlarmState: (SetAlarmStateInput.t, unit, unit) t 
  | StartMetricStreams: (StartMetricStreamsInput.t,
  StartMetricStreamsOutput.t, StartMetricStreamsOutput.error) t 
  | StopMetricStreams: (StopMetricStreamsInput.t, StopMetricStreamsOutput.t,
  StopMetricStreamsOutput.error) t 
  | TagResource: (TagResourceInput.t, TagResourceOutput.t,
  TagResourceOutput.error) t 
  | UntagResource: (UntagResourceInput.t, UntagResourceOutput.t,
  UntagResourceOutput.error) t 
let method_of_endpoint : type i o e. (i, o, e) t -> _ =
  function
  | DeleteAlarms -> `POST
  | DeleteAnomalyDetector -> `POST
  | DeleteDashboards -> `POST
  | DeleteInsightRules -> `POST
  | DeleteMetricStream -> `POST
  | DescribeAlarmHistory -> `POST
  | DescribeAlarms -> `POST
  | DescribeAlarmsForMetric -> `POST
  | DescribeAnomalyDetectors -> `POST
  | DescribeInsightRules -> `POST
  | DisableAlarmActions -> `POST
  | DisableInsightRules -> `POST
  | EnableAlarmActions -> `POST
  | EnableInsightRules -> `POST
  | GetDashboard -> `POST
  | GetInsightRuleReport -> `POST
  | GetMetricData -> `POST
  | GetMetricStatistics -> `POST
  | GetMetricStream -> `POST
  | GetMetricWidgetImage -> `POST
  | ListDashboards -> `POST
  | ListMetricStreams -> `POST
  | ListMetrics -> `POST
  | ListTagsForResource -> `POST
  | PutAnomalyDetector -> `POST
  | PutCompositeAlarm -> `POST
  | PutDashboard -> `POST
  | PutInsightRule -> `POST
  | PutMetricAlarm -> `POST
  | PutMetricData -> `POST
  | PutMetricStream -> `POST
  | SetAlarmState -> `POST
  | StartMetricStreams -> `POST
  | StopMetricStreams -> `POST
  | TagResource -> `POST
  | UntagResource -> `POST
let uri_of_endpoint : type i o e. (i, o, e) t -> i -> Uri.t =
  ((fun endpoint x ->
      match endpoint with
      | DeleteAlarms -> (Format.kasprintf Uri.of_string) "/"
      | DeleteAnomalyDetector -> (Format.kasprintf Uri.of_string) "/"
      | DeleteDashboards -> (Format.kasprintf Uri.of_string) "/"
      | DeleteInsightRules -> (Format.kasprintf Uri.of_string) "/"
      | DeleteMetricStream -> (Format.kasprintf Uri.of_string) "/"
      | DescribeAlarmHistory -> (Format.kasprintf Uri.of_string) "/"
      | DescribeAlarms -> (Format.kasprintf Uri.of_string) "/"
      | DescribeAlarmsForMetric -> (Format.kasprintf Uri.of_string) "/"
      | DescribeAnomalyDetectors -> (Format.kasprintf Uri.of_string) "/"
      | DescribeInsightRules -> (Format.kasprintf Uri.of_string) "/"
      | DisableAlarmActions -> (Format.kasprintf Uri.of_string) "/"
      | DisableInsightRules -> (Format.kasprintf Uri.of_string) "/"
      | EnableAlarmActions -> (Format.kasprintf Uri.of_string) "/"
      | EnableInsightRules -> (Format.kasprintf Uri.of_string) "/"
      | GetDashboard -> (Format.kasprintf Uri.of_string) "/"
      | GetInsightRuleReport -> (Format.kasprintf Uri.of_string) "/"
      | GetMetricData -> (Format.kasprintf Uri.of_string) "/"
      | GetMetricStatistics -> (Format.kasprintf Uri.of_string) "/"
      | GetMetricStream -> (Format.kasprintf Uri.of_string) "/"
      | GetMetricWidgetImage -> (Format.kasprintf Uri.of_string) "/"
      | ListDashboards -> (Format.kasprintf Uri.of_string) "/"
      | ListMetricStreams -> (Format.kasprintf Uri.of_string) "/"
      | ListMetrics -> (Format.kasprintf Uri.of_string) "/"
      | ListTagsForResource -> (Format.kasprintf Uri.of_string) "/"
      | PutAnomalyDetector -> (Format.kasprintf Uri.of_string) "/"
      | PutCompositeAlarm -> (Format.kasprintf Uri.of_string) "/"
      | PutDashboard -> (Format.kasprintf Uri.of_string) "/"
      | PutInsightRule -> (Format.kasprintf Uri.of_string) "/"
      | PutMetricAlarm -> (Format.kasprintf Uri.of_string) "/"
      | PutMetricData -> (Format.kasprintf Uri.of_string) "/"
      | PutMetricStream -> (Format.kasprintf Uri.of_string) "/"
      | SetAlarmState -> (Format.kasprintf Uri.of_string) "/"
      | StartMetricStreams -> (Format.kasprintf Uri.of_string) "/"
      | StopMetricStreams -> (Format.kasprintf Uri.of_string) "/"
      | TagResource -> (Format.kasprintf Uri.of_string) "/"
      | UntagResource -> (Format.kasprintf Uri.of_string) "/")
  [@ocaml.warning "-27"])
let to_request (type i) (type o) (type e) (endp : (i, o, e) t) (req : i) =
  let _req = req in
  match endp with
  | DeleteAlarms ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta = [("Action", ["DeleteAlarms"]); ("Version", [apiVersion])] in
        let query =
          (DeleteAlarmsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DeleteAnomalyDetector ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DeleteAnomalyDetector"]); ("Version", [apiVersion])] in
        let query =
          (DeleteAnomalyDetectorInput.to_query req) |>
            Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DeleteDashboards ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DeleteDashboards"]); ("Version", [apiVersion])] in
        let query =
          (DeleteDashboardsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DeleteInsightRules ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DeleteInsightRules"]); ("Version", [apiVersion])] in
        let query =
          (DeleteInsightRulesInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DeleteMetricStream ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DeleteMetricStream"]); ("Version", [apiVersion])] in
        let query =
          (DeleteMetricStreamInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DescribeAlarmHistory ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DescribeAlarmHistory"]); ("Version", [apiVersion])] in
        let query =
          (DescribeAlarmHistoryInput.to_query req) |>
            Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DescribeAlarms ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DescribeAlarms"]); ("Version", [apiVersion])] in
        let query =
          (DescribeAlarmsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DescribeAlarmsForMetric ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DescribeAlarmsForMetric"]);
          ("Version", [apiVersion])] in
        let query =
          (DescribeAlarmsForMetricInput.to_query req) |>
            Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DescribeAnomalyDetectors ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DescribeAnomalyDetectors"]);
          ("Version", [apiVersion])] in
        let query =
          (DescribeAnomalyDetectorsInput.to_query req) |>
            Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DescribeInsightRules ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DescribeInsightRules"]); ("Version", [apiVersion])] in
        let query =
          (DescribeInsightRulesInput.to_query req) |>
            Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DisableAlarmActions ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DisableAlarmActions"]); ("Version", [apiVersion])] in
        let query =
          (DisableAlarmActionsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | DisableInsightRules ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["DisableInsightRules"]); ("Version", [apiVersion])] in
        let query =
          (DisableInsightRulesInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | EnableAlarmActions ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["EnableAlarmActions"]); ("Version", [apiVersion])] in
        let query =
          (EnableAlarmActionsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | EnableInsightRules ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["EnableInsightRules"]); ("Version", [apiVersion])] in
        let query =
          (EnableInsightRulesInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | GetDashboard ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta = [("Action", ["GetDashboard"]); ("Version", [apiVersion])] in
        let query =
          (GetDashboardInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | GetInsightRuleReport ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["GetInsightRuleReport"]); ("Version", [apiVersion])] in
        let query =
          (GetInsightRuleReportInput.to_query req) |>
            Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | GetMetricData ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta = [("Action", ["GetMetricData"]); ("Version", [apiVersion])] in
        let query =
          (GetMetricDataInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | GetMetricStatistics ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["GetMetricStatistics"]); ("Version", [apiVersion])] in
        let query =
          (GetMetricStatisticsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | GetMetricStream ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["GetMetricStream"]); ("Version", [apiVersion])] in
        let query =
          (GetMetricStreamInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | GetMetricWidgetImage ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["GetMetricWidgetImage"]); ("Version", [apiVersion])] in
        let query =
          (GetMetricWidgetImageInput.to_query req) |>
            Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | ListDashboards ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["ListDashboards"]); ("Version", [apiVersion])] in
        let query =
          (ListDashboardsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | ListMetricStreams ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["ListMetricStreams"]); ("Version", [apiVersion])] in
        let query =
          (ListMetricStreamsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | ListMetrics ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta = [("Action", ["ListMetrics"]); ("Version", [apiVersion])] in
        let query =
          (ListMetricsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | ListTagsForResource ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["ListTagsForResource"]); ("Version", [apiVersion])] in
        let query =
          (ListTagsForResourceInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | PutAnomalyDetector ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["PutAnomalyDetector"]); ("Version", [apiVersion])] in
        let query =
          (PutAnomalyDetectorInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | PutCompositeAlarm ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["PutCompositeAlarm"]); ("Version", [apiVersion])] in
        let query =
          (PutCompositeAlarmInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | PutDashboard ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta = [("Action", ["PutDashboard"]); ("Version", [apiVersion])] in
        let query =
          (PutDashboardInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | PutInsightRule ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["PutInsightRule"]); ("Version", [apiVersion])] in
        let query =
          (PutInsightRuleInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | PutMetricAlarm ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["PutMetricAlarm"]); ("Version", [apiVersion])] in
        let query =
          (PutMetricAlarmInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | PutMetricData ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta = [("Action", ["PutMetricData"]); ("Version", [apiVersion])] in
        let query =
          (PutMetricDataInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | PutMetricStream ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["PutMetricStream"]); ("Version", [apiVersion])] in
        let query =
          (PutMetricStreamInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | SetAlarmState ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta = [("Action", ["SetAlarmState"]); ("Version", [apiVersion])] in
        let query =
          (SetAlarmStateInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | StartMetricStreams ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["StartMetricStreams"]); ("Version", [apiVersion])] in
        let query =
          (StartMetricStreamsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | StopMetricStreams ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta =
          [("Action", ["StopMetricStreams"]); ("Version", [apiVersion])] in
        let query =
          (StopMetricStreamsInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | TagResource ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta = [("Action", ["TagResource"]); ("Version", [apiVersion])] in
        let query =
          (TagResourceInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
  | UntagResource ->
      let headers =
        Awso.Http.Headers.of_list
          [("content-type",
             "application/x-www-form-urlencoded; charset=utf-8")] in
      let body =
        let meta = [("Action", ["UntagResource"]); ("Version", [apiVersion])] in
        let query =
          (UntagResourceInput.to_query req) |> Awso.Client.Query.render in
        Some (Uri.encoded_of_query (meta @ query)) in
      Awso.Http.Request.make ?body ~headers (method_of_endpoint endp)
let of_response (type i) (type o) (type e) (endpoint : (i, o, e) t)
  (resp : Awso.Http.Response.t) : (o, e) result=
  let code = Awso.Http.Status.to_code (Awso.Http.Response.status resp) in
  let is_success = (code >= 200) && (code < 300) in
  let parse_aws_error error_of_xml =
    let body = Awso.Http.Response.body resp in
    let bail () =
      raise
        (Awso.Http.Io.Error.Bad_response
           { Awso.Http.Io.Error.code = code; body; x_amzn_error_type = None }) in
    match (error_of_xml, ((code >= 400) && (code <= 599))) with
    | (None, _) | (_, false) -> bail ()
    | (Some error_of_xml, true) ->
        (match Awso.Xml.parse_response body with
         | `Data _ -> bail ()
         | `El (((_, "ErrorResponse"), _), _) as error_response_xml ->
             let error_xml = Awso.Xml.child_exn error_response_xml "Error" in
             (try
                let error_code =
                  match Awso.Xml.child_exn error_xml "Code" with
                  | `Data error_code -> error_code
                  | `El (_, children) ->
                      (List.map children
                         ~f:(function | `Data s -> s | `El _ -> ""))
                        |> (String.concat ~sep:"") in
                error_of_xml (String.strip error_code) error_xml
              with | Failure _ -> bail ())
         | `El _ -> bail ()) in
  let _ = parse_aws_error in
  let _ = resp in
  match endpoint with
  | DeleteAlarms ->
      if is_success then Ok () else Error (parse_aws_error None)
  | DeleteAnomalyDetector ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (DeleteAnomalyDetectorOutput.of_xml xml)
      else
        Error
          (parse_aws_error (Some DeleteAnomalyDetectorOutput.error_of_xml))
  | DeleteDashboards ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (DeleteDashboardsOutput.of_xml xml)
      else Error (parse_aws_error (Some DeleteDashboardsOutput.error_of_xml))
  | DeleteInsightRules ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (DeleteInsightRulesOutput.of_xml xml)
      else
        Error (parse_aws_error (Some DeleteInsightRulesOutput.error_of_xml))
  | DeleteMetricStream ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (DeleteMetricStreamOutput.of_xml xml)
      else
        Error (parse_aws_error (Some DeleteMetricStreamOutput.error_of_xml))
  | DescribeAlarmHistory ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (DescribeAlarmHistoryOutput.of_xml xml)
      else
        Error
          (parse_aws_error (Some DescribeAlarmHistoryOutput.error_of_xml))
  | DescribeAlarms ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (DescribeAlarmsOutput.of_xml xml)
      else Error (parse_aws_error (Some DescribeAlarmsOutput.error_of_xml))
  | DescribeAlarmsForMetric ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (DescribeAlarmsForMetricOutput.of_xml xml)
      else Error (parse_aws_error None)
  | DescribeAnomalyDetectors ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (DescribeAnomalyDetectorsOutput.of_xml xml)
      else
        Error
          (parse_aws_error (Some DescribeAnomalyDetectorsOutput.error_of_xml))
  | DescribeInsightRules ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (DescribeInsightRulesOutput.of_xml xml)
      else
        Error
          (parse_aws_error (Some DescribeInsightRulesOutput.error_of_xml))
  | DisableAlarmActions ->
      if is_success then Ok () else Error (parse_aws_error None)
  | DisableInsightRules ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (DisableInsightRulesOutput.of_xml xml)
      else
        Error (parse_aws_error (Some DisableInsightRulesOutput.error_of_xml))
  | EnableAlarmActions ->
      if is_success then Ok () else Error (parse_aws_error None)
  | EnableInsightRules ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (EnableInsightRulesOutput.of_xml xml)
      else
        Error (parse_aws_error (Some EnableInsightRulesOutput.error_of_xml))
  | GetDashboard ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (GetDashboardOutput.of_xml xml)
      else Error (parse_aws_error (Some GetDashboardOutput.error_of_xml))
  | GetInsightRuleReport ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (GetInsightRuleReportOutput.of_xml xml)
      else
        Error
          (parse_aws_error (Some GetInsightRuleReportOutput.error_of_xml))
  | GetMetricData ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (GetMetricDataOutput.of_xml xml)
      else Error (parse_aws_error (Some GetMetricDataOutput.error_of_xml))
  | GetMetricStatistics ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (GetMetricStatisticsOutput.of_xml xml)
      else
        Error (parse_aws_error (Some GetMetricStatisticsOutput.error_of_xml))
  | GetMetricStream ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (GetMetricStreamOutput.of_xml xml)
      else Error (parse_aws_error (Some GetMetricStreamOutput.error_of_xml))
  | GetMetricWidgetImage ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (GetMetricWidgetImageOutput.of_xml xml)
      else Error (parse_aws_error None)
  | ListDashboards ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (ListDashboardsOutput.of_xml xml)
      else Error (parse_aws_error (Some ListDashboardsOutput.error_of_xml))
  | ListMetricStreams ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (ListMetricStreamsOutput.of_xml xml)
      else
        Error (parse_aws_error (Some ListMetricStreamsOutput.error_of_xml))
  | ListMetrics ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (ListMetricsOutput.of_xml xml)
      else Error (parse_aws_error (Some ListMetricsOutput.error_of_xml))
  | ListTagsForResource ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (ListTagsForResourceOutput.of_xml xml)
      else
        Error (parse_aws_error (Some ListTagsForResourceOutput.error_of_xml))
  | PutAnomalyDetector ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (PutAnomalyDetectorOutput.of_xml xml)
      else
        Error (parse_aws_error (Some PutAnomalyDetectorOutput.error_of_xml))
  | PutCompositeAlarm ->
      if is_success then Ok () else Error (parse_aws_error None)
  | PutDashboard ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (PutDashboardOutput.of_xml xml)
      else Error (parse_aws_error (Some PutDashboardOutput.error_of_xml))
  | PutInsightRule ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (PutInsightRuleOutput.of_xml xml)
      else Error (parse_aws_error (Some PutInsightRuleOutput.error_of_xml))
  | PutMetricAlarm ->
      if is_success then Ok () else Error (parse_aws_error None)
  | PutMetricData ->
      if is_success then Ok () else Error (parse_aws_error None)
  | PutMetricStream ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (PutMetricStreamOutput.of_xml xml)
      else Error (parse_aws_error (Some PutMetricStreamOutput.error_of_xml))
  | SetAlarmState ->
      if is_success then Ok () else Error (parse_aws_error None)
  | StartMetricStreams ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (StartMetricStreamsOutput.of_xml xml)
      else
        Error (parse_aws_error (Some StartMetricStreamsOutput.error_of_xml))
  | StopMetricStreams ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (StopMetricStreamsOutput.of_xml xml)
      else
        Error (parse_aws_error (Some StopMetricStreamsOutput.error_of_xml))
  | TagResource ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (TagResourceOutput.of_xml xml)
      else Error (parse_aws_error (Some TagResourceOutput.error_of_xml))
  | UntagResource ->
      if is_success
      then
        let xml = Awso.Xml.parse_response (Awso.Http.Response.body resp) in
        Ok (UntagResourceOutput.of_xml xml)
      else Error (parse_aws_error (Some UntagResourceOutput.error_of_xml))