(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso *)
open! Awso_common.Jane_compat
open Values
type ('i, 'o, 'e) t =
  | DescribeAcceleratorOfferings: (DescribeAcceleratorOfferingsRequest.t,
  DescribeAcceleratorOfferingsResponse.t,
  DescribeAcceleratorOfferingsResponse.error) t 
  | DescribeAcceleratorTypes: (DescribeAcceleratorTypesRequest.t,
  DescribeAcceleratorTypesResponse.t, DescribeAcceleratorTypesResponse.error)
  t 
  | DescribeAccelerators: (DescribeAcceleratorsRequest.t,
  DescribeAcceleratorsResponse.t, DescribeAcceleratorsResponse.error) t 
  | ListTagsForResource: (ListTagsForResourceRequest.t,
  ListTagsForResourceResult.t, ListTagsForResourceResult.error) t 
  | TagResource: (TagResourceRequest.t, TagResourceResult.t,
  TagResourceResult.error) t 
  | UntagResource: (UntagResourceRequest.t, UntagResourceResult.t,
  UntagResourceResult.error) t 
let method_of_endpoint : type i o e. (i, o, e) t -> _ =
  function
  | DescribeAcceleratorOfferings -> `POST
  | DescribeAcceleratorTypes -> `GET
  | DescribeAccelerators -> `POST
  | ListTagsForResource -> `GET
  | TagResource -> `POST
  | UntagResource -> `DELETE
let uri_of_endpoint : type i o e. (i, o, e) t -> i -> Uri.t =
  ((fun endpoint x ->
      match endpoint with
      | DescribeAcceleratorOfferings ->
          (Format.kasprintf Uri.of_string) "/describe-accelerator-offerings"
      | DescribeAcceleratorTypes ->
          (Format.kasprintf Uri.of_string) "/describe-accelerator-types"
      | DescribeAccelerators ->
          (Format.kasprintf Uri.of_string) "/describe-accelerators"
      | ListTagsForResource ->
          (Format.kasprintf Uri.of_string) "/tags/%s"
            (ResourceARN.to_header x.ListTagsForResourceRequest.resourceArn)
      | TagResource ->
          (Format.kasprintf Uri.of_string) "/tags/%s"
            (ResourceARN.to_header x.TagResourceRequest.resourceArn)
      | UntagResource ->
          Uri.add_query_params'
            ((Format.kasprintf Uri.of_string) "/tags/%s"
               (ResourceARN.to_header x.UntagResourceRequest.resourceArn))
            (List.filter_opt
               [Some ("tagKeys", (TagKeyList.to_header x.tagKeys))]))
  [@ocaml.warning "-27"])
let to_request (type i) (type o) (type e) (endp : (i, o, e) t) (req : i) =
  let _req = req in
  match endp with
  | DescribeAcceleratorOfferings ->
      let (headers, body) =
        let headers =
          Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map
                   (List.filter_opt
                      [Some
                         ("locationType",
                           (LocationType.to_value
                              req.DescribeAcceleratorOfferingsRequest.locationType));
                      Option.map
                        req.DescribeAcceleratorOfferingsRequest.acceleratorTypes
                        ~f:(fun x ->
                              ("acceleratorTypes",
                                (AcceleratorTypeNameList.to_value x)))])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | DescribeAcceleratorTypes ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | DescribeAccelerators ->
      let (headers, body) =
        let headers =
          Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map
                   (List.filter_opt
                      [Option.map
                         req.DescribeAcceleratorsRequest.acceleratorIds
                         ~f:(fun x ->
                               ("acceleratorIds",
                                 (AcceleratorIdList.to_value x)));
                      Option.map req.DescribeAcceleratorsRequest.filters
                        ~f:(fun x -> ("filters", (FilterList.to_value x)));
                      Option.map req.DescribeAcceleratorsRequest.maxResults
                        ~f:(fun x -> ("maxResults", (MaxResults.to_value x)));
                      Option.map req.DescribeAcceleratorsRequest.nextToken
                        ~f:(fun x -> ("nextToken", (NextToken.to_value x)))])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | ListTagsForResource ->
      let (headers, body) = (None, None) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | TagResource ->
      let (headers, body) =
        let headers =
          Some ((List.filter_opt []) |> Awso.Http.Headers.of_list) in
        let body =
          Some
            ((`Assoc
                (List.map
                   (List.filter_opt
                      [Some
                         ("tags",
                           (TagMap.to_value req.TagResourceRequest.tags))])
                   ~f:(fun (x, y) ->
                         let value =
                           Awso.Botodata.Json.value_to_json_scalar y in
                         (x, value))))
               |> Yojson.Safe.to_string) in
        (headers, body) in
      Awso.Http.Request.make ?headers ?body (method_of_endpoint endp)
  | UntagResource -> Awso.Http.Request.make (method_of_endpoint endp)
let of_response (type i) (type o) (type e) (endpoint : (i, o, e) t)
  (resp : (Awso.Http.Response.t, Awso.Http.Io.Error.call) result) :
  (o, [ `AWS of e  | `Transport of Awso.Http.Io.Error.call ]) result=
  let handle_error err error_of_json =
    match err with
    | `Too_many_redirects -> Error (`Transport `Too_many_redirects)
    | `Bad_response
        { Awso.Http.Io.Error.code = code; body; x_amzn_error_type } ->
        let generic_error () =
          Error
            (`Transport
               (`Bad_response
                  { Awso.Http.Io.Error.code = code; body; x_amzn_error_type })) in
        (match (x_amzn_error_type, error_of_json,
                 ((code >= 400) && (code <= 599)))
         with
         | (Some error_type, Some error_of_json, true) ->
             let json = Yojson.Safe.from_string body in
             Error (`AWS (error_of_json error_type json))
         | (None, Some error_of_json, true) ->
             (try
                let json = Yojson.Safe.from_string body in
                match json |> (Yojson.Safe.Util.member "__type") with
                | `String error_type ->
                    let error_type =
                      match String.lsplit2 error_type ~on:'#' with
                      | Some (_, s) -> s
                      | None -> error_type in
                    Error (`AWS (error_of_json error_type json))
                | `Null -> generic_error ()
                | _ ->
                    failwithf "Error '__type' did not have string type: %s"
                      body ()
              with | _ -> generic_error ())
         | (None, _, _) | (_, None, _) | (_, _, false) -> generic_error ()) in
  let response_to_json resp =
    Yojson.Safe.from_string (Awso.Http.Response.body resp) in
  let _ = resp in
  let _ = handle_error in
  let _ = response_to_json in
  match endpoint with
  | DescribeAcceleratorOfferings ->
      (match resp with
       | Error err ->
           handle_error err
             (Some DescribeAcceleratorOfferingsResponse.error_of_json)
       | Ok resp ->
           Ok
             (DescribeAcceleratorOfferingsResponse.of_json
                (response_to_json resp)))
  | DescribeAcceleratorTypes ->
      (match resp with
       | Error err ->
           handle_error err
             (Some DescribeAcceleratorTypesResponse.error_of_json)
       | Ok resp ->
           Ok
             (DescribeAcceleratorTypesResponse.of_json
                (response_to_json resp)))
  | DescribeAccelerators ->
      (match resp with
       | Error err ->
           handle_error err (Some DescribeAcceleratorsResponse.error_of_json)
       | Ok resp ->
           Ok (DescribeAcceleratorsResponse.of_json (response_to_json resp)))
  | ListTagsForResource ->
      (match resp with
       | Error err ->
           handle_error err (Some ListTagsForResourceResult.error_of_json)
       | Ok resp ->
           Ok (ListTagsForResourceResult.of_json (response_to_json resp)))
  | TagResource ->
      (match resp with
       | Error err -> handle_error err (Some TagResourceResult.error_of_json)
       | Ok resp ->
           let headers =
             Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
           Ok (TagResourceResult.of_header_and_body (headers, ())))
  | UntagResource ->
      (match resp with
       | Error err ->
           handle_error err (Some UntagResourceResult.error_of_json)
       | Ok resp ->
           let headers =
             Awso.Http.Headers.to_list (Awso.Http.Response.headers resp) in
           Ok (UntagResourceResult.of_header_and_body (headers, ())))