(* generated by: awso-codegen generate-all --botocore-data vendor/botocore/botocore/data -o aws --runtime-dir lib/runtime/awso --cli-dir awso-cli *)
open! Awso_common.Jane_compat
open Values
type ('i, 'o, 'e) t =
  | AcceptConnectionProposal: (AcceptConnectionProposalRequest.t,
  AcceptConnectionProposalResponse.t, AcceptConnectionProposalResponse.error)
  t 
  | CreateConnection: (CreateConnectionRequest.t, CreateConnectionResponse.t,
  CreateConnectionResponse.error) t 
  | DeleteConnection: (DeleteConnectionRequest.t, DeleteConnectionResponse.t,
  DeleteConnectionResponse.error) t 
  | DescribeConnectionProposal: (DescribeConnectionProposalRequest.t,
  DescribeConnectionProposalResponse.t,
  DescribeConnectionProposalResponse.error) t 
  | GetConnection: (GetConnectionRequest.t, GetConnectionResponse.t,
  GetConnectionResponse.error) t 
  | GetEnvironment: (GetEnvironmentRequest.t, GetEnvironmentResponse.t,
  GetEnvironmentResponse.error) t 
  | ListAttachPoints: (ListAttachPointsRequest.t, ListAttachPointsResponse.t,
  ListAttachPointsResponse.error) t 
  | ListConnections: (ListConnectionsRequest.t, ListConnectionsResponse.t,
  ListConnectionsResponse.error) t 
  | ListEnvironments: (ListEnvironmentsRequest.t, ListEnvironmentsResponse.t,
  ListEnvironmentsResponse.error) t 
  | ListTagsForResource: (ListTagsForResourceRequest.t,
  ListTagsForResourceResponse.t, ListTagsForResourceResponse.error) t 
  | TagResource: (TagResourceRequest.t, TagResourceResponse.t,
  TagResourceResponse.error) t 
  | UntagResource: (UntagResourceRequest.t, UntagResourceResponse.t,
  UntagResourceResponse.error) t 
  | UpdateConnection: (UpdateConnectionRequest.t, UpdateConnectionResponse.t,
  UpdateConnectionResponse.error) t 
let method_of_endpoint : type i o e. (i, o, e) t -> _ =
  function
  | AcceptConnectionProposal -> `POST
  | CreateConnection -> `POST
  | DeleteConnection -> `POST
  | DescribeConnectionProposal -> `POST
  | GetConnection -> `POST
  | GetEnvironment -> `POST
  | ListAttachPoints -> `POST
  | ListConnections -> `POST
  | ListEnvironments -> `POST
  | ListTagsForResource -> `POST
  | TagResource -> `POST
  | UntagResource -> `POST
  | UpdateConnection -> `POST
let uri_of_endpoint : type i o e. (i, o, e) t -> i -> Uri.t =
  ((fun endpoint x ->
      match endpoint with
      | AcceptConnectionProposal -> (Format.kasprintf Uri.of_string) "/"
      | CreateConnection -> (Format.kasprintf Uri.of_string) "/"
      | DeleteConnection -> (Format.kasprintf Uri.of_string) "/"
      | DescribeConnectionProposal -> (Format.kasprintf Uri.of_string) "/"
      | GetConnection -> (Format.kasprintf Uri.of_string) "/"
      | GetEnvironment -> (Format.kasprintf Uri.of_string) "/"
      | ListAttachPoints -> (Format.kasprintf Uri.of_string) "/"
      | ListConnections -> (Format.kasprintf Uri.of_string) "/"
      | ListEnvironments -> (Format.kasprintf Uri.of_string) "/"
      | ListTagsForResource -> (Format.kasprintf Uri.of_string) "/"
      | TagResource -> (Format.kasprintf Uri.of_string) "/"
      | UntagResource -> (Format.kasprintf Uri.of_string) "/"
      | UpdateConnection -> (Format.kasprintf Uri.of_string) "/")
  [@ocaml.warning "-27"])
let to_request (type i) (type o) (type e) (endp : (i, o, e) t) (req : i) =
  match endp with
  | AcceptConnectionProposal ->
      let json = AcceptConnectionProposalRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.AcceptConnectionProposal")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | CreateConnection ->
      let json = CreateConnectionRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.CreateConnection")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DeleteConnection ->
      let json = DeleteConnectionRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.DeleteConnection")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | DescribeConnectionProposal ->
      let json = DescribeConnectionProposalRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.DescribeConnectionProposal")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetConnection ->
      let json = GetConnectionRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.GetConnection")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | GetEnvironment ->
      let json = GetEnvironmentRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.GetEnvironment")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListAttachPoints ->
      let json = ListAttachPointsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.ListAttachPoints")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListConnections ->
      let json = ListConnectionsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.ListConnections")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListEnvironments ->
      let json = ListEnvironmentsRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.ListEnvironments")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | ListTagsForResource ->
      let json = ListTagsForResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.ListTagsForResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | TagResource ->
      let json = TagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.TagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UntagResource ->
      let json = UntagResourceRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.UntagResource")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
  | UpdateConnection ->
      let json = UpdateConnectionRequest.to_json req in
      let body = Yojson.Safe.to_string json in
      let headers =
        Awso.Http.Headers.of_list
          [("Content-Type", "application/x-amz-json-1.0");
          ("X-Amz-Target", "Interconnect.UpdateConnection")] in
      Awso.Http.Request.make ~body ~headers (method_of_endpoint endp)
let of_response (type i) (type o) (type e) (endpoint : (i, o, e) t)
  (resp : Awso.Http.Response.t) : (o, e) result=
  let code = Awso.Http.Status.to_code (Awso.Http.Response.status resp) in
  let is_success = (code >= 200) && (code < 300) in
  let parse_aws_error error_of_json =
    let body = Awso.Http.Response.body resp in
    let bail () =
      raise
        (Awso.Http.Io.Error.Bad_response
           { Awso.Http.Io.Error.code = code; body; x_amzn_error_type = None }) in
    match (error_of_json, ((code >= 400) && (code <= 599))) with
    | (Some error_of_json, true) ->
        let json = Yojson.Safe.from_string body in
        (match json |> (Yojson.Safe.Util.member "__type") with
         | `String error_type -> error_of_json error_type json
         | `Null -> bail ()
         | _ ->
             failwith
               (sprintf "Error '__type' did not have string type: %s" body))
    | (None, _) | (_, false) -> bail () in
  let _ = parse_aws_error in
  let _ = resp in
  match endpoint with
  | AcceptConnectionProposal ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (AcceptConnectionProposalResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some AcceptConnectionProposalResponse.error_of_json))
  | CreateConnection ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (CreateConnectionResponse.of_json json)
      else
        Error (parse_aws_error (Some CreateConnectionResponse.error_of_json))
  | DeleteConnection ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (DeleteConnectionResponse.of_json json)
      else
        Error (parse_aws_error (Some DeleteConnectionResponse.error_of_json))
  | DescribeConnectionProposal ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (DescribeConnectionProposalResponse.of_json json)
      else
        Error
          (parse_aws_error
             (Some DescribeConnectionProposalResponse.error_of_json))
  | GetConnection ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetConnectionResponse.of_json json)
      else Error (parse_aws_error (Some GetConnectionResponse.error_of_json))
  | GetEnvironment ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (GetEnvironmentResponse.of_json json)
      else
        Error (parse_aws_error (Some GetEnvironmentResponse.error_of_json))
  | ListAttachPoints ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListAttachPointsResponse.of_json json)
      else
        Error (parse_aws_error (Some ListAttachPointsResponse.error_of_json))
  | ListConnections ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListConnectionsResponse.of_json json)
      else
        Error (parse_aws_error (Some ListConnectionsResponse.error_of_json))
  | ListEnvironments ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListEnvironmentsResponse.of_json json)
      else
        Error (parse_aws_error (Some ListEnvironmentsResponse.error_of_json))
  | ListTagsForResource ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (ListTagsForResourceResponse.of_json json)
      else
        Error
          (parse_aws_error (Some ListTagsForResourceResponse.error_of_json))
  | TagResource ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (TagResourceResponse.of_json json)
      else Error (parse_aws_error (Some TagResourceResponse.error_of_json))
  | UntagResource ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (UntagResourceResponse.of_json json)
      else Error (parse_aws_error (Some UntagResourceResponse.error_of_json))
  | UpdateConnection ->
      if is_success
      then
        let json = Yojson.Safe.from_string (Awso.Http.Response.body resp) in
        Ok (UpdateConnectionResponse.of_json json)
      else
        Error (parse_aws_error (Some UpdateConnectionResponse.error_of_json))